from sqlalchemy import TIMESTAMP, BigInteger, Column, Integer, SmallInteger, String, func

# from sqlalchemy.ext.declarative import declarative_base
# from app.db.mysql import Base  # ini harus declarative_base()
# Base = declarative_base()
# pylint: disable=E1102
from app.db.mysql import BaseDB1


class InvAp2(BaseDB1):
    __tablename__ = "inv_ap2"
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    NO_INVOICE = Column(String(255), nullable=True)
    TANGGAL = Column(String(255), nullable=False)
    SMU = Column(String(255), nullable=False)
    KDAIRLINE = Column(String(255), nullable=False)
    FLIGHT_NUMBER = Column(String(255), nullable=False)
    DOM_INT = Column(String(255), nullable=False)
    INC_OUT = Column(String(255), nullable=False)
    ASAL = Column(String(255), nullable=False)
    TUJUAN = Column(String(255), nullable=False)
    JENIS_KARGO = Column(String(255), nullable=False)
    TARIF_KARGO = Column(String(255), nullable=False)
    KOLI = Column(String(255), nullable=False)
    BERAT = Column(String(255), nullable=False)
    VOLUME = Column(String(255), nullable=False)
    JML_HARI = Column(String(255), nullable=False)
    CARGO_CHG = Column(String(255), nullable=False)
    KADE = Column(String(255), nullable=False)
    TOTAL_PENDAPATAN_TANPA_PPN = Column(String(255), nullable=False)
    TOTAL_PENDAPATAN_DENGAN_PPN = Column(String(255), nullable=False)

    PJT_HANDLING_FEE = Column(Integer, nullable=True)
    RUSH_HANDLING_FEE = Column(Integer, nullable=True)
    RUSH_SERVICE_FEE = Column(Integer, nullable=True)
    TRANSHIPMENT_FEE = Column(Integer, nullable=True)
    ADMINISTRATION_FEE = Column(Integer, nullable=True)
    DOCUMENTS_FEE = Column(Integer, nullable=True)
    PECAH_PU_FEE = Column(Integer, nullable=True)
    COOL_COLD_STORAGE_FEE = Column(Integer, nullable=True)
    STRONG_ROOM_FEE = Column(Integer, nullable=True)
    AC_ROOM_FEE = Column(Integer, nullable=True)
    DG_ROOM_FEE = Column(Integer, nullable=True)
    AVI_ROOM_FEE = Column(Integer, nullable=True)
    DANGEROUS_GOOD_CHECK_FEE = Column(Integer, nullable=True)
    DISCOUNT_FEE = Column(Integer, nullable=True)
    RKSP_FEE = Column(Integer, nullable=True)

    HAWB = Column(String(255), nullable=False)
    HAWB_FEE = Column(Integer, nullable=True)
    HAWB_MAWB_FEE = Column(Integer, nullable=True)
    CSC_FEE = Column(Integer, nullable=True)
    ENVIROTAINER_ELEC_FEE = Column(Integer, nullable=True)
    ADDITIONAL_COSTS = Column(Integer, nullable=True)
    NAWB_FEE = Column(Integer, nullable=True)
    BARCODE_FEE = Column(Integer, nullable=True)
    CARGO_DEVELOPMENT_FEE = Column(Integer, nullable=True)
    DUTIABLE_SHIPMENT_FEE = Column(Integer, nullable=True)
    FHL_FEE = Column(Integer, nullable=True)
    FWB_FEE = Column(Integer, nullable=True)
    CARGO_INSPECTION_REPORT_FEE = Column(Integer, nullable=True)
    MATERAI_FEE = Column(Integer, nullable=True)
    PPN_FEE = Column(Integer, nullable=True)

    status = Column(SmallInteger, nullable=False, default=1)
    created_at = Column(TIMESTAMP, server_default=func.now(), nullable=False)
    updated_at = Column(TIMESTAMP, server_default=func.now(), onupdate=func.now(), nullable=False)
