production:
  script:
    - echo "🚀 Deploying to Production"
    - ssh -o StrictHostKeyChecking=no root@$server -p 23022 $script
  only:
    - production

development:
  script:
    - echo "🧩 Deploying Development"
    - ssh -o StrictHostKeyChecking=no root@$server -p 23022 "bash /home/wisnu/mau-app/deploy-development.sh"
  only:
    - master
