version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: DockerfileBackend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ENV: production
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: DockerfileFrontend
    container_name: astro-frontend
    ports:
      - "4321:4321"
    depends_on:
      - backend
    restart: unless-stopped
