version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: DockerfileBackend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://myapp_user:myapp_pass@mariadb:3306/myapp_db
      ENV: production
    networks:
      - shared_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: DockerfileFrontend
    container_name: astro-frontend
    ports:
      - "4321:4321"
    depends_on:
      - backend
    networks:
      - shared_network
    restart: unless-stopped

networks:
  shared_network:
    external: true
