# ruff: noqa: N815

from sqlalchemy import DECIMAL, TIMESTAMP, BigInteger, Boolean, Column, Integer, String
from sqlalchemy.sql import func

from app.db.mysql import BaseDB2


class ImpHostAWB(BaseDB2):
    __tablename__ = "imp_hostawb"

    noid = Column(BigInteger, primary_key=True, autoincrement=True)
    MasterAWB = Column(String(15))
    HostAWB = Column(String(25))
    tglAWB = Column(String(10))
    tglMasterAWB = Column(String(10))
    Quantity = Column(Integer)
    Weight = Column(DECIMAL(10, 2))
    Volume = Column(DECIMAL(10, 2))
    airlinescode = Column(String(2))
    FlightNo = Column(String(7))
    DateOfFlight = Column(String(10))
    Origin = Column(String(6))
    HSCode = Column(String(8))
    DescriptionGoods = Column(String(150))
    AgenCode = Column(String(19))
    ShipperCode = Column(String(19))
    shippername = Column(String(60))
    shipperaddress = Column(String(200))
    shippercity = Column(String(50))
    shippercountry = Column(String(50))
    shipperpostal = Column(String(10))
    ConsigneeCode = Column(String(19))
    Consigneename = Column(String(60))
    Consigneeaddress = Column(String(200))
    Consigneecity = Column(String(50))
    Consigneecountry = Column(String(50))
    Consigneepostal = Column(String(10))
    ConsigneeTaxNo = Column(String(15))
    bc11 = Column(String(15))
    tglbc = Column(String(10))
    nopos = Column(String(4))
    subpos = Column(String(4))
    subsubpos = Column(String(4))
    noplp = Column(String(6))
    tglplp = Column(String(10))
    typeClearance = Column(String(10))
    SPPB = Column(String(6))
    TGLSPPB = Column(String(10))
    LOCATION = Column(String(10))
    DateOfOut = Column(String(10))
    TimeOut = Column(String(5))
    DateOfIn = Column(String(10))
    TimeIn = Column(String(5))
    BagNumber = Column(String(100))
    DateEntry = Column(String(10))
    TimeEntry = Column(String(8))
    flagDO = Column(Boolean, default=False)
    void = Column(Boolean, default=False)
    token = Column(String(5))
    flag_in = Column(Boolean, default=False)
    flag_out = Column(Boolean, default=False)
    created_at = Column(TIMESTAMP, nullable=False, server_default=func.current_timestamp())
