"""create_inv_ap2_table

Revision ID: 2686e10f671a
Revises: 3ba3103b0a70
Create Date: 2025-09-06 01:21:15.253773

"""

# pylint: disable=E1102

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2686e10f671a"
down_revision: str | None = "3ba3103b0a70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inv_ap2",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("NO_INVOICE", sa.String(255), nullable=True),
        sa.Column("TANGGAL", sa.String(255), nullable=False),
        sa.Column("SMU", sa.String(255), nullable=False),
        sa.Column("KDAIRLINE", sa.String(255), nullable=False),
        sa.Column("FLIGHT_NUMBER", sa.String(255), nullable=False),
        sa.Column("DOM_INT", sa.String(255), nullable=False),
        sa.Column("INC_OUT", sa.String(255), nullable=False),
        sa.Column("ASAL", sa.String(255), nullable=False),
        sa.Column("TUJUAN", sa.String(255), nullable=False),
        sa.Column("JENIS_KARGO", sa.String(255), nullable=False),
        sa.Column("TARIF_KARGO", sa.String(255), nullable=False),
        sa.Column("KOLI", sa.String(255), nullable=False),
        sa.Column("BERAT", sa.String(255), nullable=False),
        sa.Column("VOLUME", sa.String(255), nullable=False),
        sa.Column("JML_HARI", sa.String(255), nullable=False),
        sa.Column("CARGO_CHG", sa.String(255), nullable=False),
        sa.Column("KADE", sa.String(255), nullable=False),
        sa.Column("TOTAL_PENDAPATAN_TANPA_PPN", sa.String(255), nullable=False),
        sa.Column("TOTAL_PENDAPATAN_DENGAN_PPN", sa.String(255), nullable=False),
        sa.Column("PJT_HANDLING_FEE", sa.Integer, nullable=True),
        sa.Column("RUSH_HANDLING_FEE", sa.Integer, nullable=True),
        sa.Column("RUSH_SERVICE_FEE", sa.Integer, nullable=True),
        sa.Column("TRANSHIPMENT_FEE", sa.Integer, nullable=True),
        sa.Column("ADMINISTRATION_FEE", sa.Integer, nullable=True),
        sa.Column("DOCUMENTS_FEE", sa.Integer, nullable=True),
        sa.Column("PECAH_PU_FEE", sa.Integer, nullable=True),
        sa.Column("COOL_COLD_STORAGE_FEE", sa.Integer, nullable=True),
        sa.Column("STRONG_ROOM_FEE", sa.Integer, nullable=True),
        sa.Column("AC_ROOM_FEE", sa.Integer, nullable=True),
        sa.Column("DG_ROOM_FEE", sa.Integer, nullable=True),
        sa.Column("AVI_ROOM_FEE", sa.Integer, nullable=True),
        sa.Column("DANGEROUS_GOOD_CHECK_FEE", sa.Integer, nullable=True),
        sa.Column("DISCOUNT_FEE", sa.Integer, nullable=True),
        sa.Column("RKSP_FEE", sa.Integer, nullable=True),
        sa.Column("HAWB", sa.String(255), nullable=False),
        sa.Column("HAWB_FEE", sa.Integer, nullable=True),
        sa.Column("HAWB_MAWB_FEE", sa.Integer, nullable=True),
        sa.Column("CSC_FEE", sa.Integer, nullable=True),
        sa.Column("ENVIROTAINER_ELEC_FEE", sa.Integer, nullable=True),
        sa.Column("ADDITIONAL_COSTS", sa.Integer, nullable=True),
        sa.Column("NAWB_FEE", sa.Integer, nullable=True),
        sa.Column("BARCODE_FEE", sa.Integer, nullable=True),
        sa.Column("CARGO_DEVELOPMENT_FEE", sa.Integer, nullable=True),
        sa.Column("DUTIABLE_SHIPMENT_FEE", sa.Integer, nullable=True),
        sa.Column("FHL_FEE", sa.Integer, nullable=True),
        sa.Column("FWB_FEE", sa.Integer, nullable=True),
        sa.Column("CARGO_INSPECTION_REPORT_FEE", sa.Integer, nullable=True),
        sa.Column("MATERAI_FEE", sa.Integer, nullable=True),
        sa.Column("PPN_FEE", sa.Integer, nullable=True),
        sa.Column("status", sa.SmallInteger, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP, server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP,
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    )
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inv_ap2")
    # ### end Alembic commands ###
