"""create_respons_inv_ap2_table

Revision ID: 3b7fe30a8651
Revises: 2686e10f671a
Create Date: 2025-09-06 01:41:08.891080

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b7fe30a8651'
down_revision: str | None = '2686e10f671a' # kalau ada migrasi sebelumnya, isi dengan revision_id-nya
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'respons_inv_ap2',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('inv', sa.String(255), nullable=True),
        sa.Column('response', sa.Text, nullable=True),
        sa.Column('status', sa.String(255), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP, server_default=sa.func.now(), nullable=False),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP,
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('respons_inv_ap2')