from sqlalchemy import Column, Date, DateTime, Integer, Numeric, String, Text
from sqlalchemy.sql import func

from app.db.mysql import BaseDB1


class Fwb(BaseDB1):
    __tablename__ = "fwb"

    id = Column(Integer, primary_key=True, autoincrement=True)
    mawb = Column(String(20), nullable=False)

    shipper_name = Column(String(35))
    shipper_address = Column(String(70))
    consignee_name = Column(String(35))
    consignee_address = Column(String(70))

    flight_no = Column(String(5))
    flight_date = Column(DateTime)
    origin = Column(String(3))
    destination = Column(String(3))
    routing = Column(String(120))

    pieces = Column(Integer)
    weight = Column(Numeric(10, 3))
    volume = Column(Numeric(12, 3))
    goods_description = Column(String(20))

    chargeable_weight = Column(Numeric(10, 3))
    rate_class = Column(String(1))
    total_charge = Column(Numeric(14, 2))
    raw_message = Column(Text)

    message_type = Column(String(3))
    message_version = Column(String(3))
    awb_prefix = Column(String(3))
    awb_number = Column(String(8))
    shipment_description_code = Column(String(1))
    total_pieces = Column(Integer)
    weight_unit = Column(String(1))
    gross_weight = Column(Numeric(10, 3))
    routing_list = Column(String(120))
    first_carrier = Column(String(2))
    onward_carrier = Column(String(2))
    flight_number = Column(String(5))
    flight_carrier = Column(String(2))
    shipper_city = Column(String(17))
    shipper_state = Column(String(9))
    shipper_country = Column(String(2))
    shipper_postcode = Column(String(9))
    shipper_contact = Column(String(25))
    consignee_city = Column(String(17))
    consignee_state = Column(String(9))
    consignee_country = Column(String(2))
    consignee_postcode = Column(String(9))
    consignee_contact = Column(String(25))
    agent_iata_code = Column(String(7))
    agent_account = Column(String(25))
    agent_name = Column(String(20))
    agent_city = Column(String(17))
    currency = Column(String(3))
    charge_code = Column(String(2))
    weight_charge_pp_cc = Column(String(2))
    other_charge_pp_cc = Column(String(2))
    declared_value_carriage = Column(String(12))
    declared_value_customs = Column(String(12))
    insurance_value = Column(String(12))
    rate_line_no = Column(String(2))
    rate = Column(Numeric(14, 2))
    dimensions = Column(String(65))
    slac = Column(String(4))
    hs_code = Column(String(18))
    country_of_origin = Column(String(2))
    other_charge_code = Column(String(10))
    entitlement = Column(String(10))
    amount = Column(Numeric(14, 2))
    prepaid_weight_charge = Column(Numeric(14, 2))
    prepaid_other_charge = Column(Numeric(14, 2))
    total_prepaid = Column(Numeric(14, 2))
    collect_charge = Column(Numeric(14, 2))
    shipper_certification = Column(String(20))
    issue_date = Column(Date)
    issue_place = Column(String(17))
    issued_by = Column(String(20))
    special_handling_code = Column(String(3))
    ssr = Column(String(65))
    osi = Column(String(65))
    oci = Column(String(65))

    created_at = Column(DateTime, server_default=func.now())
