from sqlalchemy import Column, Date, DateTime, Integer, Numeric, String, Text
from sqlalchemy.sql import func

from app.db.mysql import BaseDB1


class Fwb(BaseDB1):
    __tablename__ = "fwb"

    id = Column(Integer, primary_key=True, autoincrement=True)
    mawb = Column(String(20), nullable=False)

    shipper_name = Column(String(200))
    shipper_address = Column(Text)
    consignee_name = Column(String(200))
    consignee_address = Column(Text)

    flight_no = Column(String(20))
    flight_date = Column(DateTime)
    origin = Column(String(10))
    destination = Column(String(10))
    routing = Column(String(200))

    pieces = Column(Integer)
    weight = Column(Numeric(10, 2))
    volume = Column(Numeric(10, 2))
    goods_description = Column(Text)

    chargeable_weight = Column(Numeric(10, 2))
    rate_class = Column(String(10))
    total_charge = Column(Numeric(10, 2))
    raw_message = Column(Text)

    message_type = Column(String(10))
    message_version = Column(String(10))
    awb_prefix = Column(String(10))
    awb_number = Column(String(20))
    shipment_description_code = Column(String(5))
    total_pieces = Column(Integer)
    weight_unit = Column(String(5))
    gross_weight = Column(Numeric(10, 2))
    routing_list = Column(Text)
    first_carrier = Column(String(10))
    onward_carrier = Column(String(10))
    flight_number = Column(String(20))
    flight_carrier = Column(String(10))
    shipper_city = Column(String(100))
    shipper_state = Column(String(100))
    shipper_country = Column(String(10))
    shipper_postcode = Column(String(20))
    shipper_contact = Column(String(100))
    consignee_city = Column(String(100))
    consignee_state = Column(String(100))
    consignee_country = Column(String(10))
    consignee_postcode = Column(String(20))
    consignee_contact = Column(String(100))
    agent_iata_code = Column(String(20))
    agent_account = Column(String(50))
    agent_name = Column(String(200))
    agent_city = Column(String(100))
    currency = Column(String(10))
    charge_code = Column(String(10))
    weight_charge_pp_cc = Column(String(5))
    other_charge_pp_cc = Column(String(5))
    declared_value_carriage = Column(String(20))
    declared_value_customs = Column(String(20))
    insurance_value = Column(String(20))
    rate_line_no = Column(String(20))
    rate = Column(Numeric(12, 2))
    dimensions = Column(String(100))
    slac = Column(String(20))
    hs_code = Column(String(20))
    country_of_origin = Column(String(10))
    other_charge_code = Column(String(20))
    entitlement = Column(String(10))
    amount = Column(Numeric(12, 2))
    prepaid_weight_charge = Column(Numeric(12, 2))
    prepaid_other_charge = Column(Numeric(12, 2))
    total_prepaid = Column(Numeric(12, 2))
    collect_charge = Column(Numeric(12, 2))
    shipper_certification = Column(String(200))
    issue_date = Column(Date)
    issue_place = Column(String(100))
    issued_by = Column(String(100))
    special_handling_code = Column(String(20))
    ssr = Column(Text)
    osi = Column(Text)
    oci = Column(Text)

    created_at = Column(DateTime, server_default=func.now())
