[project]
authors = [
  {name = "Wisnu Baldas", email = "wisnubaldas@gmail.com"},
]
description = "TPSOnline Modernization Project Documentation using MkDocs Material"
name = "dokumentasi"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]

[tool.poetry.dependencies]
mkdocs = "^1.6.1"
mkdocs-awesome-pages-plugin = "^2.10.1"
mkdocs-git-revision-date-localized-plugin = "^1.4.7"
mkdocs-material = "^9.5.0"
mkdocs-minify-plugin = "^0.8.0"
pymdown-extensions = "^10.16.1"
watchdog = "^5.0.0"

[tool.poetry]
package-mode = false
packages = [{include = "docs"}]

[tool.poetry.scripts]
run-dev = "mkdocs_scripts:run_dev"
build = "mkdocs_scripts:build_site"
run-prod = "mkdocs_scripts:run_prod"
