AIRLINES = [
    {
        "iata_code": "GA",
        "icao_code": "GIA",
        "airline_name": "Garuda Indonesia",
        "short_name": "Garuda",
        "country": "Indonesia",
        "awb_prefix": "126",
        "home_base": "CGK",
        "cargo_handling_agent": "PT Gapura Angkasa",
        "sitatex_address": "GIACGXH",
        "edi_support": {"FFM": True, "FWB": True, "FHL": True},
        "special_handling_codes": ["PER", "DGR", "VAL", "ELI"],
        "allowed_uld_types": ["AKE", "PAG", "PMC"],
        "contact_person": "Cargo Support",
        "contact_email": "cargo@garuda-indonesia.com",
        "contact_phone": "+62-21-23519999",
    },
    {
        "iata_code": "ID",
        "icao_code": "BTK",
        "airline_name": "Batik Air",
        "short_name": "Batik",
        "country": "Indonesia",
        "awb_prefix": "990",
        "home_base": "CGK",
        "cargo_handling_agent": "Lion Parcel",
        "sitatex_address": "BTKCGXH",
        "edi_support": {"FFM": True, "FWB": True, "FHL": True},
        "special_handling_codes": ["DGR", "AVI"],
        "allowed_uld_types": ["AKE", "PMC"],
        "contact_person": "Cargo Division",
        "contact_email": "cargo@batikair.com",
        "contact_phone": "+62-21-63798000",
    },
    {
        "iata_code": "JT",
        "icao_code": "LNI",
        "airline_name": "Lion Air",
        "short_name": "Lion",
        "country": "Indonesia",
        "awb_prefix": "990",
        "home_base": "CGK",
        "cargo_handling_agent": "Lion Parcel",
        "sitatex_address": "LNICGXH",
        "edi_support": {"FFM": False, "FWB": True, "FHL": False},
        "special_handling_codes": ["PER"],
        "allowed_uld_types": ["AKE"],
        "contact_person": "Cargo Operation",
        "contact_email": "cargo@lionair.co.id",
        "contact_phone": "+62-21-63798000",
    },
    {
        "iata_code": "QZ",
        "icao_code": "AWQ",
        "airline_name": "AirAsia Indonesia",
        "short_name": "AirAsia ID",
        "country": "Indonesia",
        "awb_prefix": "807",
        "home_base": "CGK",
        "cargo_handling_agent": "PT JAS Airport Services",
        "sitatex_address": "AWQCGXH",
        "edi_support": {"FFM": True, "FWB": True, "FHL": True},
        "special_handling_codes": ["DGR", "VAL"],
        "allowed_uld_types": ["AKE", "PAG"],
        "contact_person": "AirAsia Cargo",
        "contact_email": "id_cargo@airasia.com",
        "contact_phone": "+62-21-29270999",
    },
    {
        "iata_code": "SJ",
        "icao_code": "SRI",
        "airline_name": "Sriwijaya Air",
        "short_name": "Sriwijaya",
        "country": "Indonesia",
        "awb_prefix": "977",
        "home_base": "CGK",
        "cargo_handling_agent": "Sriwijaya Cargo",
        "sitatex_address": "SRICGXH",
        "edi_support": {"FFM": True, "FWB": False, "FHL": False},
        "special_handling_codes": ["AVI"],
        "allowed_uld_types": ["AKE"],
        "contact_person": "Cargo Service",
        "contact_email": "cargo@sriwijayaair.co.id",
        "contact_phone": "+62-21-55919055",
    },
    # ----------------------------- FOREIGN AIRLINES -----------------------------
    {
        "iata_code": "SQ",
        "icao_code": "SIA",
        "airline_name": "Singapore Airlines",
        "short_name": "Singapore",
        "country": "Singapore",
        "awb_prefix": "618",
        "home_base": "SIN",
        "cargo_handling_agent": "SATS",
        "sitatex_address": "SIASINXH",
        "edi_support": {"FFM": True, "FWB": True, "FHL": True},
        "special_handling_codes": ["PER", "VAL", "DGR", "AVI"],
        "allowed_uld_types": ["AKE", "PMC", "PLA"],
        "contact_person": "SIA Cargo Ops",
        "contact_email": "cargo@singaporeair.com",
        "contact_phone": "+65 6541 2000",
    },
    {
        "iata_code": "MH",
        "icao_code": "MAS",
        "airline_name": "Malaysia Airlines",
        "short_name": "MAS",
        "country": "Malaysia",
        "awb_prefix": "232",
        "home_base": "KUL",
        "cargo_handling_agent": "MAB Kargo",
        "sitatex_address": "MASKULXH",
        "edi_support": {"FFM": True, "FWB": True, "FHL": True},
        "special_handling_codes": ["DGR", "PER"],
        "allowed_uld_types": ["AKE", "PAG"],
        "contact_person": "MASkargo",
        "contact_email": "support@maskargo.com",
        "contact_phone": "+60 3-8777 1234",
    },
    {
        "iata_code": "TG",
        "icao_code": "THA",
        "airline_name": "Thai Airways",
        "short_name": "Thai",
        "country": "Thailand",
        "awb_prefix": "217",
        "home_base": "BKK",
        "cargo_handling_agent": "Thai Cargo",
        "sitatex_address": "THABKKXH",
        "edi_support": {"FFM": True, "FWB": True, "FHL": True},
        "special_handling_codes": ["PER", "AVI"],
        "allowed_uld_types": ["AKE", "PMC"],
        "contact_person": "Thai Cargo",
        "contact_email": "cargo@thaiairways.com",
        "contact_phone": "+66 2 545 1000",
    },
    {
        "iata_code": "CX",
        "icao_code": "CPA",
        "airline_name": "Cathay Pacific",
        "short_name": "Cathay",
        "country": "Hong Kong",
        "awb_prefix": "160",
        "home_base": "HKG",
        "cargo_handling_agent": "Cathay Cargo",
        "sitatex_address": "CPAHKGXH",
        "edi_support": {"FFM": True, "FWB": True, "FHL": True},
        "special_handling_codes": ["DGR", "VAL", "ELI"],
        "allowed_uld_types": ["AKE", "PMC", "PAG"],
        "contact_person": "Cathay Cargo Ops",
        "contact_email": "cargo@cathaypacific.com",
        "contact_phone": "+852 2747 9000",
    },
    {
        "iata_code": "CI",
        "icao_code": "CAL",
        "airline_name": "China Airlines",
        "short_name": "China Airlines",
        "country": "Taiwan",
        "awb_prefix": "297",
        "home_base": "TPE",
        "cargo_handling_agent": "China Airlines Cargo",
        "sitatex_address": "CALTPEXH",
        "edi_support": {"FFM": True, "FWB": True, "FHL": True},
        "special_handling_codes": ["PER", "DGR"],
        "allowed_uld_types": ["PMC", "PLA"],
        "contact_person": "Cargo Support",
        "contact_email": "cargo@china-airlines.com",
        "contact_phone": "+886 2 412 9000",
    },
    # --------------------------- CONTINUE UNTIL 50 -----------------------------
]  # <= Akan saya lanjutkan hingga 50 item
