"""Seeder master data CEISA untuk referensi kondisi barang.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_KONDISI_BARANG_CODES = [{'reference_slug': 'referensi-kondisi-barang',
  'reference_name': 'Referensi Kondisi Barang',
  'code': '1',
  'name': 'Baru',
  'description': 'Baru',
  'is_active': True},
 {'reference_slug': 'referensi-kondisi-barang',
  'reference_name': 'Referensi Kondisi Barang',
  'code': '2',
  'name': 'Bukan Baru',
  'description': 'Bukan Baru',
  'is_active': True},
 {'reference_slug': 'referensi-kondisi-barang',
  'reference_name': 'Referensi Kondisi Barang',
  'code': '3',
  'name': 'Baik',
  'description': 'Baik',
  'is_active': True},
 {'reference_slug': 'referensi-kondisi-barang',
  'reference_name': 'Referensi Kondisi Barang',
  'code': '4',
  'name': 'Segar',
  'description': 'Segar',
  'is_active': True},
 {'reference_slug': 'referensi-kondisi-barang',
  'reference_name': 'Referensi Kondisi Barang',
  'code': '5',
  'name': 'Beku',
  'description': 'Beku',
  'is_active': True},
 {'reference_slug': 'referensi-kondisi-barang',
  'reference_name': 'Referensi Kondisi Barang',
  'code': '6',
  'name': 'Baik/Baru',
  'description': 'Baik/Baru',
  'is_active': True},
 {'reference_slug': 'referensi-kondisi-barang',
  'reference_name': 'Referensi Kondisi Barang',
  'code': '7',
  'name': 'Baik/Beku',
  'description': 'Baik/Beku',
  'is_active': True},
 {'reference_slug': 'referensi-kondisi-barang',
  'reference_name': 'Referensi Kondisi Barang',
  'code': '8',
  'name': 'Baik/Bekas',
  'description': 'Baik/Bekas',
  'is_active': True}]
