"""Seeder master data CEISA untuk referensi tipe kontainer.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_TIPE_KONTAINER_CODES = [{'reference_slug': 'referensi-tipe-kontainer',
  'reference_name': 'Referensi Tipe Kontainer',
  'code': '1',
  'name': 'General / Dry Cargo',
  'description': 'General / Dry Cargo',
  'is_active': True},
 {'reference_slug': 'referensi-tipe-kontainer',
  'reference_name': 'Referensi Tipe Kontainer',
  'code': '2',
  'name': 'Tunne Type',
  'description': 'Tunne Type',
  'is_active': True},
 {'reference_slug': 'referensi-tipe-kontainer',
  'reference_name': 'Referensi Tipe Kontainer',
  'code': '3',
  'name': 'Open Top Steel',
  'description': 'Open Top Steel',
  'is_active': True},
 {'reference_slug': 'referensi-tipe-kontainer',
  'reference_name': 'Referensi Tipe Kontainer',
  'code': '4',
  'name': 'Flat Rack',
  'description': 'Flat Rack',
  'is_active': True},
 {'reference_slug': 'referensi-tipe-kontainer',
  'reference_name': 'Referensi Tipe Kontainer',
  'code': '5',
  'name': 'Reefer/Refregete',
  'description': 'Reefer/Refregete',
  'is_active': True},
 {'reference_slug': 'referensi-tipe-kontainer',
  'reference_name': 'Referensi Tipe Kontainer',
  'code': '6',
  'name': 'Barge Container',
  'description': 'Barge Container',
  'is_active': True},
 {'reference_slug': 'referensi-tipe-kontainer',
  'reference_name': 'Referensi Tipe Kontainer',
  'code': '7',
  'name': 'Bulk Container',
  'description': 'Bulk Container',
  'is_active': True},
 {'reference_slug': 'referensi-tipe-kontainer',
  'reference_name': 'Referensi Tipe Kontainer',
  'code': '8',
  'name': 'Isotank',
  'description': 'Isotank',
  'is_active': True},
 {'reference_slug': 'referensi-tipe-kontainer',
  'reference_name': 'Referensi Tipe Kontainer',
  'code': '99',
  'name': 'Lain-lain',
  'description': 'Lain-lain',
  'is_active': True}]
