"""Seeder master data CEISA untuk referensi kategori ekspor.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_KATEGORI_EKSPOR_CODES = [{'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '61',
  'name': 'BKC Yang Belum Dilunasi Cukainya',
  'description': 'BKC Yang Belum Dilunasi Cukainya',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '51',
  'name': 'PLB',
  'description': 'PLB',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '46',
  'name': 'TPB Dari Kawasan Daur Ulang Berikat',
  'description': 'TPB Dari Kawasan Daur Ulang Berikat',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '45',
  'name': 'TPB Dari Tempat Lelang Berikat',
  'description': 'TPB Dari Tempat Lelang Berikat',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '44',
  'name': 'TPB Dari Toko Bebas Bea',
  'description': 'TPB Dari Toko Bebas Bea',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '43',
  'name': 'TPB Dari Tempat Pameran Berikat',
  'description': 'TPB Dari Tempat Pameran Berikat',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '42',
  'name': 'TPB Dari Gudang Berikat',
  'description': 'TPB Dari Gudang Berikat',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '41',
  'name': 'TPB Dari Kawasan Berikat',
  'description': 'TPB Dari Kawasan Berikat',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '38',
  'name': 'Khusus Brg Keperluan Penelitian',
  'description': 'Khusus Brg Keperluan Penelitian',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '37',
  'name': 'Khusus Brg Contoh',
  'description': 'Khusus Brg Contoh',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '36',
  'name': 'Khusus Brg Cinderamata',
  'description': 'Khusus Brg Cinderamata',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '35',
  'name': 'Khusus Brg Keperluan Ibadah Utk Umum Sosial Pendidikan Budaya/Olahraga dan Bencana Alam',
  'description': 'Khusus Brg Keperluan Ibadah Utk Umum Sosial Pendidikan Budaya/Olahraga dan Bencana Alam',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '34',
  'name': 'Khusus Brg Pindahan',
  'description': 'Khusus Brg Pindahan',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '33',
  'name': 'Khusus Brg Kiriman',
  'description': 'Khusus Brg Kiriman',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '32',
  'name': 'Khusus Brg Perwakilan Badan Internasional',
  'description': 'Khusus Brg Perwakilan Badan Internasional',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '31',
  'name': 'Khusus Brg Perwakilan Negara Asing',
  'description': 'Khusus Brg Perwakilan Negara Asing',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '23',
  'name': 'KITE dengan pembebasan dan pengembalian',
  'description': 'KITE dengan pembebasan dan pengembalian',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '22',
  'name': 'Yg pd saat imp mndpt fas pengembalian BM(NIPER dgn pengembalian)',
  'description': 'Yg pd saat imp mndpt fas pengembalian BM(NIPER dgn pengembalian)',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '21',
  'name': 'Yg pd saat imp mndpt fas pembebasan BM(NIPER dgn pembebasan)',
  'description': 'Yg pd saat imp mndpt fas pembebasan BM(NIPER dgn pembebasan)',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '10',
  'name': 'Umum',
  'description': 'Umum',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '24',
  'name': 'Ekspor KITE IKM',
  'description': 'Ekspor KITE IKM',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '22',
  'name': 'KITE dengan pengembalian',
  'description': 'KITE dengan pengembalian',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '21',
  'name': 'KITE dengan Pembebasan',
  'description': 'KITE dengan Pembebasan',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '12',
  'name': 'Ekspor Badan Usaha',
  'description': 'Ekspor Badan Usaha',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '11',
  'name': 'Ekspor Perorangan',
  'description': 'Ekspor Perorangan',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '4',
  'name': 'Ekspor Dari - Asal KB',
  'description': 'Ekspor Dari - Asal KB',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '3',
  'name': 'Ekspor Melalui - Asal KB',
  'description': 'Ekspor Melalui - Asal KB',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '2',
  'name': 'Ekspor Dari - Umum',
  'description': 'Ekspor Dari - Umum',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-ekspor',
  'reference_name': 'Referensi Kategori Ekspor',
  'code': '1',
  'name': 'Ekspor Melalui - Umum',
  'description': 'Ekspor Melalui - Umum',
  'is_active': True}]
