"""Seeder master data CEISA untuk referensi respon.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_RESPON_CODES = [{'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*',
  'name': 'PENERBITAN NOMOR DAFTAR',
  'description': 'PENERBITAN NOMOR DAFTAR',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*00',
  'name': 'RESPON PENERIMAAN',
  'description': 'RESPON PENERIMAAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*01',
  'name': 'NOTA PEMBERITAHUAN PENOLAKAN (REJECT)',
  'description': 'NOTA PEMBERITAHUAN PENOLAKAN (REJECT)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*02',
  'name': 'PEMBERITAHUAN PENERIMAAN PIB PENYELESAIAN (P4)',
  'description': 'PEMBERITAHUAN PENERIMAAN PIB PENYELESAIAN (P4)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*03',
  'name': 'SURAT PERSETUJUAN PENGELUARAN BARANG (SPPB)',
  'description': 'SURAT PERSETUJUAN PENGELUARAN BARANG (SPPB)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*03',
  'name': 'SURAT PERINTAH PEMERIKSAAN FISIK',
  'description': 'SURAT PERINTAH PEMERIKSAAN FISIK',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*03',
  'name': 'NOTA PERSETUJUAN PEMASUKAN BARANG EKSPOR (NPPBE)',
  'description': 'NOTA PERSETUJUAN PEMASUKAN BARANG EKSPOR (NPPBE)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*04',
  'name': 'FORMULIR SURAT PERSETUJUAN PENYELESAIAN DOKUMEN (SPPD)',
  'description': 'FORMULIR SURAT PERSETUJUAN PENYELESAIAN DOKUMEN (SPPD)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*04',
  'name': 'SURAT PEMBERITAHUAN JALUR KUNING (SPJK)',
  'description': 'SURAT PEMBERITAHUAN JALUR KUNING (SPJK)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*04',
  'name': 'LAPORAN HASIL PEMERIKSAAN',
  'description': 'LAPORAN HASIL PEMERIKSAAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*04',
  'name': 'SURAT PEMBERITAHUAN PEMERIKSAAN FISIK (SPPF)',
  'description': 'SURAT PEMBERITAHUAN PEMERIKSAAN FISIK (SPPF)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*04',
  'name': '[KHUSUS 33] NOTA PELAYANAN EKSPOR (NPE)',
  'description': '[KHUSUS 33] NOTA PELAYANAN EKSPOR (NPE)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*05',
  'name': 'FORMULIR SURAT PERSETUJUAN PERUBAHAN BC 1.6',
  'description': 'FORMULIR SURAT PERSETUJUAN PERUBAHAN BC 1.6',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*05',
  'name': 'SURAT PEMBERITAHUAN JALUR MERAH (SPJM)',
  'description': 'SURAT PEMBERITAHUAN JALUR MERAH (SPJM)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*05',
  'name': 'SURAT PERSETUJUAN PENYELESAIAN DOKUMEN (SPPD)',
  'description': 'SURAT PERSETUJUAN PENYELESAIAN DOKUMEN (SPPD)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*05',
  'name': 'BERITA ACARA HASIL PEMERIKSAAN',
  'description': 'BERITA ACARA HASIL PEMERIKSAAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*05',
  'name': 'INSTRUKSI PEMERIKSAAN',
  'description': 'INSTRUKSI PEMERIKSAAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*05',
  'name': 'PEMBERITAHUAN KESIAPAN BARANG (PKB)',
  'description': 'PEMBERITAHUAN KESIAPAN BARANG (PKB)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*05',
  'name': 'SURAT PEMERIKSAAN FISIK',
  'description': 'SURAT PEMERIKSAAN FISIK',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*06',
  'name': 'FORMULIR SURAT PERSETUJUAN PEMBATALAN BC 1.6',
  'description': 'FORMULIR SURAT PERSETUJUAN PEMBATALAN BC 1.6',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*06',
  'name': 'SURAT PERINTAH PEMERIKSAAN FISIK (SPPF)',
  'description': 'SURAT PERINTAH PEMERIKSAAN FISIK (SPPF)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*06',
  'name': 'SURAT PERSETUJUAN / PENOLAKAN PERUBAHAN',
  'description': 'SURAT PERSETUJUAN / PENOLAKAN PERUBAHAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*06',
  'name': 'INSTRUKSI PEMERIKSAAN FISIK MELALUI PEMINDAI',
  'description': 'INSTRUKSI PEMERIKSAAN FISIK MELALUI PEMINDAI',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*06',
  'name': 'PEMBERITAHUAN PEMERIKSAAN BARANG (PPB)',
  'description': 'PEMBERITAHUAN PEMERIKSAAN BARANG (PPB)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*06',
  'name': 'INSTRUKSI PEMERIKSAAN',
  'description': 'INSTRUKSI PEMERIKSAAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*07',
  'name': 'SURAT PEMBERITAHUAN PENGAWASAN PEMBONGKARAN DAN PENIMBUNAN (SP4) PLB',
  'description': 'SURAT PEMBERITAHUAN PENGAWASAN PEMBONGKARAN DAN PENIMBUNAN (SP4) PLB',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*07',
  'name': 'LAPORAN HASIL PEMERIKSAAN',
  'description': 'LAPORAN HASIL PEMERIKSAAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*07',
  'name': 'SURAT PERSETUJUAN PEMBATALAN',
  'description': 'SURAT PERSETUJUAN PEMBATALAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*07',
  'name': 'SURAT PERSETUJUAN / PENOLAKAN PEMBATALAN',
  'description': 'SURAT PERSETUJUAN / PENOLAKAN PEMBATALAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*07',
  'name': 'NOTA PEMBETULAN',
  'description': 'NOTA PEMBETULAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*08',
  'name': 'TANDA TERIMA PENYERAHAN KELENGKAPAN DOKUMEN',
  'description': 'TANDA TERIMA PENYERAHAN KELENGKAPAN DOKUMEN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*08',
  'name': 'BERITA ACARA HASIL PEMERIKSAAN',
  'description': 'BERITA ACARA HASIL PEMERIKSAAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*08',
  'name': 'SURAT PERINTAH PEMERIKSAAN FISIK (SPPF)',
  'description': 'SURAT PERINTAH PEMERIKSAAN FISIK (SPPF)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*08',
  'name': 'SURAT PERSETUJUAN PENGELUARAN BARANG (SPPB)',
  'description': 'SURAT PERSETUJUAN PENGELUARAN BARANG (SPPB)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*08',
  'name': 'SURAT PERSETUJUAN PENYELESAIAN DOKUMEN (SPPD)',
  'description': 'SURAT PERSETUJUAN PENYELESAIAN DOKUMEN (SPPD)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*08',
  'name': 'LAPORAN HASIL ANALISIS TAMPILAN (LHAT)',
  'description': 'LAPORAN HASIL ANALISIS TAMPILAN (LHAT)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*08',
  'name': 'PEMBERITAHUAN PENGGABUNGAN DAN PEMECAHAN BARANG EKSPOR DAN TRANSHIPMENT (P3BET)',
  'description': 'PEMBERITAHUAN PENGGABUNGAN DAN PEMECAHAN BARANG EKSPOR DAN TRANSHIPMENT (P3BET)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*09',
  'name': 'TANDA TERIMA PENYERAHAN KELENGKAPAN DOKUMEN',
  'description': 'TANDA TERIMA PENYERAHAN KELENGKAPAN DOKUMEN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*09',
  'name': 'BERITA ACARA HASIL PEMERIKSAAN / LAPORAN HASIL PEMERIKSAAN FISIK (LHP)',
  'description': 'BERITA ACARA HASIL PEMERIKSAAN / LAPORAN HASIL PEMERIKSAAN FISIK (LHP)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*09',
  'name': 'SURAT PERSETUJUAN PENYELESAIAN DOKUMEN(SPPD)',
  'description': 'SURAT PERSETUJUAN PENYELESAIAN DOKUMEN(SPPD)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*09',
  'name': 'SURAT PERSETUJUAN PEMASUKAN KEMBALI BARANG (SPPKB)',
  'description': 'SURAT PERSETUJUAN PEMASUKAN KEMBALI BARANG (SPPKB)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*09',
  'name': 'NOTA PERSETUJUAN P3BET',
  'description': 'NOTA PERSETUJUAN P3BET',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*10',
  'name': 'SURAT PERSETUJUAN / PENOLAKAN PERUBAHAN',
  'description': 'SURAT PERSETUJUAN / PENOLAKAN PERUBAHAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*10',
  'name': 'BERITA ACARA PEMERIKSAAN FISIK BARANG (BAPFB)',
  'description': 'BERITA ACARA PEMERIKSAAN FISIK BARANG (BAPFB)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*10',
  'name': 'TANDA TERIMA PENYERAHAN KELENGKAPAN DOKUMEN',
  'description': 'TANDA TERIMA PENYERAHAN KELENGKAPAN DOKUMEN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*10',
  'name': 'RESPON REJECT PEB',
  'description': 'RESPON REJECT PEB',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*10',
  'name': 'PEMBERITAHUAN PENGAWASAN STUFFING (PPS)',
  'description': 'PEMBERITAHUAN PENGAWASAN STUFFING (PPS)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*11',
  'name': 'SURAT PERSETUJUAN PELAYANAN BC 1.6 OLEH PENYELENGGARA POS',
  'description': 'SURAT PERSETUJUAN PELAYANAN BC 1.6 OLEH PENYELENGGARA POS',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*11',
  'name': 'SURAT PERSETUJUAN / PENOLAKAN PEMBATALAN',
  'description': 'SURAT PERSETUJUAN / PENOLAKAN PEMBATALAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*11',
  'name': 'NOTA PEMBETULAN BC 2.3',
  'description': 'NOTA PEMBETULAN BC 2.3',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*11',
  'name': 'RESPON ERROR AUTENTIFIKASI BC261',
  'description': 'RESPON ERROR AUTENTIFIKASI BC261',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*11',
  'name': 'PEMBERITAHUAN PEMBETULAN BC 3.3 (PP-BC 3.3)',
  'description': 'PEMBERITAHUAN PEMBETULAN BC 3.3 (PP-BC 3.3)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*12',
  'name': 'LAPORAN HASIL PEMERIKSAAN',
  'description': 'LAPORAN HASIL PEMERIKSAAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*12',
  'name': 'RESPON ERROR AUTENTIFIKASI BC262',
  'description': 'RESPON ERROR AUTENTIFIKASI BC262',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*12',
  'name': 'SURAT PERSETUJUAN/PENOLAKAN PEMBATALAN BC 28',
  'description': 'SURAT PERSETUJUAN/PENOLAKAN PEMBATALAN BC 28',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*12',
  'name': 'RESPON REJECT PKBE',
  'description': 'RESPON REJECT PKBE',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*12',
  'name': 'PEMBERITAHUAN PEMBETULAN P3BET (PP-P3BET)',
  'description': 'PEMBERITAHUAN PEMBETULAN P3BET (PP-P3BET)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*13',
  'name': 'SURAT PENETAPAN BARANG LARANGAN/PEMBATASAN (SPBL)',
  'description': 'SURAT PENETAPAN BARANG LARANGAN/PEMBATASAN (SPBL)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*13',
  'name': 'SURAT PERSETUJUAN PENGELUARAN BARANG EKSPOR DAN TRANSHIPMENT (SPPBET)',
  'description': 'SURAT PERSETUJUAN PENGELUARAN BARANG EKSPOR DAN TRANSHIPMENT (SPPBET)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*14',
  'name': 'SURAT PENETAPAN PENYESUAIAN JAMINAN (SPPJ)',
  'description': 'SURAT PENETAPAN PENYESUAIAN JAMINAN (SPPJ)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*14',
  'name': 'RESPON PPB',
  'description': 'RESPON PPB',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*14',
  'name': 'SURAT PERSETUJUAN PEMASUKAN ATAU PENGELUARAN BARANG KE ATAU DARI PLB DAN/ATAU PEMUATAN BARANG KE SARANA '
          'PENGANGKUT SEBELUM PENYAMPAIAN PEMBERITAHUAN PABEAN',
  'description': 'SURAT PERSETUJUAN PEMASUKAN ATAU PENGELUARAN BARANG KE ATAU DARI PLB DAN/ATAU PEMUATAN BARANG KE '
                 'SARANA PENGANGKUT SEBELUM PENYAMPAIAN PEMBERITAHUAN PABEAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*15',
  'name': 'NOTA PERMINTAAN DATA DAN/ATAU DOKUMEN (NPD)',
  'description': 'NOTA PERMINTAAN DATA DAN/ATAU DOKUMEN (NPD)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*15',
  'name': 'RESPON NOTA PELAYANAN EKSPOR',
  'description': 'RESPON NOTA PELAYANAN EKSPOR',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*15',
  'name': 'SURAT PERMOHONAN PEMASUKAN ATAU PENGELUARAN BARANG KE ATAU DARI PLB DAN/ATAU PEMUATAN BARANG KE SARANA '
          'PENGANGKUT SEBELUM PENYAMPAIAN PEMBERITAHUAN PABEAN',
  'description': 'SURAT PERMOHONAN PEMASUKAN ATAU PENGELUARAN BARANG KE ATAU DARI PLB DAN/ATAU PEMUATAN BARANG KE '
                 'SARANA PENGANGKUT SEBELUM PENYAMPAIAN PEMBERITAHUAN PABEAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*16',
  'name': 'NOTA PERMINTAAN JAMINAN (NPJ)',
  'description': 'NOTA PERMINTAAN JAMINAN (NPJ)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*16',
  'name': 'RESPON NOTA PELAYANAN EKSPOR PEB MERAH',
  'description': 'RESPON NOTA PELAYANAN EKSPOR PEB MERAH',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*16',
  'name': 'INSTRUKSI PEMERIKSAAN (IP)',
  'description': 'INSTRUKSI PEMERIKSAAN (IP)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*17',
  'name': 'SURAT PERSETUJUAN PENYELESAIAN DOKUMEN (SPPD)',
  'description': 'SURAT PERSETUJUAN PENYELESAIAN DOKUMEN (SPPD)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*17',
  'name': 'RESPON SPPBK',
  'description': 'RESPON SPPBK',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*17',
  'name': 'INSTRUKSI PEMERIKSAAN MELALUI PEMINDAI',
  'description': 'INSTRUKSI PEMERIKSAAN MELALUI PEMINDAI',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*18',
  'name': 'LAPORAN HASIL PEMERIKSAAN (LHP)',
  'description': 'LAPORAN HASIL PEMERIKSAAN (LHP)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*19',
  'name': 'LAPORAN HASIL ANALISIS TAMPILAN (LHAT)',
  'description': 'LAPORAN HASIL ANALISIS TAMPILAN (LHAT)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*20',
  'name': 'KONFIRMASI BAYAR (BILLING)',
  'description': 'KONFIRMASI BAYAR (BILLING)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*20',
  'name': 'RESPON PROSES PEB',
  'description': 'RESPON PROSES PEB',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*20',
  'name': 'BERITA ACARA PEMERIKSAAN FISIK BARANG',
  'description': 'BERITA ACARA PEMERIKSAAN FISIK BARANG',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*21',
  'name': 'INFORMASI NILAI PABEAN',
  'description': 'INFORMASI NILAI PABEAN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*21',
  'name': 'TANDA TERIMA PENYERAHAN KELENGKAPAN DOKUMEN',
  'description': 'TANDA TERIMA PENYERAHAN KELENGKAPAN DOKUMEN',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*22',
  'name': 'UNDANGAN KONSULTASI',
  'description': 'UNDANGAN KONSULTASI',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*22',
  'name': 'RESPON PROSES PKBE',
  'description': 'RESPON PROSES PKBE',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*22',
  'name': 'PERMOHONAN PENGELUARAN BARANG EKSPOR DAN TRANSHIPMENT',
  'description': 'PERMOHONAN PENGELUARAN BARANG EKSPOR DAN TRANSHIPMENT',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*23',
  'name': 'KIRIM BARANG LABORATORIUM',
  'description': 'KIRIM BARANG LABORATORIUM',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*24',
  'name': 'KONFIRMASI BARANG',
  'description': 'KONFIRMASI BARANG',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*26',
  'name': 'SURAT PENETAPAN TARIF DAN/ATAU NILAI PABEAN (SPTNP)',
  'description': 'SURAT PENETAPAN TARIF DAN/ATAU NILAI PABEAN (SPTNP)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*27',
  'name': 'KONFIRMASI BAYAR (SPTNP)',
  'description': 'KONFIRMASI BAYAR (SPTNP)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*28',
  'name': 'KONFIRMASI BAYAR (BILLING SPTNP/SPPBK)',
  'description': 'KONFIRMASI BAYAR (BILLING SPTNP/SPPBK)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*30',
  'name': 'RESPON REJECT PERBAIKAN PEB',
  'description': 'RESPON REJECT PERBAIKAN PEB',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*30',
  'name': 'SURAT PENETAPAN PERHITUNGAN BEA KELUAR (SPPBK)',
  'description': 'SURAT PENETAPAN PERHITUNGAN BEA KELUAR (SPPBK)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*50',
  'name': 'LPPT',
  'description': 'LPPT',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*66',
  'name': 'INSTRUKSI PEMERIKSAAN (IP)',
  'description': 'INSTRUKSI PEMERIKSAAN (IP)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*80',
  'name': 'RESPON RUSH HANDLING (P4)',
  'description': 'RESPON RUSH HANDLING (P4)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*80',
  'name': 'SURAT PERSETUJUAN / PENOLAKAN PERUBAHAN BC33',
  'description': 'SURAT PERSETUJUAN / PENOLAKAN PERUBAHAN BC33',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*80',
  'name': 'SURAT PERSETUJUAN / PENOLAKAN PERUBAHAN P3BET',
  'description': 'SURAT PERSETUJUAN / PENOLAKAN PERUBAHAN P3BET',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*90',
  'name': 'RESPON UMUM',
  'description': 'RESPON UMUM',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*91',
  'name': 'RESPON UMUM NPPD',
  'description': 'RESPON UMUM NPPD',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*92',
  'name': 'RESPON REKON MANIFES',
  'description': 'RESPON REKON MANIFES',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*99',
  'name': 'RESPON ERROR AUTENTIFIKASI (ERROR)',
  'description': 'RESPON ERROR AUTENTIFIKASI (ERROR)',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*360',
  'name': 'RESPON LHPRE',
  'description': 'RESPON LHPRE',
  'is_active': True},
 {'reference_slug': 'referensi-respon',
  'reference_name': 'Referensi Respon',
  'code': '*966',
  'name': 'PERSETUJUAN PERUBAHAN',
  'description': 'PERSETUJUAN PERUBAHAN',
  'is_active': True}]
