"""Seeder master data CEISA untuk referensi kategori barang.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_KATEGORI_BARANG_CODES = [{'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '01',
  'name': 'BARANG UNTUK DITIMBUN',
  'description': 'BARANG UNTUK DITIMBUN',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '02',
  'name': 'BARANG UNTUK KEPERLUAN PENGUSAHAAN',
  'description': 'BARANG UNTUK KEPERLUAN PENGUSAHAAN',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '11',
  'name': 'UNTUK BAHAN BAKU/BAHAN PENOLONG',
  'description': 'UNTUK BAHAN BAKU/BAHAN PENOLONG',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '12',
  'name': 'UNTUK PENGEMAS/ALAT BANTU PENGEMAS',
  'description': 'UNTUK PENGEMAS/ALAT BANTU PENGEMAS',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '13',
  'name': 'UNTUK PERALATAN UNTUK PEMBANGUNAN, PERLUASAN, ATAU KONSTRUKSI KB',
  'description': 'UNTUK PERALATAN UNTUK PEMBANGUNAN, PERLUASAN, ATAU KONSTRUKSI KB',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '14',
  'name': 'UNTUK BARANG MODAL DAN/ATAU SPAREPARTS BARANG MODAL',
  'description': 'UNTUK BARANG MODAL DAN/ATAU SPAREPARTS BARANG MODAL',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '15',
  'name': 'UNTUK BARANG CONTOH',
  'description': 'UNTUK BARANG CONTOH',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '16',
  'name': 'UNTUK BARANG JADI GUNA DIGABUNG DENGAN HASIL PRODUKSI',
  'description': 'UNTUK BARANG JADI GUNA DIGABUNG DENGAN HASIL PRODUKSI',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '17',
  'name': 'UNTUK BARANG REIMPOR',
  'description': 'UNTUK BARANG REIMPOR',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '18',
  'name': 'UNTUK PERALATAN PERKANTORAN',
  'description': 'UNTUK PERALATAN PERKANTORAN',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '19',
  'name': 'BARANG UNTUK KEPERLUAN PENANGANAN COVID19',
  'description': 'BARANG UNTUK KEPERLUAN PENANGANAN COVID19',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '21',
  'name': 'UNTUK BARANG YANG DITIMBUN DI GB',
  'description': 'UNTUK BARANG YANG DITIMBUN DI GB',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '22',
  'name': 'UNTUK BARANG REIMPOR',
  'description': 'UNTUK BARANG REIMPOR',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '31',
  'name': 'UNTUK BARANG UNTUK DIPAMERKAN',
  'description': 'UNTUK BARANG UNTUK DIPAMERKAN',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '32',
  'name': 'UNTUK BARANG UNTUK MENDUKUNG KEPERLUAN PAMERAN',
  'description': 'UNTUK BARANG UNTUK MENDUKUNG KEPERLUAN PAMERAN',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '33',
  'name': 'UNTUK BARANG REIMPOR',
  'description': 'UNTUK BARANG REIMPOR',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '41',
  'name': 'UNTUK BARANG YANG DITIMBUN DI TBB',
  'description': 'UNTUK BARANG YANG DITIMBUN DI TBB',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '42',
  'name': 'UNTUK BARANG REIMPOR',
  'description': 'UNTUK BARANG REIMPOR',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '51',
  'name': 'UNTUK BARANG LELANG',
  'description': 'UNTUK BARANG LELANG',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '52',
  'name': 'UNTUK SPAREPARTS',
  'description': 'UNTUK SPAREPARTS',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '53',
  'name': 'UNTUK BARANG REIMPOR',
  'description': 'UNTUK BARANG REIMPOR',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '61',
  'name': 'UNTUK BARANG YANG DITIMBUN DI KDUB',
  'description': 'UNTUK BARANG YANG DITIMBUN DI KDUB',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '62',
  'name': 'UNTUK BARANG REIMPOR',
  'description': 'UNTUK BARANG REIMPOR',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '1',
  'name': 'HASIL PRODUKSI',
  'description': 'HASIL PRODUKSI',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '2',
  'name': 'BAHAN BAKU',
  'description': 'BAHAN BAKU',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '3',
  'name': 'BARANG MODAL',
  'description': 'BARANG MODAL',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '4',
  'name': 'PERALATAN KANTOR',
  'description': 'PERALATAN KANTOR',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '5',
  'name': 'SISA DARI PROSES PRODUKSI/LIMBAH (WASTE/SCRAP) DAN/ATAU SISA ATAU BEKAS PENGEMAS',
  'description': 'SISA DARI PROSES PRODUKSI/LIMBAH (WASTE/SCRAP) DAN/ATAU SISA ATAU BEKAS PENGEMAS',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '6',
  'name': 'BARANG YANG DITIMBUN UNTUK DIJUAL',
  'description': 'BARANG YANG DITIMBUN UNTUK DIJUAL',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '7',
  'name': 'BARANG YANG DIPAMERKAN UNTUK DIJUAL',
  'description': 'BARANG YANG DIPAMERKAN UNTUK DIJUAL',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '8',
  'name': 'BARANG LAINNYA',
  'description': 'BARANG LAINNYA',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '9',
  'name': 'BARANG UNTUK KEPERLUAN PENANGANAN COVID19',
  'description': 'BARANG UNTUK KEPERLUAN PENANGANAN COVID19',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-barang',
  'reference_name': 'Referensi Kategori Barang',
  'code': '10',
  'name': 'BARANG CONTOH',
  'description': 'BARANG CONTOH',
  'is_active': True}]
