"""Seeder master data CEISA untuk referensi kantor.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_KANTOR_CODES = [{'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '000000',
  'name': 'DJBC',
  'description': 'DJBC',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '001000',
  'name': 'SEKRETARIAT',
  'description': 'SEKRETARIAT',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '001100',
  'name': 'TP BIDANG I',
  'description': 'TP BIDANG I',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '001200',
  'name': 'TP BIDANG II',
  'description': 'TP BIDANG II',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '001300',
  'name': 'TP BIDANG III',
  'description': 'TP BIDANG III',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '001400',
  'name': 'DIREKTORAT KI',
  'description': 'DIREKTORAT KI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '001500',
  'name': 'DIREKTORAT KBP',
  'description': 'DIREKTORAT KBP',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '002000',
  'name': 'DIREKTORAT TEKNIS',
  'description': 'DIREKTORAT TEKNIS',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '003000',
  'name': 'DIREKTORAT FASILITAS',
  'description': 'DIREKTORAT FASILITAS',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '004000',
  'name': 'DIREKTORAT CUKAI',
  'description': 'DIREKTORAT CUKAI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '005000',
  'name': 'DIREKTORAT P2',
  'description': 'DIREKTORAT P2',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '006000',
  'name': 'DIREKTORAT AUDIT',
  'description': 'DIREKTORAT AUDIT',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '007000',
  'name': 'DIREKTORAT KIAL',
  'description': 'DIREKTORAT KIAL',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '008000',
  'name': 'DIREKTORAT PPS',
  'description': 'DIREKTORAT PPS',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '009000',
  'name': 'DIREKTORAT IKC',
  'description': 'DIREKTORAT IKC',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '010000',
  'name': 'KANWIL SUMUT',
  'description': 'KANWIL SUMUT',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '010100',
  'name': 'KPPBC KUALANAMU',
  'description': 'KPPBC KUALANAMU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '010700',
  'name': 'KPPBC ELAWAN',
  'description': 'KPPBC ELAWAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '010800',
  'name': 'KPPBC MEDAN',
  'description': 'KPPBC MEDAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '010900',
  'name': 'KPPBC PANGKALAN SUSU',
  'description': 'KPPBC PANGKALAN SUSU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '011000',
  'name': 'KPPBC PEMATANGSIANTAR',
  'description': 'KPPBC PEMATANGSIANTAR',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '011100',
  'name': 'KPPBC TELUK NIBUNG',
  'description': 'KPPBC TELUK NIBUNG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '011200',
  'name': 'KPPBC KUALA TANJUNG',
  'description': 'KPPBC KUALA TANJUNG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '011300',
  'name': 'KPPBC SIBOLGA',
  'description': 'KPPBC SIBOLGA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '011500',
  'name': 'KPPBC TELUK BAYUR',
  'description': 'KPPBC TELUK BAYUR',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '011600',
  'name': 'BLBC KELAS II MEDAN',
  'description': 'BLBC KELAS II MEDAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '020000',
  'name': 'KANWIL KHUSUS KEPRI',
  'description': 'KANWIL KHUSUS KEPRI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '020100',
  'name': 'KPPBC TBK',
  'description': 'KPPBC TBK',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '020200',
  'name': 'KPPBC SAMBU BELAKANG PADANG',
  'description': 'KPPBC SAMBU BELAKANG PADANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '020300',
  'name': 'KPPBC SELAT PANJANG',
  'description': 'KPPBC SELAT PANJANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '020400',
  'name': 'KPU BATAM',
  'description': 'KPU BATAM',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '020500',
  'name': 'KPPBC TANJUNG PINANG',
  'description': 'KPPBC TANJUNG PINANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '020800',
  'name': 'KPPBC DABO SINGKEP',
  'description': 'KPPBC DABO SINGKEP',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '020900',
  'name': 'KPPBC DUMAI',
  'description': 'KPPBC DUMAI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '021000',
  'name': 'KPPBC BAGAN SIAPIAPI',
  'description': 'KPPBC BAGAN SIAPIAPI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '021100',
  'name': 'KPPBC BENGKALIS',
  'description': 'KPPBC BENGKALIS',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '021200',
  'name': 'KPPBC PEKANBARU',
  'description': 'KPPBC PEKANBARU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '021300',
  'name': 'KPPBC SIAK SRI INDRAPURA',
  'description': 'KPPBC SIAK SRI INDRAPURA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '021500',
  'name': 'KPPBC TEMBILAHAN',
  'description': 'KPPBC TEMBILAHAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '021700',
  'name': 'KPPBC TAREMPA',
  'description': 'KPPBC TAREMPA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '021800',
  'name': 'PANGSAROP BATAM',
  'description': 'PANGSAROP BATAM',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '021900',
  'name': 'PANGSAROP TANJUNG BALAI KARIMUN',
  'description': 'PANGSAROP TANJUNG BALAI KARIMUN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '030000',
  'name': 'KANWIL SUMBAGTIM',
  'description': 'KANWIL SUMBAGTIM',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '030100',
  'name': 'KPPBC PALEMBANG',
  'description': 'KPPBC PALEMBANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '030200',
  'name': 'KPPBC BENGKULU',
  'description': 'KPPBC BENGKULU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '030300',
  'name': 'KPPBC PANGKALPINANG',
  'description': 'KPPBC PANGKALPINANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '030500',
  'name': 'KPPBC TANJUNGPANDAN',
  'description': 'KPPBC TANJUNGPANDAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '030600',
  'name': 'KPPBC JAMBI',
  'description': 'KPPBC JAMBI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '030700',
  'name': 'KPPBC BANDAR LAMPUNG',
  'description': 'KPPBC BANDAR LAMPUNG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '040000',
  'name': 'KANWIL JAKARTA',
  'description': 'KANWIL JAKARTA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '040300',
  'name': 'KPU TANJUNG PRIOK',
  'description': 'KPU TANJUNG PRIOK',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '040400',
  'name': 'KPPBC JAKARTA',
  'description': 'KPPBC JAKARTA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '040500',
  'name': 'BLBC KELAS I JAKARTA',
  'description': 'BLBC KELAS I JAKARTA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '040600',
  'name': 'KPPBC KANTOR POS PASAR BARU',
  'description': 'KPPBC KANTOR POS PASAR BARU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '040700',
  'name': 'PANGSAROP TANJUNG PRIOK',
  'description': 'PANGSAROP TANJUNG PRIOK',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '050000',
  'name': 'KANWIL JABAR',
  'description': 'KANWIL JABAR',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '050100',
  'name': 'KPU SOEKARNO-HATTA',
  'description': 'KPU SOEKARNO-HATTA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '050300',
  'name': 'KPPBC BOGOR',
  'description': 'KPPBC BOGOR',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '050400',
  'name': 'KPPBC TMP MERAK',
  'description': 'KPPBC TMP MERAK',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '050500',
  'name': 'KPPBC BANDUNG',
  'description': 'KPPBC BANDUNG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '050600',
  'name': 'KPPBC TASIKMALAYA',
  'description': 'KPPBC TASIKMALAYA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '050700',
  'name': 'KPPBC CIREBON',
  'description': 'KPPBC CIREBON',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '050800',
  'name': 'KPPBC PURWAKARTA',
  'description': 'KPPBC PURWAKARTA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '050900',
  'name': 'KPPBC BEKASI',
  'description': 'KPPBC BEKASI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '051000',
  'name': 'KPPBC IKARANG',
  'description': 'KPPBC IKARANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '060000',
  'name': 'KANWIL JATENG DIY',
  'description': 'KANWIL JATENG DIY',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '060100',
  'name': 'KPPBC TMP TANJUNG EMAS',
  'description': 'KPPBC TMP TANJUNG EMAS',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '060200',
  'name': 'KPPBC PEKALONGAN',
  'description': 'KPPBC PEKALONGAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '060300',
  'name': 'KPPBC TMC KUDUS',
  'description': 'KPPBC TMC KUDUS',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '060400',
  'name': 'KPPBC CILACAP',
  'description': 'KPPBC CILACAP',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '060600',
  'name': 'KPPBC SURAKARTA',
  'description': 'KPPBC SURAKARTA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '060700',
  'name': 'KPPBC YOGYAKARTA',
  'description': 'KPPBC YOGYAKARTA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '060800',
  'name': 'KPPBC SEMARANG',
  'description': 'KPPBC SEMARANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '061000',
  'name': 'KPPBC TEGAL',
  'description': 'KPPBC TEGAL',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '061100',
  'name': 'KPPBC MAGELANG',
  'description': 'KPPBC MAGELANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '062000',
  'name': 'KPPBC PURWOKERTO',
  'description': 'KPPBC PURWOKERTO',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '070000',
  'name': 'KANWIL JATIM I',
  'description': 'KANWIL JATIM I',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '070100',
  'name': 'KPPBC TMP TANJUNG PERAK',
  'description': 'KPPBC TMP TANJUNG PERAK',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '070200',
  'name': 'KPPBC MADURA',
  'description': 'KPPBC MADURA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '070300',
  'name': 'KPPBC GRESIK',
  'description': 'KPPBC GRESIK',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '070400',
  'name': 'KPPBC BOJONEGORO',
  'description': 'KPPBC BOJONEGORO',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '070500',
  'name': 'KPPBC TMP JUANDA',
  'description': 'KPPBC TMP JUANDA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '070600',
  'name': 'KPPBC TMC MALANG',
  'description': 'KPPBC TMC MALANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '070700',
  'name': 'KPPBC BLITAR',
  'description': 'KPPBC BLITAR',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '070800',
  'name': 'KPPBC TMC KEDIRI',
  'description': 'KPPBC TMC KEDIRI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '070900',
  'name': 'KPPBC TULUNG AGUNG',
  'description': 'KPPBC TULUNG AGUNG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '071000',
  'name': 'KPPBC MADIUN',
  'description': 'KPPBC MADIUN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '071100',
  'name': 'KPPBC JEMBER',
  'description': 'KPPBC JEMBER',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '071200',
  'name': 'KPPBC PROBOLINGGO',
  'description': 'KPPBC PROBOLINGGO',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '071300',
  'name': 'KPPBC PASURUAN',
  'description': 'KPPBC PASURUAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '071400',
  'name': 'BLBC KELAS II SURABAYA',
  'description': 'BLBC KELAS II SURABAYA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '071500',
  'name': 'KPPBC SIDOARJO',
  'description': 'KPPBC SIDOARJO',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '080000',
  'name': 'KANWIL BALI, NTB DAN NTT',
  'description': 'KANWIL BALI, NTB DAN NTT',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '080100',
  'name': 'KPPBC TMP NGURAH RAI',
  'description': 'KPPBC TMP NGURAH RAI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '080200',
  'name': 'KPPBC DENPASAR',
  'description': 'KPPBC DENPASAR',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '080300',
  'name': 'KPPBC MATARAM',
  'description': 'KPPBC MATARAM',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '080400',
  'name': 'KPPBC SUMBAWA',
  'description': 'KPPBC SUMBAWA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '080500',
  'name': 'KPPBC KUPANG',
  'description': 'KPPBC KUPANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '080700',
  'name': 'KPPBC MAUMERE',
  'description': 'KPPBC MAUMERE',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '081200',
  'name': 'KPPBC BENOA',
  'description': 'KPPBC BENOA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '081300',
  'name': 'KPPBC ATAPUPU',
  'description': 'KPPBC ATAPUPU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '081400',
  'name': 'KPPBC ATAMBUA',
  'description': 'KPPBC ATAMBUA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '090000',
  'name': 'KANWIL KALBAGBAR',
  'description': 'KANWIL KALBAGBAR',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '090100',
  'name': 'KPPBC PONTIANAK',
  'description': 'KPPBC PONTIANAK',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '090200',
  'name': 'KPPBC ENTIKONG',
  'description': 'KPPBC ENTIKONG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '090400',
  'name': 'KPPBC KETAPANG',
  'description': 'KPPBC KETAPANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '090500',
  'name': 'KPPBC SINTETE',
  'description': 'KPPBC SINTETE',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '090700',
  'name': 'KPPBC SAMPIT',
  'description': 'KPPBC SAMPIT',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '090800',
  'name': 'KPPBC PANGKALAN BUN',
  'description': 'KPPBC PANGKALAN BUN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '090900',
  'name': 'KPPBC PULANG PISAU',
  'description': 'KPPBC PULANG PISAU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '091000',
  'name': 'KPPBC NANGA BADAU',
  'description': 'KPPBC NANGA BADAU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '092000',
  'name': 'KPPBC JAGOI BABANG',
  'description': 'KPPBC JAGOI BABANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '100000',
  'name': 'KANWIL KALBAGTIM',
  'description': 'KANWIL KALBAGTIM',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '100100',
  'name': 'KPPBC BANJARMASIN',
  'description': 'KPPBC BANJARMASIN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '100200',
  'name': 'KPPBC KOTABARU',
  'description': 'KPPBC KOTABARU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '100300',
  'name': 'KPPBC BALIKPAPAN',
  'description': 'KPPBC BALIKPAPAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '100500',
  'name': 'KPPBC SAMARINDA',
  'description': 'KPPBC SAMARINDA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '100600',
  'name': 'KPPBC BONTANG',
  'description': 'KPPBC BONTANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '100800',
  'name': 'KPPBC TARAKAN',
  'description': 'KPPBC TARAKAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '100900',
  'name': 'KPPBC NUNUKAN',
  'description': 'KPPBC NUNUKAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '101000',
  'name': 'KPPBC SANGATTA',
  'description': 'KPPBC SANGATTA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '110000',
  'name': 'KANWIL SULBAGSEL',
  'description': 'KANWIL SULBAGSEL',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '110100',
  'name': 'KPPBC MAKASSAR',
  'description': 'KPPBC MAKASSAR',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '110300',
  'name': 'KPPBC PAREPARE',
  'description': 'KPPBC PAREPARE',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '110400',
  'name': 'KPPBC MALILI',
  'description': 'KPPBC MALILI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '110500',
  'name': 'KPPBC BAJOE',
  'description': 'KPPBC BAJOE',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '110600',
  'name': 'KPPBC KENDARI',
  'description': 'KPPBC KENDARI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '110700',
  'name': 'KPPBC POMALAA',
  'description': 'KPPBC POMALAA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '110800',
  'name': 'KPPBC PANTOLOAN',
  'description': 'KPPBC PANTOLOAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '110900',
  'name': 'KPPBC MOROWALI',
  'description': 'KPPBC MOROWALI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '111000',
  'name': 'KPPBC LUWUK',
  'description': 'KPPBC LUWUK',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '111100',
  'name': 'KPPBC BITUNG',
  'description': 'KPPBC BITUNG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '111200',
  'name': 'KPPBC MANADO',
  'description': 'KPPBC MANADO',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '111300',
  'name': 'KPPBC GORONTALO',
  'description': 'KPPBC GORONTALO',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '111400',
  'name': 'PANGSAROP PANTOLOAN',
  'description': 'PANGSAROP PANTOLOAN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '120000',
  'name': 'KANWIL MALUKU',
  'description': 'KANWIL MALUKU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '120100',
  'name': 'KPPBC AMBON',
  'description': 'KPPBC AMBON',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '120200',
  'name': 'KPPBC TERNATE',
  'description': 'KPPBC TERNATE',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '120300',
  'name': 'KPPBC SORONG',
  'description': 'KPPBC SORONG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '120400',
  'name': 'KPPBC MANOKWARI',
  'description': 'KPPBC MANOKWARI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '120500',
  'name': 'KPPBC FAK-FAK',
  'description': 'KPPBC FAK-FAK',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '120600',
  'name': 'KPPBC JAYAPURA',
  'description': 'KPPBC JAYAPURA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '120700',
  'name': 'KPPBC MERAUKE',
  'description': 'KPPBC MERAUKE',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '120800',
  'name': 'KPPBC AMAMAPARE',
  'description': 'KPPBC AMAMAPARE',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '120900',
  'name': 'KPPBC BIAK',
  'description': 'KPPBC BIAK',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '121000',
  'name': 'KPPBC TUAL',
  'description': 'KPPBC TUAL',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '121100',
  'name': 'PANGSAROP SORONG',
  'description': 'PANGSAROP SORONG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '122000',
  'name': 'KPPBC BINTUNI',
  'description': 'KPPBC BINTUNI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '122100',
  'name': 'KPPBC KAIMANA',
  'description': 'KPPBC KAIMANA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '122200',
  'name': 'KPPBC NABIRE',
  'description': 'KPPBC NABIRE',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '122300',
  'name': 'KPPBC BABO',
  'description': 'KPPBC BABO',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '130000',
  'name': 'KANWIL ACEH',
  'description': 'KANWIL ACEH',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '130100',
  'name': 'KPPBC BANDA ACEH',
  'description': 'KPPBC BANDA ACEH',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '130300',
  'name': 'KPPBC SABANG',
  'description': 'KPPBC SABANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '130400',
  'name': 'KPPBC MEULABOH',
  'description': 'KPPBC MEULABOH',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '130500',
  'name': 'KPPBC LHOKSEUMAWE',
  'description': 'KPPBC LHOKSEUMAWE',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '130600',
  'name': 'KPPBC KUALA LANGSA',
  'description': 'KPPBC KUALA LANGSA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '140000',
  'name': 'KANWIL RIAU',
  'description': 'KANWIL RIAU',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '150000',
  'name': 'KANWIL BANTEN',
  'description': 'KANWIL BANTEN',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '150300',
  'name': 'KPPBC TANGERANG',
  'description': 'KPPBC TANGERANG',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '160000',
  'name': 'KANWIL JATIM II',
  'description': 'KANWIL JATIM II',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '160200',
  'name': 'KPPBC MARUNDA',
  'description': 'KPPBC MARUNDA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '160700',
  'name': 'KPPBC BANYUWANGI',
  'description': 'KPPBC BANYUWANGI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '170000',
  'name': 'KANWIL SUMBAGBAR',
  'description': 'KANWIL SUMBAGBAR',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '180000',
  'name': 'KANWIL KALBAGSEL',
  'description': 'KANWIL KALBAGSEL',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '180100',
  'name': 'KPPBC Nashta',
  'description': 'KPPBC Nashta',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '180200',
  'name': 'KPPBC Nashta',
  'description': 'KPPBC Nashta',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '190000',
  'name': 'KANWIL SULBAGTARA',
  'description': 'KANWIL SULBAGTARA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '200000',
  'name': 'KANWIL KHUSUS PAPUA',
  'description': 'KANWIL KHUSUS PAPUA',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '760000',
  'name': 'PUSDIKLAT BEA DAN CUKAI',
  'description': 'PUSDIKLAT BEA DAN CUKAI',
  'is_active': True},
 {'reference_slug': 'referensi-kantor',
  'reference_name': 'Referensi Kantor',
  'code': '999999',
  'name': 'UNIT LAIN DI LUAR DJBC',
  'description': 'UNIT LAIN DI LUAR DJBC',
  'is_active': True}]
