"""Seeder master data CEISA untuk referensi status.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_STATUS_CODES = [{'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '001',
  'name': 'Perekaman Dokumen',
  'description': 'Perekaman Dokumen',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '100',
  'name': 'Penerimaan Data',
  'description': 'Penerimaan Data',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '104',
  'name': 'Kirim Dokumen Ke INSW',
  'description': 'Kirim Dokumen Ke INSW',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '105',
  'name': 'LNSW - Penerimaan Dokumen',
  'description': 'LNSW - Penerimaan Dokumen',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '106',
  'name': 'LNSW - Cek Mandatory Content',
  'description': 'LNSW - Cek Mandatory Content',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '107',
  'name': 'LNSW - Analyzing Point',
  'description': 'LNSW - Analyzing Point',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '108',
  'name': 'LNSW - Konfirmasi Skep',
  'description': 'LNSW - Konfirmasi Skep',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '110',
  'name': 'Validasi',
  'description': 'Validasi',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '111',
  'name': 'Proses Validasi',
  'description': 'Proses Validasi',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '120',
  'name': 'Reject',
  'description': 'Reject',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '130',
  'name': 'Penerimaan Dokumen',
  'description': 'Penerimaan Dokumen',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '200',
  'name': 'Analyzing Point',
  'description': 'Analyzing Point',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '205',
  'name': 'Pengecekan Jaminan',
  'description': 'Pengecekan Jaminan',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '210',
  'name': 'Payment Verification',
  'description': 'Payment Verification',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '220',
  'name': 'Pre-Notification',
  'description': 'Pre-Notification',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '225',
  'name': 'Approval Similarity',
  'description': 'Approval Similarity',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '230',
  'name': 'Siap Jalur',
  'description': 'Siap Jalur',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '240',
  'name': 'Penjaluran',
  'description': 'Penjaluran',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '300',
  'name': 'Pemeriksaan Fisik',
  'description': 'Pemeriksaan Fisik',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '330',
  'name': 'Pemeriksaan Barang',
  'description': 'Pemeriksaan Barang',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '400',
  'name': 'Pemeriksaan Dokumen',
  'description': 'Pemeriksaan Dokumen',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '410',
  'name': 'INP',
  'description': 'INP',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '415',
  'name': 'LAB',
  'description': 'LAB',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '440',
  'name': 'SPTNP',
  'description': 'SPTNP',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '500',
  'name': 'Gate In TPS',
  'description': 'Gate In TPS',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '501',
  'name': 'Gate Out TPS',
  'description': 'Gate Out TPS',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '502',
  'name': 'Pelekatan Segel',
  'description': 'Pelekatan Segel',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '503',
  'name': 'Pembukaan Segel',
  'description': 'Pembukaan Segel',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '510',
  'name': 'Gate In TPB',
  'description': 'Gate In TPB',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '511',
  'name': 'Pembongkaran',
  'description': 'Pembongkaran',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '512',
  'name': 'Stuffing',
  'description': 'Stuffing',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '513',
  'name': 'Area Transit',
  'description': 'Area Transit',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '514',
  'name': 'Gate Out TPB',
  'description': 'Gate Out TPB',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '800',
  'name': 'Selesai Proses',
  'description': 'Selesai Proses',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '900',
  'name': 'Pembatalan',
  'description': 'Pembatalan',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '981',
  'name': 'Penelitian Unit Pengawas',
  'description': 'Penelitian Unit Pengawas',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '960',
  'name': 'Perekaman Perbaikan Portal',
  'description': 'Perekaman Perbaikan Portal',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '961',
  'name': 'Penelitian Perbaikan',
  'description': 'Penelitian Perbaikan',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '962',
  'name': 'Perekaman Perbaikan Inhouse',
  'description': 'Perekaman Perbaikan Inhouse',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '963',
  'name': 'Validasi Perbaikan',
  'description': 'Validasi Perbaikan',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '965',
  'name': 'Penolakan Perbaikan',
  'description': 'Penolakan Perbaikan',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '966',
  'name': 'Persetujuan Perbaikan',
  'description': 'Persetujuan Perbaikan',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '969',
  'name': 'Pembatalan Perbaikan',
  'description': 'Pembatalan Perbaikan',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '970',
  'name': 'Perbaikan RH',
  'description': 'Perbaikan RH',
  'is_active': True},
 {'reference_slug': 'referensi-status',
  'reference_name': 'Referensi Status',
  'code': '971',
  'name': 'Perbaikan RH Selesai',
  'description': 'Perbaikan RH Selesai',
  'is_active': True}]
