"""Seeder master data CEISA untuk referensi dokumen.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_DOKUMEN_CODES = [{'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '10',
  'name': 'RKSP',
  'description': 'RKSP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '11',
  'name': 'MANIFES',
  'description': 'MANIFES',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '16',
  'name': 'BC 1.6 - PEMBERITAHUAN PABEAN PENGELUARAN BARANG DARI KAWASAN PABEAN UNTUK DITIMBUN DI PUSAT LOGISTIK '
          'BERIKAT',
  'description': 'BC 1.6 - PEMBERITAHUAN PABEAN PENGELUARAN BARANG DARI KAWASAN PABEAN UNTUK DITIMBUN DI PUSAT '
                 'LOGISTIK BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '20',
  'name': 'BC 2.0 - PEMBERITAHUAN IMPOR BARANG',
  'description': 'BC 2.0 - PEMBERITAHUAN IMPOR BARANG',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '21',
  'name': 'PIBK/IMPOR KHUSUS',
  'description': 'PIBK/IMPOR KHUSUS',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '23',
  'name': 'BC 2.3 - PEMBERITAHUAN IMPOR BARANG UNTUK DITIMBUN DI TEMPAT PENIMBUNAN BERIKAT',
  'description': 'BC 2.3 - PEMBERITAHUAN IMPOR BARANG UNTUK DITIMBUN DI TEMPAT PENIMBUNAN BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '25',
  'name': 'BC 2.5 - PEMBERITAHUAN IMPOR BARANG DARI TEMPAT PENIMBUNAN BERIKAT',
  'description': 'BC 2.5 - PEMBERITAHUAN IMPOR BARANG DARI TEMPAT PENIMBUNAN BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '27',
  'name': 'BC 2.7 - PEMBERITAHUAN PENGELUARAN UNTUK DIANGKUT DARI TEMPAT PENIMBUNAN BERIKAT KE TEMPAT PENIMBUNAN '
          'BERIKAT LAINNYA',
  'description': 'BC 2.7 - PEMBERITAHUAN PENGELUARAN UNTUK DIANGKUT DARI TEMPAT PENIMBUNAN BERIKAT KE TEMPAT '
                 'PENIMBUNAN BERIKAT LAINNYA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '28',
  'name': 'BC 2.8 - PEMBERITAHUAN IMPOR BARANG DARI PUSAT LOGISTIK BERIKAT',
  'description': 'BC 2.8 - PEMBERITAHUAN IMPOR BARANG DARI PUSAT LOGISTIK BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '30',
  'name': 'BC 3.0 - PEMBERITAHUAN EKSPOR NARAMG',
  'description': 'BC 3.0 - PEMBERITAHUAN EKSPOR NARAMG',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '33',
  'name': 'BC 3.3 - PEMBERITAHUAN EKSPOR BARANG MELALUI/DARI PUSAT LOGISTIK BERIKAT',
  'description': 'BC 3.3 - PEMBERITAHUAN EKSPOR BARANG MELALUI/DARI PUSAT LOGISTIK BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '40',
  'name': 'BC 4.0 - PEMBERITAHUAN PEMASUKAN BARANG ASAL TEMPAT LAIN DALAM DAERAH PABEAN KE TEMPAT PENIMBUNAN BERIKAT',
  'description': 'BC 4.0 - PEMBERITAHUAN PEMASUKAN BARANG ASAL TEMPAT LAIN DALAM DAERAH PABEAN KE TEMPAT PENIMBUNAN '
                 'BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '41',
  'name': 'BC 4.1 - PEMBERITAHUAN PENGELUARAN KEMBALI BARANG ASAL TEMPAT LAIN DALAM DAERAH PABEAN DARI TEMPAT '
          'PENIMBUNAN BERIKAT',
  'description': 'BC 4.1 - PEMBERITAHUAN PENGELUARAN KEMBALI BARANG ASAL TEMPAT LAIN DALAM DAERAH PABEAN DARI TEMPAT '
                 'PENIMBUNAN BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '50',
  'name': 'KITE',
  'description': 'KITE',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '51',
  'name': 'FTZ 01',
  'description': 'FTZ 01',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '52',
  'name': 'FTZ 02',
  'description': 'FTZ 02',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '53',
  'name': 'FTZ 03',
  'description': 'FTZ 03',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '65',
  'name': 'BC 1.1 KONSOLIDASI PJT',
  'description': 'BC 1.1 KONSOLIDASI PJT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '111',
  'name': 'Bank Devisa Hasil Ekspor (DHE)',
  'description': 'Bank Devisa Hasil Ekspor (DHE)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '161',
  'name': 'PPB - PEMBERITAHUAN PERPINDAHAN BARANG ANTAR TEMPAT PENIMBUNAN DALAM SATU PUSAT LOGISTIK BERIKAT',
  'description': 'PPB - PEMBERITAHUAN PERPINDAHAN BARANG ANTAR TEMPAT PENIMBUNAN DALAM SATU PUSAT LOGISTIK BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '202',
  'name': 'PENGELUARAN BAHAN BAKU DAN/ ATAU SISA BAHAN BAKU',
  'description': 'PENGELUARAN BAHAN BAKU DAN/ ATAU SISA BAHAN BAKU',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '203',
  'name': 'PENGELUARAN SEMENTARA - SUBKONTRAK',
  'description': 'PENGELUARAN SEMENTARA - SUBKONTRAK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '204',
  'name': 'PENGELUARAN SEMENTARA - PERBAIKAN/ REPARASI',
  'description': 'PENGELUARAN SEMENTARA - PERBAIKAN/ REPARASI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '205',
  'name': 'PENGELUARAN SEMENTARA - PEMINJAMAN BARANG MODAL UNTUK KEPERLUAN PRODUKSI',
  'description': 'PENGELUARAN SEMENTARA - PEMINJAMAN BARANG MODAL UNTUK KEPERLUAN PRODUKSI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '206',
  'name': 'PENGELUARAN SEMENTARA - PENGETESAN ATAU PENGEMBANGAN KUALITAS PRODUKSI',
  'description': 'PENGELUARAN SEMENTARA - PENGETESAN ATAU PENGEMBANGAN KUALITAS PRODUKSI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '207',
  'name': 'PENGELUARAN SEMENTARA - PENGGUNAAN KEMASAN YANG DIPAKAI BERULANG (RETURNABLE PACKAGE)',
  'description': 'PENGELUARAN SEMENTARA - PENGGUNAAN KEMASAN YANG DIPAKAI BERULANG (RETURNABLE PACKAGE)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '208',
  'name': 'PENGELUARAN SEMENTARA - DIPAMERKAN',
  'description': 'PENGELUARAN SEMENTARA - DIPAMERKAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '209',
  'name': 'PENGELUARAN SEMENTARA - TUJUAN LAIN DENGAN PERSETUJUAN KEPALA KANTOR PABEAN',
  'description': 'PENGELUARAN SEMENTARA - TUJUAN LAIN DENGAN PERSETUJUAN KEPALA KANTOR PABEAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '210',
  'name': 'PENERIMAAN PEKERJAAN - SUBKONTRAK',
  'description': 'PENERIMAAN PEKERJAAN - SUBKONTRAK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '211',
  'name': 'PENERIMAAN PEKERJAAN - PERBAIKAN/ REPARASI',
  'description': 'PENERIMAAN PEKERJAAN - PERBAIKAN/ REPARASI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '212',
  'name': 'PENERIMAAN PEKERJAAN - PEKERJAAN LAIN',
  'description': 'PENERIMAAN PEKERJAAN - PEKERJAAN LAIN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '213',
  'name': 'PEMUSNAHAN BARANG DI KAWASAN BERIKAT',
  'description': 'PEMUSNAHAN BARANG DI KAWASAN BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '217',
  'name': 'PACKING LIST',
  'description': 'PACKING LIST',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '246',
  'name': 'L/C',
  'description': 'L/C',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '261',
  'name': 'BC 2.6.1 - PEMBERITAHUAN PENGELUARAN BARANG DARI TEMPAT PENIMBUNAN BERIKAT DENGAN JAMINAN',
  'description': 'BC 2.6.1 - PEMBERITAHUAN PENGELUARAN BARANG DARI TEMPAT PENIMBUNAN BERIKAT DENGAN JAMINAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '262',
  'name': 'BC 2.6.2 - PEMBERITAHUAN PEMASUKAN KEMBALI BARANG YANG DI KELUARKAN DARI TEMPAT PENIMBUNAN BERIKAT DENGAN '
          'JAMINAN',
  'description': 'BC 2.6.2 - PEMBERITAHUAN PEMASUKAN KEMBALI BARANG YANG DI KELUARKAN DARI TEMPAT PENIMBUNAN BERIKAT '
                 'DENGAN JAMINAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '281',
  'name': 'PPK - PEMBERITAHUAN PEMASUKAN KEMBALI BARANG ASAL PLB DARI LOKASI PENERIMA FASILITAS DI TEMPAT LAIN DALAM '
          'DAERAH PABEAN KE PLB',
  'description': 'PPK - PEMBERITAHUAN PEMASUKAN KEMBALI BARANG ASAL PLB DARI LOKASI PENERIMA FASILITAS DI TEMPAT LAIN '
                 'DALAM DAERAH PABEAN KE PLB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '282',
  'name': 'DOKAP PLB - PEMBERITAHUAN PENGELUARAN DENGAN DOKUMEN PELENGKAP',
  'description': 'DOKAP PLB - PEMBERITAHUAN PENGELUARAN DENGAN DOKUMEN PELENGKAP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '302',
  'name': 'CN Ekspor',
  'description': 'CN Ekspor',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '315',
  'name': 'KONTRAK',
  'description': 'KONTRAK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '331',
  'name': 'P3BET - PEMBERITAHUAN PENGGABUNGAN DAN PEMECAHAN BARANG EKSPOR DAN TRANSHIPMENT',
  'description': 'P3BET - PEMBERITAHUAN PENGGABUNGAN DAN PEMECAHAN BARANG EKSPOR DAN TRANSHIPMENT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '343',
  'name': 'SHIPING ORDER',
  'description': 'SHIPING ORDER',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '380',
  'name': 'INVOICE',
  'description': 'INVOICE',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '383',
  'name': 'SSTB',
  'description': 'SSTB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '388',
  'name': 'FAKTUR PAJAK',
  'description': 'FAKTUR PAJAK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '410',
  'name': 'SURAT SANGGUP BAYAR / SSB',
  'description': 'SURAT SANGGUP BAYAR / SSB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '430',
  'name': 'BANK GARANSI',
  'description': 'BANK GARANSI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '440',
  'name': 'SURAT TANDA BUKTI SETOR / STBS',
  'description': 'SURAT TANDA BUKTI SETOR / STBS',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '454',
  'name': 'SSPCP / SSBC',
  'description': 'SSPCP / SSBC',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '455',
  'name': 'SURAT SETORAN PAJAK (SSP)',
  'description': 'SURAT SETORAN PAJAK (SSP)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '456',
  'name': 'SKB',
  'description': 'SKB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '457',
  'name': 'Surat Keterangan Bebas (SKB) PPh',
  'description': 'Surat Keterangan Bebas (SKB) PPh',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '458',
  'name': 'SURAT KETERANGAN TIDAK DIPUNGUT (SKTD) PPN',
  'description': 'SURAT KETERANGAN TIDAK DIPUNGUT (SKTD) PPN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '459',
  'name': 'Non SKB / SKTD',
  'description': 'Non SKB / SKTD',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '500',
  'name': 'MOU PDE (Eksportir)',
  'description': 'MOU PDE (Eksportir)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '511',
  'name': 'FTZ-01 PEMASUKAN DARI LUAR DAERAH PABEAN (IMPOR)',
  'description': 'FTZ-01 PEMASUKAN DARI LUAR DAERAH PABEAN (IMPOR)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '512',
  'name': 'FTZ-01 PENGELUARAN KE LUAR DAERAH PABEAN (EKSPOR)',
  'description': 'FTZ-01 PENGELUARAN KE LUAR DAERAH PABEAN (EKSPOR)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '513',
  'name': 'FTZ-01 PENGELUARAN KE TEMPAT LAIN DALAM DAERAH PABEAN',
  'description': 'FTZ-01 PENGELUARAN KE TEMPAT LAIN DALAM DAERAH PABEAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '521',
  'name': 'FTZ-02 PEMASUKAN ANTAR FREE TRADE ZONE DAN KAWASAN BERIKAT',
  'description': 'FTZ-02 PEMASUKAN ANTAR FREE TRADE ZONE DAN KAWASAN BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '522',
  'name': 'FTZ-02 PENGELUARAN ANTAR FREE TRADE ZONE DAN KAWASAN BERIKAT',
  'description': 'FTZ-02 PENGELUARAN ANTAR FREE TRADE ZONE DAN KAWASAN BERIKAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '531',
  'name': 'FTZ-03 PEMASUKAN DARI TEMPAT LAIN DALAM DAERAH PABEAN',
  'description': 'FTZ-03 PEMASUKAN DARI TEMPAT LAIN DALAM DAERAH PABEAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '640',
  'name': 'DELIVERY ORDER',
  'description': 'DELIVERY ORDER',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '666',
  'name': 'Pengecualian Dengan Surat Keputusan',
  'description': 'Pengecualian Dengan Surat Keputusan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '704',
  'name': 'MASTER B/L',
  'description': 'MASTER B/L',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '705',
  'name': 'B/L',
  'description': 'B/L',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '740',
  'name': 'AWB',
  'description': 'AWB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '741',
  'name': 'MASTER AWB',
  'description': 'MASTER AWB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '800',
  'name': 'SERTIFIKAT ALAT PERANGKAT TELEKOM/POSTEL',
  'description': 'SERTIFIKAT ALAT PERANGKAT TELEKOM/POSTEL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '803',
  'name': 'SATS LN / DEPHUT',
  'description': 'SATS LN / DEPHUT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '805',
  'name': 'REGISTRASI B3 / KLH',
  'description': 'REGISTRASI B3 / KLH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '808',
  'name': 'IJIN IMPOR / POLRI',
  'description': 'IJIN IMPOR / POLRI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '809',
  'name': 'SIE',
  'description': 'SIE',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '810',
  'name': 'SM/SPM',
  'description': 'SM/SPM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '811',
  'name': 'Sertifikat Legalitas Kayu (Dok.V-Legal)',
  'description': 'Sertifikat Legalitas Kayu (Dok.V-Legal)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '812',
  'name': 'Dok. Impor (PIB)',
  'description': 'Dok. Impor (PIB)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '813',
  'name': 'DOK. CUKAI (CK)',
  'description': 'DOK. CUKAI (CK)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '814',
  'name': 'SKEP IJIN EKSPOR BERKALA',
  'description': 'SKEP IJIN EKSPOR BERKALA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '815',
  'name': 'SKEP IJIN TATA NIAGA EKSPOR',
  'description': 'SKEP IJIN TATA NIAGA EKSPOR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '816',
  'name': 'DOK. EKSPOR (PEB)',
  'description': 'DOK. EKSPOR (PEB)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '817',
  'name': 'Eksportir Terdaftar (ET) Depdag',
  'description': 'Eksportir Terdaftar (ET) Depdag',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '818',
  'name': 'Endorsement BRIK',
  'description': 'Endorsement BRIK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '819',
  'name': 'Sertifikat Intan Kasar',
  'description': 'Sertifikat Intan Kasar',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '820',
  'name': 'Surat Persetujuan Ekspor (SPE)',
  'description': 'Surat Persetujuan Ekspor (SPE)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '821',
  'name': 'Surat Tanda Registrasi UPPB',
  'description': 'Surat Tanda Registrasi UPPB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '822',
  'name': 'Srt Tanda Pendaftaran Pedagang Bokor SIR',
  'description': 'Srt Tanda Pendaftaran Pedagang Bokor SIR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '834',
  'name': 'SNI GULA KRISTAL MENTAH / DEPTAN',
  'description': 'SNI GULA KRISTAL MENTAH / DEPTAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '835',
  'name': 'IZIN DAN/ATAU PENDAFT PESTISIDA / DEPTAN',
  'description': 'IZIN DAN/ATAU PENDAFT PESTISIDA / DEPTAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '836',
  'name': 'IZIN IMPOR / DEPTAN',
  'description': 'IZIN IMPOR / DEPTAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '842',
  'name': 'SNI / ESDM',
  'description': 'SNI / ESDM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '843',
  'name': 'NOMOR PELUMAS TERDAFTAR / ESDM',
  'description': 'NOMOR PELUMAS TERDAFTAR / ESDM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '844',
  'name': 'IJIN USAHA NIAGA/IU NIAGA TERBATAS/ESDM',
  'description': 'IJIN USAHA NIAGA/IU NIAGA TERBATAS/ESDM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '845',
  'name': 'REKOMENDASI IMPOR PELUMAS',
  'description': 'REKOMENDASI IMPOR PELUMAS',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '846',
  'name': 'SKEM',
  'description': 'SKEM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '851',
  'name': 'SURAT IJIN KARANTINA TANAMAN',
  'description': 'SURAT IJIN KARANTINA TANAMAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '853',
  'name': 'SURAT IJIN KARANTINA HEWAN / IKAN',
  'description': 'SURAT IJIN KARANTINA HEWAN / IKAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '854',
  'name': 'SURAT PERSETUJUAN MUAT BPOM',
  'description': 'SURAT PERSETUJUAN MUAT BPOM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '856',
  'name': 'LAP. PEMERIKSAAN SURVEYOR (LPS-E)',
  'description': 'LAP. PEMERIKSAAN SURVEYOR (LPS-E)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '857',
  'name': 'FUMIGATION CERTIFICATE',
  'description': 'FUMIGATION CERTIFICATE',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '858',
  'name': 'CITES CERTIFICATE',
  'description': 'CITES CERTIFICATE',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '860',
  'name': 'Electronic Certificate Of Origin (E-CO)',
  'description': 'Electronic Certificate Of Origin (E-CO)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '861',
  'name': 'CERTIFICATE OF ORIGIN (CO)',
  'description': 'CERTIFICATE OF ORIGIN (CO)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '862',
  'name': 'SKEP USDFS',
  'description': 'SKEP USDFS',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '871',
  'name': 'Nomor Pendaftaran Alat Kesehatan/Depkes',
  'description': 'Nomor Pendaftaran Alat Kesehatan/Depkes',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '872',
  'name': 'LAPORAN SURVEYOR DEPKES',
  'description': 'LAPORAN SURVEYOR DEPKES',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '873',
  'name': 'IP (NARKTK, PREKURSOR & PSIKOTR)/DEPKES',
  'description': 'IP (NARKTK, PREKURSOR & PSIKOTR)/DEPKES',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '874',
  'name': 'IT (PREKURSOR & PSIKOTR)/DEPKES',
  'description': 'IT (PREKURSOR & PSIKOTR)/DEPKES',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '875',
  'name': 'SPI (NARKTK, PREKURSOR & PSIKOTR)/DEPKES',
  'description': 'SPI (NARKTK, PREKURSOR & PSIKOTR)/DEPKES',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '876',
  'name': 'Ijin Pembawaan UKA',
  'description': 'Ijin Pembawaan UKA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '877',
  'name': 'Ijin Persetujuan Pembawaan UKA',
  'description': 'Ijin Persetujuan Pembawaan UKA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '878',
  'name': 'Ijin Pelaporan Pembawaan UKA',
  'description': 'Ijin Pelaporan Pembawaan UKA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '888',
  'name': 'PENGECUALIAN PERIJINAN',
  'description': 'PENGECUALIAN PERIJINAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '902',
  'name': 'IJIN BAPETEN',
  'description': 'IJIN BAPETEN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '911',
  'name': 'SURAT KEPUTUSAN',
  'description': 'SURAT KEPUTUSAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '912',
  'name': 'SKEP FASILITAS BKPM',
  'description': 'SKEP FASILITAS BKPM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '913',
  'name': 'SKEP FASILITAS PERTAMBANGAN',
  'description': 'SKEP FASILITAS PERTAMBANGAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '914',
  'name': 'KITE IKM',
  'description': 'KITE IKM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '915',
  'name': 'Skep Fasilitas Impor Sementara',
  'description': 'Skep Fasilitas Impor Sementara',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '917',
  'name': 'BPBC / BPPAI',
  'description': 'BPBC / BPPAI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '918',
  'name': 'SK LABEL BAHASA INDONESIA',
  'description': 'SK LABEL BAHASA INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '919',
  'name': 'SK Bermotor',
  'description': 'SK Bermotor',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '920',
  'name': 'SKEP TPB',
  'description': 'SKEP TPB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '936',
  'name': 'KH-9a/Izin Impor Karantina Hewan',
  'description': 'KH-9a/Izin Impor Karantina Hewan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '937',
  'name': 'KH-14/Izin Impor Karantina Hewan',
  'description': 'KH-14/Izin Impor Karantina Hewan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '938',
  'name': 'KH-17/Izin Impor Karantina Hewan',
  'description': 'KH-17/Izin Impor Karantina Hewan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '939',
  'name': 'KT-5/Izin Impor Karantina Pertanian',
  'description': 'KT-5/Izin Impor Karantina Pertanian',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '940',
  'name': 'KT-9/Izin Impor Karantina Pertanian',
  'description': 'KT-9/Izin Impor Karantina Pertanian',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '941',
  'name': 'KT-13/Izin Impor Karantina Pertanian',
  'description': 'KT-13/Izin Impor Karantina Pertanian',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '942',
  'name': 'IZIN IMPOR KARANTINA TUMBUHAN',
  'description': 'IZIN IMPOR KARANTINA TUMBUHAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '943',
  'name': 'KH-5 / IZIN IMPOR KARANTINA HEWAN',
  'description': 'KH-5 / IZIN IMPOR KARANTINA HEWAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '944',
  'name': 'KH-7 / IZIN IMPOR KARANTINA HEWAN',
  'description': 'KH-7 / IZIN IMPOR KARANTINA HEWAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '945',
  'name': 'KH-12 / IZIN IMPOR KARANTINA HEWAN',
  'description': 'KH-12 / IZIN IMPOR KARANTINA HEWAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '946',
  'name': 'KID-3 / IZIN IMPOR KARANTINA IKAN',
  'description': 'KID-3 / IZIN IMPOR KARANTINA IKAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '947',
  'name': 'KID-15 / IZIN IMPOR KARANTINA IKAN',
  'description': 'KID-15 / IZIN IMPOR KARANTINA IKAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '948',
  'name': 'NPIK',
  'description': 'NPIK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '949',
  'name': 'PENGAKUAN SBG IMPORTIR PRODUSEN',
  'description': 'PENGAKUAN SBG IMPORTIR PRODUSEN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '950',
  'name': 'KID-4/IZIN KARANTINA IKAN',
  'description': 'KID-4/IZIN KARANTINA IKAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '951',
  'name': 'HC (HEALTH CERTIFICATE)',
  'description': 'HC (HEALTH CERTIFICATE)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '956',
  'name': 'PENGAKUAN SBG IMPORTIR TERDAFTAR',
  'description': 'PENGAKUAN SBG IMPORTIR TERDAFTAR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '957',
  'name': 'SNI/SPB/DEPDAG',
  'description': 'SNI/SPB/DEPDAG',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '958',
  'name': 'LAPORAN SURVEYOR / DEPDAG',
  'description': 'LAPORAN SURVEYOR / DEPDAG',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '959',
  'name': 'SURAT PERSETUJUAN IMPOR DEP.DAG',
  'description': 'SURAT PERSETUJUAN IMPOR DEP.DAG',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '960',
  'name': '3D/PC dan/atau PFP',
  'description': '3D/PC dan/atau PFP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '961',
  'name': 'Hasil Lab',
  'description': 'Hasil Lab',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '993',
  'name': 'SURAT IJIN MENTERI PERTANIAN',
  'description': 'SURAT IJIN MENTERI PERTANIAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '994',
  'name': 'BUKTI PENERIMAAN JAMINAN (BPJ)',
  'description': 'BUKTI PENERIMAAN JAMINAN (BPJ)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '995',
  'name': 'STBS / SSP-E (PAJAK EKSPOR)',
  'description': 'STBS / SSP-E (PAJAK EKSPOR)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '996',
  'name': 'SRT SANGGUP BAYAR (SSB)',
  'description': 'SRT SANGGUP BAYAR (SSB)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '997',
  'name': 'COSTOMS BOND / STTJ',
  'description': 'COSTOMS BOND / STTJ',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '998',
  'name': 'SKEP FASILITAS KEMUDAHAN EKSPOR',
  'description': 'SKEP FASILITAS KEMUDAHAN EKSPOR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '999',
  'name': 'LAINNYA',
  'description': 'LAINNYA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03001',
  'name': 'Izin Prinsip Pendirian Kawasan Berikat Sebelum Fisik Bangunan Berdiri',
  'description': 'Izin Prinsip Pendirian Kawasan Berikat Sebelum Fisik Bangunan Berdiri',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03002',
  'name': 'Keputusan Penetapan Tempat Sebagai Kawasan Berikat Dan Pemberian Izin Penyelenggara Kawasan Berikat',
  'description': 'Keputusan Penetapan Tempat Sebagai Kawasan Berikat Dan Pemberian Izin Penyelenggara Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03003',
  'name': 'Persetujuan Penetapan Tempat Sebagai Kawasan Berikat Dan Pemberian Izin Penyelenggara Kawasan Berikat '
          'Sekaligus Izin Pengusaha Kawasan Berikat',
  'description': 'Persetujuan Penetapan Tempat Sebagai Kawasan Berikat Dan Pemberian Izin Penyelenggara Kawasan '
                 'Berikat Sekaligus Izin Pengusaha Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03004',
  'name': 'Izin PDKB',
  'description': 'Izin PDKB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03005',
  'name': 'Perpanjangan Penetapan Tempat Sebagai Kawasan Berikat Dan Izin Penyelenggara Kawasan Berikat, Izin '
          'Pengusaha Kawasan Berikat, Atau Izin PDKB Sebelum Jangka Waktu Izin Tersebut Berakhir',
  'description': 'Perpanjangan Penetapan Tempat Sebagai Kawasan Berikat Dan Izin Penyelenggara Kawasan Berikat, Izin '
                 'Pengusaha Kawasan Berikat, Atau Izin PDKB Sebelum Jangka Waktu Izin Tersebut Berakhir',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03006',
  'name': 'Perubahan Izin Penyelenggara Kawasan Berikat, Izin Pengusaha Kawasan Berikat, Atau Izin PDKB (Terdapat '
          'Perubahan Nama Perusahaan Yang Bukan Dikarenakan Merger Atau Diakuisisi, Jenis Hasil Produksi, Atau Luas '
          'Kawasan Berikat)',
  'description': 'Perubahan Izin Penyelenggara Kawasan Berikat, Izin Pengusaha Kawasan Berikat, Atau Izin PDKB '
                 '(Terdapat Perubahan Nama Perusahaan Yang Bukan Dikarenakan Merger Atau Diakuisisi, Jenis Hasil '
                 'Produksi, Atau Luas Kawasan Berikat)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03007',
  'name': 'Perubahan Keputusan Izin Penyelenggara Kawasan Berikat, Izin Pengusaha Kawasan Berikat, Atau Izin PDKB',
  'description': 'Perubahan Keputusan Izin Penyelenggara Kawasan Berikat, Izin Pengusaha Kawasan Berikat, Atau Izin '
                 'PDKB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03008',
  'name': 'Pemberian Izin Penambahan Pintu Khusus Pemasukan Dan Pengeluaran Barang Di Kawasan Berikat',
  'description': 'Pemberian Izin Penambahan Pintu Khusus Pemasukan Dan Pengeluaran Barang Di Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03009',
  'name': 'Pemberian Izin Penambahan Pintu Khusus Orang Di Kawasan Berikat',
  'description': 'Pemberian Izin Penambahan Pintu Khusus Orang Di Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03010',
  'name': 'Persetujuan Pemasukan Barang Dari Kawasan Bebas Ke Kawasan Berikat',
  'description': 'Persetujuan Pemasukan Barang Dari Kawasan Bebas Ke Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03011',
  'name': 'Persetujuan Pemasukan Barang Modal Dari Luar Daerah Pabean',
  'description': 'Persetujuan Pemasukan Barang Modal Dari Luar Daerah Pabean',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03012',
  'name': 'Persetujuan Pemasukan Barang Modal Dari Kawasan Berikat Lain',
  'description': 'Persetujuan Pemasukan Barang Modal Dari Kawasan Berikat Lain',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03013',
  'name': 'Persetujuan Pemasukan Barang Jadi Asal Luar Daerah Pabean Untuk Digabungkan Dengan Hasil Produksi Utama '
          'Kawasan Berikat',
  'description': 'Persetujuan Pemasukan Barang Jadi Asal Luar Daerah Pabean Untuk Digabungkan Dengan Hasil Produksi '
                 'Utama Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03014',
  'name': 'Persetujuan Pemasukan Peralatan Perkantoran Asal Luar Daerah Pabean Ke Kawasan Berikat',
  'description': 'Persetujuan Pemasukan Peralatan Perkantoran Asal Luar Daerah Pabean Ke Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03015',
  'name': 'Persetujuan Pemasukan Barang Contoh Asal Luar Daerah Pabean',
  'description': 'Persetujuan Pemasukan Barang Contoh Asal Luar Daerah Pabean',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03016',
  'name': 'Persetujuan Pembebasan Bea Masuk Untuk Barang Contoh Yang Akan Dikeluarkan Ke Tempat Lain Dalam Daerah '
          'Pabean',
  'description': 'Persetujuan Pembebasan Bea Masuk Untuk Barang Contoh Yang Akan Dikeluarkan Ke Tempat Lain Dalam '
                 'Daerah Pabean',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03017',
  'name': 'Persetujuan Mengeluarkan Hasil Produksi Kawasan Berikat Ke Tempat Penyelenggaraan Pameran Berikat (TPPB)',
  'description': 'Persetujuan Mengeluarkan Hasil Produksi Kawasan Berikat Ke Tempat Penyelenggaraan Pameran Berikat '
                 '(TPPB)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03018',
  'name': 'Persetujuan Untuk Mengeluarkan Bahan Baku Dan/Atau Bahan Rusak Dan/Atau Apkir (Reject) Yang Sama Sekali '
          'Tidak Diproses Ke Gudang Berikat Asal Barang',
  'description': 'Persetujuan Untuk Mengeluarkan Bahan Baku Dan/Atau Bahan Rusak Dan/Atau Apkir (Reject) Yang Sama '
                 'Sekali Tidak Diproses Ke Gudang Berikat Asal Barang',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03019',
  'name': 'Persetujuan Untuk Mengeluarkan Barang Dan/Atau Bahan Rusak Dan/Atau Apkir (Reject) Asal Tlddp Ke TLDDP',
  'description': 'Persetujuan Untuk Mengeluarkan Barang Dan/Atau Bahan Rusak Dan/Atau Apkir (Reject) Asal Tlddp Ke '
                 'TLDDP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03020',
  'name': 'Persetujuan Pengeluaran Bahan Baku/Sisa Bahan Baku Asal Impor Untuk Direekspor',
  'description': 'Persetujuan Pengeluaran Bahan Baku/Sisa Bahan Baku Asal Impor Untuk Direekspor',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03021',
  'name': 'Persetujuan Pengeluaran Bahan Baku Dan/Atau Sisa Bahan Baku Asal Luar Daerah Pabean Ke Kawasan Berikat Lain',
  'description': 'Persetujuan Pengeluaran Bahan Baku Dan/Atau Sisa Bahan Baku Asal Luar Daerah Pabean Ke Kawasan '
                 'Berikat Lain',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03022',
  'name': 'Persetujuan Pengeluaran Bahan Baku Dan/Atau Sisa Bahan Baku Asal Luar Daerah Pabean Ke Perusahaan Industri '
          'Di TLDDP',
  'description': 'Persetujuan Pengeluaran Bahan Baku Dan/Atau Sisa Bahan Baku Asal Luar Daerah Pabean Ke Perusahaan '
                 'Industri Di TLDDP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03023',
  'name': 'Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan Dalam '
          'Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lain Dalam Satu Manajemen',
  'description': 'Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan '
                 'Dalam Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lain Dalam Satu Manajemen',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03024',
  'name': 'Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan Dalam '
          'Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lain Dalam Satu PKB',
  'description': 'Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan '
                 'Dalam Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lain Dalam Satu PKB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03025',
  'name': 'Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan Dalam '
          'Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lainnya',
  'description': 'Persetujuan Pemindahtanganan Barang Selain Hasil Produksi Dalam Rangka Saling Melengkapi Kebutuhan '
                 'Dalam Proses Produksi Atau Peningkatan Produksi Ke Kawasan Berikat Lainnya',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03026',
  'name': 'Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Dibayar BM-nya Untuk Direekspor',
  'description': 'Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Dibayar BM-nya Untuk Direekspor',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03027',
  'name': 'Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban BM-nya Ke Kawasan Berikat '
          'Lain Setelah Jangka Waktu 2 (Dua) Tahun Sejak Diimpor Dan Telahdipergunakan Di Kawasan Berikat',
  'description': 'Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban BM-nya Ke Kawasan '
                 'Berikat Lain Setelah Jangka Waktu 2 (Dua) Tahun Sejak Diimpor Dan Telahdipergunakan Di Kawasan '
                 'Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03028',
  'name': 'Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban BM Ke Tempat Lain Dalam '
          'Daerah Pabean Sebelum Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat',
  'description': 'Persetujuan Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban BM Ke Tempat Lain '
                 'Dalam Daerah Pabean Sebelum Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di '
                 'Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03029',
  'name': 'Keputusan Pembebasan BM Atas Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban '
          'Pembayaran Bm Ke TLDDP Setelah Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di '
          'Kawasan Berikat',
  'description': 'Keputusan Pembebasan BM Atas Pengeluaran Barang Modal Asal Impor Yang Belum Diselesaikan Kewajiban '
                 'Pembayaran Bm Ke TLDDP Setelah Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di '
                 'Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03030',
  'name': 'Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Lunas BM Untuk Direekspor',
  'description': 'Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Lunas BM Untuk Direekspor',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03031',
  'name': 'Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke '
          'Kawasan Berikat Lain Setelah Dipergunakan Di Kawasan Berikat',
  'description': 'Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban '
                 'Pembayaran Bm Ke Kawasan Berikat Lain Setelah Dipergunakan Di Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03032',
  'name': 'Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke '
          'TLDDP Sebelum Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat Yang '
          'Bersangkutan',
  'description': 'Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban '
                 'Pembayaran Bm Ke TLDDP Sebelum Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di '
                 'Kawasan Berikat Yang Bersangkutan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03033',
  'name': 'Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban Pembayaran Bm Ke '
          'TLDDP Setelah Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di Kawasan Berikat',
  'description': 'Persetujuan Pengeluaran Peralatan Perkantoran Asal Impor Yang Belum Diselesaikan Kewajiban '
                 'Pembayaran Bm Ke TLDDP Setelah Jangka Waktu 4 (Empat) Tahun Sejak Diimpor, Dan Telah Dipergunakan Di '
                 'Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03034',
  'name': 'Persetujuan Untuk Memindahtangankan Barang Modal Dan/Atau Peralatan Perkantoran Yang Telah Dilunasi BM Dan '
          'PDRI Pada Saat Pemasukan Ke Kawasan Berikat',
  'description': 'Persetujuan Untuk Memindahtangankan Barang Modal Dan/Atau Peralatan Perkantoran Yang Telah Dilunasi '
                 'BM Dan PDRI Pada Saat Pemasukan Ke Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03035',
  'name': 'Persetujuan Untuk Memindahtangankan Barang Modal Asal Tempat Lain Dalam Daerah Pabean',
  'description': 'Persetujuan Untuk Memindahtangankan Barang Modal Asal Tempat Lain Dalam Daerah Pabean',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03036',
  'name': 'Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke Luar Daerah Pabean',
  'description': 'Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke Luar Daerah Pabean',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03037',
  'name': 'Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke TLDDP',
  'description': 'Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke TLDDP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03038',
  'name': 'Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke KB Lain',
  'description': 'Persetujuan Pengeluaran Barang Modal Untuk Perbaikan/Reparasi Ke KB Lain',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03039',
  'name': 'Persetujuan Subkontrak Kurang Dari 60 (Enam Puluh) Hari Ke TLDDP',
  'description': 'Persetujuan Subkontrak Kurang Dari 60 (Enam Puluh) Hari Ke TLDDP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03040',
  'name': 'Persetujuan Subkontrak Kurang Dari 60 (Enam Puluh) Hari Ke KB Lain',
  'description': 'Persetujuan Subkontrak Kurang Dari 60 (Enam Puluh) Hari Ke KB Lain',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03041',
  'name': 'Persetujuan Subkontrak Lebih Dari 60 (Enam Puluh) Hari Ke TLDDP',
  'description': 'Persetujuan Subkontrak Lebih Dari 60 (Enam Puluh) Hari Ke TLDDP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03042',
  'name': 'Persetujuan Subkontrak Lebih Dari 60 (Enam Puluh) Hari Ke PDKB Lain',
  'description': 'Persetujuan Subkontrak Lebih Dari 60 (Enam Puluh) Hari Ke PDKB Lain',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03043',
  'name': 'Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke KB Lain Dalam Rangka Subkontrak',
  'description': 'Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke KB Lain Dalam Rangka Subkontrak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03044',
  'name': 'Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke KB Lain Bukan Dalam Rangka Subkontrak',
  'description': 'Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke KB Lain Bukan Dalam Rangka Subkontrak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03045',
  'name': 'Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke TLDDP Dalam Rangka Subkontrak',
  'description': 'Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke TLDDP Dalam Rangka Subkontrak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03046',
  'name': 'Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke TLDDP Bukan Dalam Rangka Subkontrak',
  'description': 'Persetujuan Meminjamkan Mesin/Cetakan (Moulding) Ke TLDDP Bukan Dalam Rangka Subkontrak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03047',
  'name': 'Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke PDKB Lain Dalam Rangka Subkontrak',
  'description': 'Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke PDKB Lain Dalam Rangka '
                 'Subkontrak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03048',
  'name': 'Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke PDKB Lain Bukan Dalam Rangka '
          'Subkontrak',
  'description': 'Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke PDKB Lain Bukan Dalam '
                 'Rangka Subkontrak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03049',
  'name': 'Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke TLDDP Dalam Rangka Subkontrak',
  'description': 'Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke TLDDP Dalam Rangka '
                 'Subkontrak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03050',
  'name': 'Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke TLDDP Selain Dalam Rangka '
          'Subkontrak',
  'description': 'Persetujuan Perpanjangan Meminjamkan Mesin Dan/Atau Cetakan (Moulding) Ke TLDDP Selain Dalam Rangka '
                 'Subkontrak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03051',
  'name': 'Persetujuan Peminjaman Mesin Atau Cetakan (Moulding) Yang Melebihi Jangka Waktu',
  'description': 'Persetujuan Peminjaman Mesin Atau Cetakan (Moulding) Yang Melebihi Jangka Waktu',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03052',
  'name': 'Persetujuan Pemusnahan Atas Barangbarang Yang Busuk Dan/Atau Yang Karena Sifat Dan Bentuknya Dapat '
          'Dimusnahkan',
  'description': 'Persetujuan Pemusnahan Atas Barangbarang Yang Busuk Dan/Atau Yang Karena Sifat Dan Bentuknya Dapat '
                 'Dimusnahkan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03053',
  'name': 'Persetujuan Perusakan Atas Barang Asal Luar Daerah Pabean Yang Karena Sifat Dan Bentuknya Tidak Dapat '
          'Dimusnahkan',
  'description': 'Persetujuan Perusakan Atas Barang Asal Luar Daerah Pabean Yang Karena Sifat Dan Bentuknya Tidak '
                 'Dapat Dimusnahkan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03054',
  'name': 'Persetujuan Menerima Subkontrak Dari TLDDP',
  'description': 'Persetujuan Menerima Subkontrak Dari TLDDP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03055',
  'name': 'Persetujuan Peminjaman Mesin/Cetakan (Moulding) Dari TLDDP Dalam Rangka Subkontrak',
  'description': 'Persetujuan Peminjaman Mesin/Cetakan (Moulding) Dari TLDDP Dalam Rangka Subkontrak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03056',
  'name': 'Persetujuan Peminjaman Mesin/Cetakan (Moulding) Dari TLDDP Bukan Dalam Rangka Subkontrak',
  'description': 'Persetujuan Peminjaman Mesin/Cetakan (Moulding) Dari TLDDP Bukan Dalam Rangka Subkontrak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03057',
  'name': 'Persetujuan Peminjaman Mesin/Peralatan Pabrik Dari TLDDP',
  'description': 'Persetujuan Peminjaman Mesin/Peralatan Pabrik Dari TLDDP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03060',
  'name': 'Persetujuan Pemasukan Barang Modal Berupa Peralatan Pabrik Dari Luar Daerah Pabean',
  'description': 'Persetujuan Pemasukan Barang Modal Berupa Peralatan Pabrik Dari Luar Daerah Pabean',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03061',
  'name': 'Persetujuan Pemasukan Barang Modal Berupa Suku Cadang Dari Luar Daerah Pabean Yang Dimasukkan Tidak '
          'Bersamaan Dengan Barang Modal',
  'description': 'Persetujuan Pemasukan Barang Modal Berupa Suku Cadang Dari Luar Daerah Pabean Yang Dimasukkan Tidak '
                 'Bersamaan Dengan Barang Modal',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03062',
  'name': 'Persetujuan Pemasukan Kembali (Reimpor) Barang Hasil Produksi Asal TPB',
  'description': 'Persetujuan Pemasukan Kembali (Reimpor) Barang Hasil Produksi Asal TPB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03063',
  'name': 'Persetujuan Pemasukan Kembali (Reimpor) Barang Modal Setelah Perbaikan/Reparasi Dari Luar Daerah Pabean',
  'description': 'Persetujuan Pemasukan Kembali (Reimpor) Barang Modal Setelah Perbaikan/Reparasi Dari Luar Daerah '
                 'Pabean',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03064',
  'name': 'Persetujuan Perpanjangan Jangka Waktu Pengeluaran Barang Modal Keperluan Perbaikan/Reparasi Tujuan TLDDP',
  'description': 'Persetujuan Perpanjangan Jangka Waktu Pengeluaran Barang Modal Keperluan Perbaikan/Reparasi Tujuan '
                 'TLDDP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03065',
  'name': 'Persetujuan Pengeluaran Barang Contoh/Sampel KB Dengan Tujuan TLDDP',
  'description': 'Persetujuan Pengeluaran Barang Contoh/Sampel KB Dengan Tujuan TLDDP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'},
 {'reference_slug': 'referensi-dokumen',
  'reference_name': 'Referensi Dokumen',
  'code': '03066',
  'name': 'Rekomendasi Meminjamkan Barang Modal Ke TLDDP Dalam Rangka Subkontrak Atau Bukan Lebih Dari 6 Bulan',
  'description': 'Rekomendasi Meminjamkan Barang Modal Ke TLDDP Dalam Rangka Subkontrak Atau Bukan Lebih Dari 6 Bulan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-dokumen.md'}]
