"""Seeder master data CEISA untuk referensi bank.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_BANK_CODES = [{'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '0',
  'name': 'TRANSAKSI_TUNAI',
  'description': 'TRANSAKSI_TUNAI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '0',
  'name': 'INDONESIA EXIMBANK',
  'description': 'INDONESIA EXIMBANK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '0',
  'name': 'POS INDONESIA',
  'description': 'POS INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '2',
  'name': 'BANK RAKYAT INDONESIA',
  'description': 'BANK RAKYAT INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '8',
  'name': 'BANK MANDIRI',
  'description': 'BANK MANDIRI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '9',
  'name': 'BANK NEGARA INDONESIA',
  'description': 'BANK NEGARA INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '11',
  'name': 'BANK DANAMON SYARIAH',
  'description': 'BANK DANAMON SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '11',
  'name': 'BANK DANAMON',
  'description': 'BANK DANAMON',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '13',
  'name': 'BANK PERMATA SYARIAH',
  'description': 'BANK PERMATA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '13',
  'name': 'BANK PERMATA',
  'description': 'BANK PERMATA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '14',
  'name': 'BANK CENTRAL ASIA',
  'description': 'BANK CENTRAL ASIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '16',
  'name': 'BANK MAYBANK INDONESIA',
  'description': 'BANK MAYBANK INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '16',
  'name': 'BANK MAYBANK INDONESIA SYARIAH',
  'description': 'BANK MAYBANK INDONESIA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '19',
  'name': 'BANK PANIN',
  'description': 'BANK PANIN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '22',
  'name': 'BANK CIMB NIAGA SYARIAH',
  'description': 'BANK CIMB NIAGA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '22',
  'name': 'BANK CIMB NIAGA',
  'description': 'BANK CIMB NIAGA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '23',
  'name': 'BANK UOB BUANA',
  'description': 'BANK UOB BUANA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '28',
  'name': 'BANK OCBC NISP',
  'description': 'BANK OCBC NISP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '28',
  'name': 'BANK OCBC NISP SYARIAH',
  'description': 'BANK OCBC NISP SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '31',
  'name': 'CITIBANK',
  'description': 'CITIBANK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '32',
  'name': 'JPMORGAN CHASE BANK',
  'description': 'JPMORGAN CHASE BANK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '33',
  'name': 'BANK OF AMERICA',
  'description': 'BANK OF AMERICA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '36',
  'name': 'BANK WINDU KENTJANA INTERNATIONAL',
  'description': 'BANK WINDU KENTJANA INTERNATIONAL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '37',
  'name': 'BANK ARTHA GRAHA INTERNASIONAL',
  'description': 'BANK ARTHA GRAHA INTERNASIONAL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '40',
  'name': 'BANGKOK BANK PUBLIC CO. LTD',
  'description': 'BANGKOK BANK PUBLIC CO. LTD',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '41',
  'name': 'HSBC SYARIAH',
  'description': 'HSBC SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '41',
  'name': 'HSBC',
  'description': 'HSBC',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '42',
  'name': 'MUFG BANK, LTD',
  'description': 'MUFG BANK, LTD',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '45',
  'name': 'BANK SUMITOMO MITSUI INDONESIA',
  'description': 'BANK SUMITOMO MITSUI INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '46',
  'name': 'BANK DBS INDONESIA',
  'description': 'BANK DBS INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '47',
  'name': 'BANK RESONA PERDANIA',
  'description': 'BANK RESONA PERDANIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '48',
  'name': 'BANK MIZUHO INDONESIA',
  'description': 'BANK MIZUHO INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '50',
  'name': 'STANDARD CHARTERED BANK',
  'description': 'STANDARD CHARTERED BANK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '52',
  'name': 'THE ROYAL BANK OF SCOTLAND N.V.',
  'description': 'THE ROYAL BANK OF SCOTLAND N.V.',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '54',
  'name': 'BANK CAPITAL INDONESIA',
  'description': 'BANK CAPITAL INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '57',
  'name': 'BANK BNP PARIBAS INDONESIA',
  'description': 'BANK BNP PARIBAS INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '59',
  'name': 'BANK KEB INDONESIA',
  'description': 'BANK KEB INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '60',
  'name': 'PT.BANK RABOBANK INTERNATIONAL INDONESIA',
  'description': 'PT.BANK RABOBANK INTERNATIONAL INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '61',
  'name': 'ANZ PANIN BANK',
  'description': 'ANZ PANIN BANK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '67',
  'name': 'DEUTSCHE BANK AG',
  'description': 'DEUTSCHE BANK AG',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '68',
  'name': 'BANK WOORI INDONESIA',
  'description': 'BANK WOORI INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '69',
  'name': 'BANK OF CHINA LIMITED',
  'description': 'BANK OF CHINA LIMITED',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '76',
  'name': 'BANK BUMI ARTA',
  'description': 'BANK BUMI ARTA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '87',
  'name': 'BANK EKONOMI RAHARJA',
  'description': 'BANK EKONOMI RAHARJA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '88',
  'name': 'BANK ANTARDAERAH',
  'description': 'BANK ANTARDAERAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '89',
  'name': 'BANK RABOBANK INTERNATIONAL INDONESIA',
  'description': 'BANK RABOBANK INTERNATIONAL INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '95',
  'name': 'BANK MUTIARA',
  'description': 'BANK MUTIARA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '97',
  'name': 'BANK MAYAPADA INTERNATIONAL',
  'description': 'BANK MAYAPADA INTERNATIONAL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '110',
  'name': 'BPD JABAR BANTEN',
  'description': 'BPD JABAR BANTEN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '111',
  'name': 'BPD DKI SYARIAH',
  'description': 'BPD DKI SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '111',
  'name': 'BPD DKI',
  'description': 'BPD DKI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '112',
  'name': 'BPD YOGYAKARTA',
  'description': 'BPD YOGYAKARTA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '112',
  'name': 'BPD YOGYAKARTA SYARIAH',
  'description': 'BPD YOGYAKARTA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '113',
  'name': 'BPD JAWA TENGAH SYARIAH',
  'description': 'BPD JAWA TENGAH SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '113',
  'name': 'BPD JAWA TENGAH',
  'description': 'BPD JAWA TENGAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '114',
  'name': 'BPD JAWA TIMUR SYARIAH',
  'description': 'BPD JAWA TIMUR SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '114',
  'name': 'BPD JAWA TIMUR',
  'description': 'BPD JAWA TIMUR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '115',
  'name': 'BPD JAMBI',
  'description': 'BPD JAMBI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '116',
  'name': 'BPD ACEH SYARIAH',
  'description': 'BPD ACEH SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '116',
  'name': 'BPD ACEH',
  'description': 'BPD ACEH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '117',
  'name': 'BPD SUMATERA UTARA SYARIAH',
  'description': 'BPD SUMATERA UTARA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '117',
  'name': 'BPD SUMATERA UTARA',
  'description': 'BPD SUMATERA UTARA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '118',
  'name': 'BPD SUMATERA BARAT SYARIAH',
  'description': 'BPD SUMATERA BARAT SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '118',
  'name': 'BPD SUMATERA BARAT',
  'description': 'BPD SUMATERA BARAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '119',
  'name': 'BPD RIAU',
  'description': 'BPD RIAU',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '119',
  'name': 'BPD RIAU SYARIAH',
  'description': 'BPD RIAU SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '120',
  'name': 'BPD SUMSEL dan BABEL',
  'description': 'BPD SUMSEL dan BABEL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '120',
  'name': 'BPD SUMSEL dan BABEL SYARIAH',
  'description': 'BPD SUMSEL dan BABEL SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '121',
  'name': 'BPD LAMPUNG',
  'description': 'BPD LAMPUNG',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '122',
  'name': 'BPD KALIMANTAN SELATAN SYARIAH',
  'description': 'BPD KALIMANTAN SELATAN SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '122',
  'name': 'BPD KALIMANTAN SELATAN',
  'description': 'BPD KALIMANTAN SELATAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '123',
  'name': 'BPD KALIMANTAN BARAT SYARIAH',
  'description': 'BPD KALIMANTAN BARAT SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '123',
  'name': 'BPD KALIMANTAN BARAT',
  'description': 'BPD KALIMANTAN BARAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '124',
  'name': 'BPD KALIMANTAN TIMUR',
  'description': 'BPD KALIMANTAN TIMUR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '124',
  'name': 'BPD KALIMANTAN TIMUR SYARIAH',
  'description': 'BPD KALIMANTAN TIMUR SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '125',
  'name': 'BPD KALIMANTAN TENGAH',
  'description': 'BPD KALIMANTAN TENGAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '126',
  'name': 'BPD SULAWESI SELATAN',
  'description': 'BPD SULAWESI SELATAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '126',
  'name': 'BPD SULAWESI SELATAN SYARIAH',
  'description': 'BPD SULAWESI SELATAN SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '127',
  'name': 'BPD SULAWESI UTARA',
  'description': 'BPD SULAWESI UTARA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '128',
  'name': 'BPD NUSA TENGGARA BARAT SYARIAH',
  'description': 'BPD NUSA TENGGARA BARAT SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '128',
  'name': 'BPD NUSA TENGGARA BARAT',
  'description': 'BPD NUSA TENGGARA BARAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '129',
  'name': 'BPD BALI',
  'description': 'BPD BALI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '130',
  'name': 'BPD NUSA TENGGARA TIMUR',
  'description': 'BPD NUSA TENGGARA TIMUR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '131',
  'name': 'BPD MALUKU',
  'description': 'BPD MALUKU',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '132',
  'name': 'BPD PAPUA',
  'description': 'BPD PAPUA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '133',
  'name': 'BPD BENGKULU',
  'description': 'BPD BENGKULU',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '134',
  'name': 'BPD SULAWESI TENGAH',
  'description': 'BPD SULAWESI TENGAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '135',
  'name': 'BPD SULAWESI TENGGARA',
  'description': 'BPD SULAWESI TENGGARA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '145',
  'name': 'BANK NUSANTARA PARAHYANGAN',
  'description': 'BANK NUSANTARA PARAHYANGAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '146',
  'name': 'BANK SWADESI',
  'description': 'BANK SWADESI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '147',
  'name': 'BANK MUAMALAT INDONESIA',
  'description': 'BANK MUAMALAT INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '151',
  'name': 'BANK MESTIKA DHARMA',
  'description': 'BANK MESTIKA DHARMA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '152',
  'name': 'BANK METRO EXPRESS',
  'description': 'BANK METRO EXPRESS',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '153',
  'name': 'BANK SINARMAS',
  'description': 'BANK SINARMAS',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '153',
  'name': 'BANK SINARMAS SYARIAH',
  'description': 'BANK SINARMAS SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '157',
  'name': 'BANK MASPION INDONESIA',
  'description': 'BANK MASPION INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '161',
  'name': 'BANK GANESHA',
  'description': 'BANK GANESHA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '164',
  'name': 'BANK ICBC INDONESIA',
  'description': 'BANK ICBC INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '167',
  'name': 'BANK KESAWAN',
  'description': 'BANK KESAWAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '200',
  'name': 'BANK TABUNGAN NEGARA',
  'description': 'BANK TABUNGAN NEGARA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '200',
  'name': 'BANK TABUNGAN NEGARA SYARIAH',
  'description': 'BANK TABUNGAN NEGARA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '212',
  'name': 'BANK HIMPUNAN SAUDARA 1906',
  'description': 'BANK HIMPUNAN SAUDARA 1906',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '213',
  'name': 'BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH',
  'description': 'BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '213',
  'name': 'BANK TABUNGAN PENSIUNAN NASIONAL',
  'description': 'BANK TABUNGAN PENSIUNAN NASIONAL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '385',
  'name': 'BANK INDONESIA',
  'description': 'BANK INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '405',
  'name': 'BANK VICTORIA SYARIAH',
  'description': 'BANK VICTORIA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '422',
  'name': 'BANK RAKYAT INDONESIA SYARIAH',
  'description': 'BANK RAKYAT INDONESIA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '425',
  'name': 'BPD JABAR BANTEN SYARIAH',
  'description': 'BPD JABAR BANTEN SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '426',
  'name': 'BANK MEGA',
  'description': 'BANK MEGA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '427',
  'name': 'BANK NEGARA INDONESIA SYARIAH',
  'description': 'BANK NEGARA INDONESIA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '441',
  'name': 'BANK BUKOPIN',
  'description': 'BANK BUKOPIN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '451',
  'name': 'BANK MANDIRI SYARIAH',
  'description': 'BANK MANDIRI SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '459',
  'name': 'BANK BISNIS INTERNASIONAL',
  'description': 'BANK BISNIS INTERNASIONAL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '466',
  'name': 'BANK ANDARA',
  'description': 'BANK ANDARA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '472',
  'name': 'BANK JASA JAKARTA',
  'description': 'BANK JASA JAKARTA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '484',
  'name': 'BANK HANA',
  'description': 'BANK HANA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '485',
  'name': 'BANK ICB BUMIPUTERA',
  'description': 'BANK ICB BUMIPUTERA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '490',
  'name': 'BANK YUDHA BHAKTI',
  'description': 'BANK YUDHA BHAKTI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '491',
  'name': 'BANK MITRA NIAGA',
  'description': 'BANK MITRA NIAGA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '494',
  'name': 'BANK AGRONIAGA',
  'description': 'BANK AGRONIAGA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '498',
  'name': 'BANK SBI INDONESIA',
  'description': 'BANK SBI INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '501',
  'name': 'BANK ROYAL INDONESIA',
  'description': 'BANK ROYAL INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '503',
  'name': 'BANK NATIONAL NOBU',
  'description': 'BANK NATIONAL NOBU',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '506',
  'name': 'BANK MEGA SYARIAH',
  'description': 'BANK MEGA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '513',
  'name': 'BANK INA PERDANA',
  'description': 'BANK INA PERDANA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '517',
  'name': 'BANK PANIN SYARIAH',
  'description': 'BANK PANIN SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '520',
  'name': 'PRIMA MASTER BANK',
  'description': 'PRIMA MASTER BANK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '521',
  'name': 'BANK BUKOPIN SYARIAH',
  'description': 'BANK BUKOPIN SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '523',
  'name': 'DIPO INTERNASIONAL BANK',
  'description': 'DIPO INTERNASIONAL BANK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '525',
  'name': 'BANK BARCLAYS INDONESIA',
  'description': 'BANK BARCLAYS INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '526',
  'name': 'LIMAN INTERNASIONAL BANK',
  'description': 'LIMAN INTERNASIONAL BANK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '531',
  'name': 'ANGLOMAS INTERNATIONAL BANK',
  'description': 'ANGLOMAS INTERNATIONAL BANK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '535',
  'name': 'BANK KESEJAHTERAAN EKONOMI',
  'description': 'BANK KESEJAHTERAAN EKONOMI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '536',
  'name': 'BANK CENTRAL ASIA SYARIAH',
  'description': 'BANK CENTRAL ASIA SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '542',
  'name': 'BANK ARTOS INDONESIA',
  'description': 'BANK ARTOS INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '547',
  'name': 'BANK SAHABAT PURBA DANARTA',
  'description': 'BANK SAHABAT PURBA DANARTA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '548',
  'name': 'BANK MULTI ARTA SENTOSA',
  'description': 'BANK MULTI ARTA SENTOSA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '553',
  'name': 'BANK MAYORA',
  'description': 'BANK MAYORA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '555',
  'name': 'BANK INDEX SELINDO',
  'description': 'BANK INDEX SELINDO',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '558',
  'name': 'BANK PUNDI INDONESIA',
  'description': 'BANK PUNDI INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '559',
  'name': 'CENTRATAMA NASIONAL BANK',
  'description': 'CENTRATAMA NASIONAL BANK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '562',
  'name': 'BANK FAMA INTERNATIONAL',
  'description': 'BANK FAMA INTERNATIONAL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '564',
  'name': 'BANK SINAR HARAPAN BALI',
  'description': 'BANK SINAR HARAPAN BALI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '566',
  'name': 'BANK VICTORIA INTERNATIONAL',
  'description': 'BANK VICTORIA INTERNATIONAL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '567',
  'name': 'BANK HARDA INTERNASIONAL',
  'description': 'BANK HARDA INTERNASIONAL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '945',
  'name': 'BANK AGRIS',
  'description': 'BANK AGRIS',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '947',
  'name': 'BANK MAYBANK SYARIAH',
  'description': 'BANK MAYBANK SYARIAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '949',
  'name': 'BANK CHINATRUST INDONESIA',
  'description': 'BANK CHINATRUST INDONESIA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'},
 {'reference_slug': 'referensi-bank',
  'reference_name': 'Referensi Bank',
  'code': '950',
  'name': 'BANK COMMONWEALTH',
  'description': 'BANK COMMONWEALTH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-bank.md'}]
