"""Seeder master data CEISA untuk referensi jenis transaksi perdagangan.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_JENIS_TRANSAKSI_PERDAGANGAN_CODES = [{'reference_slug': 'referensi-jenis-transaksi-perdagangan',
  'reference_name': 'Referensi Jenis Transaksi Perdagangan',
  'code': 'IMB',
  'name': 'Transaksi Perdagangan Dengan Imbal Dagang',
  'description': 'Transaksi Perdagangan Dengan Imbal Dagang',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-transaksi-perdagangan',
  'reference_name': 'Referensi Jenis Transaksi Perdagangan',
  'code': 'IOA',
  'name': 'Pembayaran Dilakukan Dengan Interoffice Account',
  'description': 'Pembayaran Dilakukan Dengan Interoffice Account',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-transaksi-perdagangan',
  'reference_name': 'Referensi Jenis Transaksi Perdagangan',
  'code': 'KMD',
  'name': 'Pembayaran Kemudian',
  'description': 'Pembayaran Kemudian',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-transaksi-perdagangan',
  'reference_name': 'Referensi Jenis Transaksi Perdagangan',
  'code': 'KON',
  'name': 'Pembayaran Dilakukan Dengan Konsinyasi',
  'description': 'Pembayaran Dilakukan Dengan Konsinyasi',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-transaksi-perdagangan',
  'reference_name': 'Referensi Jenis Transaksi Perdagangan',
  'code': 'LAI',
  'name': 'Transaksi Perdagangan Atau Cara Pembayaran Lainnya',
  'description': 'Transaksi Perdagangan Atau Cara Pembayaran Lainnya',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-transaksi-perdagangan',
  'reference_name': 'Referensi Jenis Transaksi Perdagangan',
  'code': 'PMK',
  'name': 'Pembayaran Dilakukan Dimuka',
  'description': 'Pembayaran Dilakukan Dimuka',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-transaksi-perdagangan',
  'reference_name': 'Referensi Jenis Transaksi Perdagangan',
  'code': 'RLC',
  'name': 'Pembayaran Dengan Red Clause Letter Of Credit',
  'description': 'Pembayaran Dengan Red Clause Letter Of Credit',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-transaksi-perdagangan',
  'reference_name': 'Referensi Jenis Transaksi Perdagangan',
  'code': 'SLC',
  'name': 'Pembayaran Dengan Sight Letter Of Credit',
  'description': 'Pembayaran Dengan Sight Letter Of Credit',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-transaksi-perdagangan',
  'reference_name': 'Referensi Jenis Transaksi Perdagangan',
  'code': 'ULC',
  'name': 'Pembayaran Dengan Usance Letter Of Credit',
  'description': 'Pembayaran Dengan Usance Letter Of Credit',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-transaksi-perdagangan',
  'reference_name': 'Referensi Jenis Transaksi Perdagangan',
  'code': 'WSI',
  'name': 'Pembayaran Dilakukan Dengan Wesel Inkaso',
  'description': 'Pembayaran Dilakukan Dengan Wesel Inkaso',
  'is_active': True}]
