"""Seeder master data CEISA untuk referensi cara angkut.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_CARA_ANGKUT_CODES = [{'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '1',
  'name': 'LAUT',
  'description': 'LAUT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '2',
  'name': 'KERETA API',
  'description': 'KERETA API',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '3',
  'name': 'DARAT',
  'description': 'DARAT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '4',
  'name': 'UDARA',
  'description': 'UDARA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '5',
  'name': 'POS',
  'description': 'POS',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '6',
  'name': 'MULTIMODA',
  'description': 'MULTIMODA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '7',
  'name': 'INSTALASI / PIPA',
  'description': 'INSTALASI / PIPA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '8',
  'name': 'PERAIRAN',
  'description': 'PERAIRAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '9',
  'name': 'LAINNYA',
  'description': 'LAINNYA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '10',
  'name': 'INSTALASI',
  'description': 'INSTALASI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '11',
  'name': 'PIPA',
  'description': 'PIPA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'},
 {'reference_slug': 'referensi-cara-angkut',
  'reference_name': 'Referensi Cara Angkut',
  'code': '12',
  'name': 'TRANSMISI',
  'description': 'TRANSMISI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-angkut.md'}]
