"""Seeder master data CEISA untuk referensi fasilitas tarif.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_FASILITAS_TARIF_CODES = [{'reference_slug': 'referensi-fasilitas-tarif',
  'reference_name': 'Referensi Fasilitas Tarif',
  'code': '1',
  'name': 'DIBAYAR',
  'description': 'DIBAYAR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas-tarif.md'},
 {'reference_slug': 'referensi-fasilitas-tarif',
  'reference_name': 'Referensi Fasilitas Tarif',
  'code': '2',
  'name': 'DITANGGUNG PEMERINTAH',
  'description': 'DITANGGUNG PEMERINTAH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas-tarif.md'},
 {'reference_slug': 'referensi-fasilitas-tarif',
  'reference_name': 'Referensi Fasilitas Tarif',
  'code': '3',
  'name': 'DITANGGUHKAN',
  'description': 'DITANGGUHKAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas-tarif.md'},
 {'reference_slug': 'referensi-fasilitas-tarif',
  'reference_name': 'Referensi Fasilitas Tarif',
  'code': '4',
  'name': 'BERKALA',
  'description': 'BERKALA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas-tarif.md'},
 {'reference_slug': 'referensi-fasilitas-tarif',
  'reference_name': 'Referensi Fasilitas Tarif',
  'code': '5',
  'name': 'DIBEBASKAN',
  'description': 'DIBEBASKAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas-tarif.md'},
 {'reference_slug': 'referensi-fasilitas-tarif',
  'reference_name': 'Referensi Fasilitas Tarif',
  'code': '6',
  'name': 'TIDAK DIPUNGUT',
  'description': 'TIDAK DIPUNGUT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas-tarif.md'},
 {'reference_slug': 'referensi-fasilitas-tarif',
  'reference_name': 'Referensi Fasilitas Tarif',
  'code': '7',
  'name': 'SUDAH DILUNASI',
  'description': 'SUDAH DILUNASI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas-tarif.md'},
 {'reference_slug': 'referensi-fasilitas-tarif',
  'reference_name': 'Referensi Fasilitas Tarif',
  'code': '8',
  'name': 'DIJAMINKAN',
  'description': 'DIJAMINKAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas-tarif.md'},
 {'reference_slug': 'referensi-fasilitas-tarif',
  'reference_name': 'Referensi Fasilitas Tarif',
  'code': '9',
  'name': 'DITUNDA',
  'description': 'DITUNDA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas-tarif.md'}]
