"""Seeder master data CEISA untuk referensi entitas.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_ENTITAS_CODES = [{'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '1',
  'name': 'IMPORTIR',
  'description': 'IMPORTIR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '2',
  'name': 'EKSPORTIR',
  'description': 'EKSPORTIR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '3',
  'name': 'PENGUSAHA',
  'description': 'PENGUSAHA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '4',
  'name': 'PPJK',
  'description': 'PPJK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '5',
  'name': 'PEMASOK',
  'description': 'PEMASOK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '6',
  'name': 'PEMBELI',
  'description': 'PEMBELI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '7',
  'name': 'PEMILIK',
  'description': 'PEMILIK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '8',
  'name': 'PENERIMA',
  'description': 'PENERIMA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '9',
  'name': 'PENGIRIM',
  'description': 'PENGIRIM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '10',
  'name': 'PENJUAL',
  'description': 'PENJUAL',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '11',
  'name': 'PEMUSATAN',
  'description': 'PEMUSATAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '12',
  'name': 'PENANDATANGAN',
  'description': 'PENANDATANGAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '13',
  'name': 'VENDOR',
  'description': 'VENDOR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '21',
  'name': 'PENGANGKUT',
  'description': 'PENGANGKUT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '22',
  'name': 'AGEN PENGANGKUT',
  'description': 'AGEN PENGANGKUT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'},
 {'reference_slug': 'referensi-entitas',
  'reference_name': 'Referensi Entitas',
  'code': '23',
  'name': 'KONSOLIDATOR',
  'description': 'KONSOLIDATOR',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-entitas.md'}]
