"""Seeder master data CEISA untuk referensi incoterm.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_INCOTERM_CODES = [{'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'CFR',
  'name': 'Cost and Freight',
  'description': 'Cost and Freight',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'CIF',
  'name': 'Cost, Insurance and Freight',
  'description': 'Cost, Insurance and Freight',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'CIP',
  'name': 'Carriage and Insurance Paid to',
  'description': 'Carriage and Insurance Paid to',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'CPT',
  'name': 'Carriage Paid To',
  'description': 'Carriage Paid To',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'DAF',
  'name': 'Delivered At Frontier',
  'description': 'Delivered At Frontier',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'DAP',
  'name': 'Delivered At Place',
  'description': 'Delivered At Place',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'DAT',
  'name': 'Delivered At Terminal',
  'description': 'Delivered At Terminal',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'DDP',
  'name': 'Delivered Duty Paid',
  'description': 'Delivered Duty Paid',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'DDU',
  'name': 'Delivered Duty Unpaid',
  'description': 'Delivered Duty Unpaid',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'DEQ',
  'name': 'Delivered Ex Quay',
  'description': 'Delivered Ex Quay',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'DES',
  'name': 'Delivered Ex Ship',
  'description': 'Delivered Ex Ship',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'EXW',
  'name': 'Ex Works',
  'description': 'Ex Works',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'FAS',
  'name': 'Free Alongside Ship',
  'description': 'Free Alongside Ship',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'FCA',
  'name': 'Free Carrier',
  'description': 'Free Carrier',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'FOB',
  'name': 'Free on Board',
  'description': 'Free on Board',
  'is_active': True},
 {'reference_slug': 'referensi-incoterm',
  'reference_name': 'Referensi Incoterm',
  'code': 'LAN',
  'name': 'LAINNYA',
  'description': 'LAINNYA',
  'is_active': True}]
