"""Seeder master data CEISA untuk referensi valuta.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_VALUTA_CODES = [{'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ADP',
  'name': 'Andorran Peseta',
  'description': 'Andorran Peseta',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'AED',
  'name': 'UAE Dirham',
  'description': 'UAE Dirham',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'AFA',
  'name': 'Afghani',
  'description': 'Afghani',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'AFN',
  'name': 'Afghani',
  'description': 'Afghani',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ALL',
  'name': 'Lek',
  'description': 'Lek',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'AMD',
  'name': 'Armenian Dram',
  'description': 'Armenian Dram',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ANG',
  'name': 'Netherlands Antillian Guilder',
  'description': 'Netherlands Antillian Guilder',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'AOA',
  'name': 'Kwanza',
  'description': 'Kwanza',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'AON',
  'name': 'New Kwanza',
  'description': 'New Kwanza',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ARS',
  'name': 'Argentina Peso',
  'description': 'Argentina Peso',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ATS',
  'name': 'Schilling',
  'description': 'Schilling',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'AUD',
  'name': 'Australian Dollar',
  'description': 'Australian Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'AWG',
  'name': 'Aruban Guilder',
  'description': 'Aruban Guilder',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'AZM',
  'name': 'Azerbaijanian Manat',
  'description': 'Azerbaijanian Manat',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'AZN',
  'name': 'Azerbaijanian Manat',
  'description': 'Azerbaijanian Manat',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BAM',
  'name': 'Convertible Marks',
  'description': 'Convertible Marks',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BBD',
  'name': 'Barbados Dollar',
  'description': 'Barbados Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BDT',
  'name': 'Taka',
  'description': 'Taka',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BEF',
  'name': 'Belgian Franc',
  'description': 'Belgian Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BGL',
  'name': 'Lev',
  'description': 'Lev',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BGN',
  'name': 'Bulgarian Lev',
  'description': 'Bulgarian Lev',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BHD',
  'name': 'Bahraini Dinar',
  'description': 'Bahraini Dinar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BIF',
  'name': 'Burundi Franc',
  'description': 'Burundi Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BMD',
  'name': 'Bermudian Dollar',
  'description': 'Bermudian Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BND',
  'name': 'Brunei Dollar',
  'description': 'Brunei Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BOB',
  'name': 'Boliaiano',
  'description': 'Boliaiano',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BOV',
  'name': 'Mvdol',
  'description': 'Mvdol',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BRL',
  'name': 'Brazilian Real',
  'description': 'Brazilian Real',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BSD',
  'name': 'Bahamian Dollar',
  'description': 'Bahamian Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BTN',
  'name': 'Ngultrum',
  'description': 'Ngultrum',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BWP',
  'name': 'Pula',
  'description': 'Pula',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BYB',
  'name': 'Belarussian Ruble',
  'description': 'Belarussian Ruble',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BYR',
  'name': 'Belarussian Ruble',
  'description': 'Belarussian Ruble',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'BZD',
  'name': 'Belize Dollar',
  'description': 'Belize Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CAD',
  'name': 'Canadian Dollar',
  'description': 'Canadian Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CDF',
  'name': 'Congolese Franc',
  'description': 'Congolese Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CHE',
  'name': 'WIR Euro',
  'description': 'WIR Euro',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CHF',
  'name': 'Swiss Franc',
  'description': 'Swiss Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CHW',
  'name': 'WIR Franc',
  'description': 'WIR Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CLF',
  'name': 'Unidades de fomento',
  'description': 'Unidades de fomento',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CLP',
  'name': 'Chilean Peso',
  'description': 'Chilean Peso',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CNY',
  'name': 'Yuan Renminbi',
  'description': 'Yuan Renminbi',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'COP',
  'name': 'Colombian Peso',
  'description': 'Colombian Peso',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'COU',
  'name': 'Unidad de Valor Real',
  'description': 'Unidad de Valor Real',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CRC',
  'name': 'Costa Rican Colon',
  'description': 'Costa Rican Colon',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CUC',
  'name': 'Peso Convertible',
  'description': 'Peso Convertible',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CUP',
  'name': 'Cuban Peso',
  'description': 'Cuban Peso',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CVE',
  'name': 'Cape Verde Escudo',
  'description': 'Cape Verde Escudo',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CYP',
  'name': 'Cyprus Pound',
  'description': 'Cyprus Pound',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'CZK',
  'name': 'Czech Koruna',
  'description': 'Czech Koruna',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'DEM',
  'name': 'Deustche Mark',
  'description': 'Deustche Mark',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'DJF',
  'name': 'Djibouti Franc',
  'description': 'Djibouti Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'DKK',
  'name': 'Danish Krone',
  'description': 'Danish Krone',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'DOP',
  'name': 'Domincan Peso',
  'description': 'Domincan Peso',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'DZD',
  'name': 'Algerian Dinar',
  'description': 'Algerian Dinar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ECS',
  'name': 'Sucre',
  'description': 'Sucre',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'EEK',
  'name': 'Kroon',
  'description': 'Kroon',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'EGP',
  'name': 'Egyptian Pound',
  'description': 'Egyptian Pound',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ERN',
  'name': 'Nakfa',
  'description': 'Nakfa',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ESP',
  'name': 'Spainish peseta',
  'description': 'Spainish peseta',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ETB',
  'name': 'Ethiopian Birr',
  'description': 'Ethiopian Birr',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'FIM',
  'name': 'Markka',
  'description': 'Markka',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'FJD',
  'name': 'Fiji Dollar',
  'description': 'Fiji Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'FKP',
  'name': 'Falkland Islands Pound',
  'description': 'Falkland Islands Pound',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'FRF',
  'name': 'Franch Franc',
  'description': 'Franch Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GBP',
  'name': 'Pound Sterling',
  'description': 'Pound Sterling',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GEK',
  'name': 'Georgian Coupon',
  'description': 'Georgian Coupon',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GEL',
  'name': 'Lari',
  'description': 'Lari',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GHC',
  'name': 'Cedi',
  'description': 'Cedi',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GHS',
  'name': 'Cedi',
  'description': 'Cedi',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GIP',
  'name': 'Gibraltar Pound',
  'description': 'Gibraltar Pound',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GMD',
  'name': 'Dalasi',
  'description': 'Dalasi',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GNF',
  'name': 'Guinea Franc',
  'description': 'Guinea Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GRD',
  'name': 'Drachma',
  'description': 'Drachma',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GTQ',
  'name': 'Quetzal',
  'description': 'Quetzal',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GWP',
  'name': 'Guinea-Bissau Peso',
  'description': 'Guinea-Bissau Peso',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'GYD',
  'name': 'Guyana Dollar',
  'description': 'Guyana Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'HKD',
  'name': 'Hong Kong Dollar',
  'description': 'Hong Kong Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'HNL',
  'name': 'Lempira',
  'description': 'Lempira',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'HRD',
  'name': 'Croatian Dinar',
  'description': 'Croatian Dinar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'HRK',
  'name': 'Kuna',
  'description': 'Kuna',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'HTG',
  'name': 'Gourde',
  'description': 'Gourde',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'HUF',
  'name': 'Forint',
  'description': 'Forint',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'IDR',
  'name': 'Rupiah',
  'description': 'Rupiah',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'IEP',
  'name': 'Irish Pound',
  'description': 'Irish Pound',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ILS',
  'name': 'Shekel',
  'description': 'Shekel',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'INR',
  'name': 'Indian Rupee',
  'description': 'Indian Rupee',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'IQD',
  'name': 'Iraqi Dinar',
  'description': 'Iraqi Dinar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'IRR',
  'name': 'Iranian Rial',
  'description': 'Iranian Rial',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ISK',
  'name': 'Iceland Krona',
  'description': 'Iceland Krona',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ITL',
  'name': 'Italian Lira',
  'description': 'Italian Lira',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'JMD',
  'name': 'Jamaican Dollar',
  'description': 'Jamaican Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'JOD',
  'name': 'Jordanian Dinar',
  'description': 'Jordanian Dinar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'JPY',
  'name': 'Yen',
  'description': 'Yen',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'KES',
  'name': 'Kenyan Shilling',
  'description': 'Kenyan Shilling',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'KGS',
  'name': 'Som',
  'description': 'Som',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'KHR',
  'name': 'Riel',
  'description': 'Riel',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'KMF',
  'name': 'Comoro Franc',
  'description': 'Comoro Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'KPW',
  'name': 'North Korean Won',
  'description': 'North Korean Won',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'KRW',
  'name': 'Won',
  'description': 'Won',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'KWD',
  'name': 'Kuwauti Dinar',
  'description': 'Kuwauti Dinar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'KYD',
  'name': 'Cayman Islands Dollar',
  'description': 'Cayman Islands Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'KZT',
  'name': 'Tenge',
  'description': 'Tenge',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'LAK',
  'name': 'Kip',
  'description': 'Kip',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'LBP',
  'name': 'Lebanese Pound',
  'description': 'Lebanese Pound',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'LKR',
  'name': 'Sri Langka Rupee',
  'description': 'Sri Langka Rupee',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'LRD',
  'name': 'Liberian Dollar',
  'description': 'Liberian Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'LSL',
  'name': 'Loli',
  'description': 'Loli',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'LTL',
  'name': 'Lithuanian Litas',
  'description': 'Lithuanian Litas',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'LUF',
  'name': 'Luxembourg Franc',
  'description': 'Luxembourg Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'LVL',
  'name': 'Latvian Lats#',
  'description': 'Latvian Lats#',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'LVR',
  'name': 'Latvian Ruble',
  'description': 'Latvian Ruble',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'LYD',
  'name': 'Libyan Dinar',
  'description': 'Libyan Dinar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MAD',
  'name': 'Moroccoan Dirham',
  'description': 'Moroccoan Dirham',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MDL',
  'name': 'Moldovan Leu',
  'description': 'Moldovan Leu',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MGA',
  'name': 'Malagasy Ariary',
  'description': 'Malagasy Ariary',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MGF',
  'name': 'Malagasy Franc',
  'description': 'Malagasy Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MKD',
  'name': 'Denar',
  'description': 'Denar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MMK',
  'name': 'Kyat',
  'description': 'Kyat',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MNT',
  'name': 'Tugrik',
  'description': 'Tugrik',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MOP',
  'name': 'Pataca',
  'description': 'Pataca',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MRO',
  'name': 'Ouguiya',
  'description': 'Ouguiya',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MTL',
  'name': 'Mallese Lira',
  'description': 'Mallese Lira',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MUR',
  'name': 'Mauritius Pupee',
  'description': 'Mauritius Pupee',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MVR',
  'name': 'Rufiyaa',
  'description': 'Rufiyaa',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MWK',
  'name': 'Kwacha',
  'description': 'Kwacha',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MXN',
  'name': 'Mexican Nuevo Peso',
  'description': 'Mexican Nuevo Peso',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MXV',
  'name': 'Mexican Unidad de Inversion (UDI)',
  'description': 'Mexican Unidad de Inversion (UDI)',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MYR',
  'name': 'Malaysian Ringgit',
  'description': 'Malaysian Ringgit',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MZM',
  'name': 'Metical',
  'description': 'Metical',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'MZN',
  'name': 'Metical',
  'description': 'Metical',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'NAD',
  'name': 'Namibia Dollar',
  'description': 'Namibia Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'NGN',
  'name': 'Naira',
  'description': 'Naira',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'NIO',
  'name': 'Cordoba Oro',
  'description': 'Cordoba Oro',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'NLG',
  'name': 'Netherlands Guilder',
  'description': 'Netherlands Guilder',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'NOK',
  'name': 'Norwegian Krone',
  'description': 'Norwegian Krone',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'NPR',
  'name': 'Nepalese Rupee',
  'description': 'Nepalese Rupee',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'NZD',
  'name': 'New Zealand Dollar',
  'description': 'New Zealand Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'OMR',
  'name': 'Rial Omani',
  'description': 'Rial Omani',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'PAB',
  'name': 'Balboa/US Dollar',
  'description': 'Balboa/US Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'PEN',
  'name': 'Nuevo Sol',
  'description': 'Nuevo Sol',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'PGK',
  'name': 'Kina',
  'description': 'Kina',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'PHP',
  'name': 'Philippines Peso',
  'description': 'Philippines Peso',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'PKR',
  'name': 'Pakistan Rupee',
  'description': 'Pakistan Rupee',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'PLN',
  'name': 'Zloty',
  'description': 'Zloty',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'PLZ',
  'name': 'Zloty',
  'description': 'Zloty',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'PTE',
  'name': 'Portuguese Escudo',
  'description': 'Portuguese Escudo',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'PYG',
  'name': 'Guarani',
  'description': 'Guarani',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'QAR',
  'name': 'Qatari Rial',
  'description': 'Qatari Rial',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ROL',
  'name': 'Leu',
  'description': 'Leu',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'RON',
  'name': 'New Leu',
  'description': 'New Leu',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'RSD',
  'name': 'Serbian Dinar',
  'description': 'Serbian Dinar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'RUB',
  'name': 'Russian Ruble',
  'description': 'Russian Ruble',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'RUR',
  'name': 'Russian Ruble',
  'description': 'Russian Ruble',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'RWF',
  'name': 'Rwanda Franc',
  'description': 'Rwanda Franc',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SAR',
  'name': 'Saudi Riyal',
  'description': 'Saudi Riyal',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SBD',
  'name': 'Solomon Islands Dollar',
  'description': 'Solomon Islands Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SCR',
  'name': 'Seychelles Rupee',
  'description': 'Seychelles Rupee',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SDD',
  'name': 'Sudanase Dinar',
  'description': 'Sudanase Dinar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SDG',
  'name': 'Sudanese Pound',
  'description': 'Sudanese Pound',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SDP',
  'name': 'Sudanese Pound',
  'description': 'Sudanese Pound',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SEK',
  'name': 'Swedish Krone',
  'description': 'Swedish Krone',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SGD',
  'name': 'Singapore Dollar',
  'description': 'Singapore Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SHP',
  'name': 'St. Helena Pound',
  'description': 'St. Helena Pound',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SIT',
  'name': 'Tolar',
  'description': 'Tolar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SKK',
  'name': 'Slovak Koruna',
  'description': 'Slovak Koruna',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SLL',
  'name': 'Leone',
  'description': 'Leone',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SOS',
  'name': 'Somalia shilling',
  'description': 'Somalia shilling',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SRD',
  'name': 'Surinam Dollar',
  'description': 'Surinam Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SRG',
  'name': 'Surinam Guilder',
  'description': 'Surinam Guilder',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'STD',
  'name': 'Dobra',
  'description': 'Dobra',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SVC',
  'name': 'El Salvador Colon',
  'description': 'El Salvador Colon',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SYP',
  'name': 'Syrian Pound',
  'description': 'Syrian Pound',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'SZL',
  'name': 'Lilangeni',
  'description': 'Lilangeni',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'THB',
  'name': 'Baht',
  'description': 'Baht',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'TJS',
  'name': 'Somoni',
  'description': 'Somoni',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'TMM',
  'name': 'Manat',
  'description': 'Manat',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'TMT',
  'name': 'Manat',
  'description': 'Manat',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'TND',
  'name': 'Tunisian Dinar',
  'description': 'Tunisian Dinar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'TOP',
  'name': "Pa'anga",
  'description': "Pa'anga",
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'TRL',
  'name': 'Turkish Lira',
  'description': 'Turkish Lira',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'TRY',
  'name': 'Turkish Lira',
  'description': 'Turkish Lira',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'TTD',
  'name': 'Trinidad and Tobago Dollar',
  'description': 'Trinidad and Tobago Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'TWD',
  'name': 'New Taiwan Dollar',
  'description': 'New Taiwan Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'TZS',
  'name': 'Tanzania Shilling',
  'description': 'Tanzania Shilling',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'UAH',
  'name': 'Hryvnia',
  'description': 'Hryvnia',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'UAK',
  'name': 'Karbovanet',
  'description': 'Karbovanet',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'UGX',
  'name': 'Uganda Shilling',
  'description': 'Uganda Shilling',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'USD',
  'name': 'US Dollar',
  'description': 'US Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'UYI',
  'name': 'Uruguay Peso en Unidades Indexadas',
  'description': 'Uruguay Peso en Unidades Indexadas',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'UYU',
  'name': 'Peso Uruguayo',
  'description': 'Peso Uruguayo',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'UZS',
  'name': 'Ubekistan Sum',
  'description': 'Ubekistan Sum',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'VEB',
  'name': 'Bolivar',
  'description': 'Bolivar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'VEF',
  'name': 'Bolivar Fuerte',
  'description': 'Bolivar Fuerte',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'VND',
  'name': 'Dong',
  'description': 'Dong',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'VUV',
  'name': 'Vatu',
  'description': 'Vatu',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'WST',
  'name': 'Tala',
  'description': 'Tala',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'YER',
  'name': 'Yemeni Rial',
  'description': 'Yemeni Rial',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'YUN',
  'name': 'New Yugosslavian',
  'description': 'New Yugosslavian',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ZAL',
  'name': 'Financial Rand',
  'description': 'Financial Rand',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ZAR',
  'name': 'Rand',
  'description': 'Rand',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ZMK',
  'name': 'Kwacha',
  'description': 'Kwacha',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ZWD',
  'name': 'Zimbabwe Dollar',
  'description': 'Zimbabwe Dollar',
  'is_active': True},
 {'reference_slug': 'referensi-valuta',
  'reference_name': 'Referensi Valuta',
  'code': 'ZWL',
  'name': 'Zimbabwe Dollar',
  'description': 'Zimbabwe Dollar',
  'is_active': True}]
