"""Seeder master data CEISA untuk referensi status pengusaha.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_STATUS_PENGUSAHA_CODES = [{'reference_slug': 'referensi-status-pengusaha',
  'reference_name': 'Referensi Status Pengusaha',
  'code': '1',
  'name': 'Koperasi',
  'description': 'Koperasi',
  'is_active': True},
 {'reference_slug': 'referensi-status-pengusaha',
  'reference_name': 'Referensi Status Pengusaha',
  'code': '2',
  'name': 'PMDN (Migas)',
  'description': 'PMDN (Migas)',
  'is_active': True},
 {'reference_slug': 'referensi-status-pengusaha',
  'reference_name': 'Referensi Status Pengusaha',
  'code': '3',
  'name': 'PMDN (Non Migas)',
  'description': 'PMDN (Non Migas)',
  'is_active': True},
 {'reference_slug': 'referensi-status-pengusaha',
  'reference_name': 'Referensi Status Pengusaha',
  'code': '4',
  'name': 'PMA (Migas)',
  'description': 'PMA (Migas)',
  'is_active': True},
 {'reference_slug': 'referensi-status-pengusaha',
  'reference_name': 'Referensi Status Pengusaha',
  'code': '5',
  'name': 'PMA (Non Migas)',
  'description': 'PMA (Non Migas)',
  'is_active': True},
 {'reference_slug': 'referensi-status-pengusaha',
  'reference_name': 'Referensi Status Pengusaha',
  'code': '6',
  'name': 'BUMN',
  'description': 'BUMN',
  'is_active': True},
 {'reference_slug': 'referensi-status-pengusaha',
  'reference_name': 'Referensi Status Pengusaha',
  'code': '7',
  'name': 'BUMD',
  'description': 'BUMD',
  'is_active': True},
 {'reference_slug': 'referensi-status-pengusaha',
  'reference_name': 'Referensi Status Pengusaha',
  'code': '8',
  'name': 'Perorangan',
  'description': 'Perorangan',
  'is_active': True},
 {'reference_slug': 'referensi-status-pengusaha',
  'reference_name': 'Referensi Status Pengusaha',
  'code': '9',
  'name': 'Usaha Kecil, Mikro, dan Menengah',
  'description': 'Usaha Kecil, Mikro, dan Menengah',
  'is_active': True},
 {'reference_slug': 'referensi-status-pengusaha',
  'reference_name': 'Referensi Status Pengusaha',
  'code': '10',
  'name': 'Lainnya',
  'description': 'Lainnya',
  'is_active': True}]
