"""Seeder master data CEISA untuk referensi tujuan pemasukan.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_TUJUAN_PEMASUKAN_CODES = [{'reference_slug': 'referensi-tujuan-pemasukan',
  'reference_name': 'Referensi Tujuan Pemasukan',
  'code': '262',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pemasukan',
  'reference_name': 'Referensi Tujuan Pemasukan',
  'code': '262',
  'name': '2',
  'description': '2',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pemasukan',
  'reference_name': 'Referensi Tujuan Pemasukan',
  'code': '262',
  'name': '3',
  'description': '3',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pemasukan',
  'reference_name': 'Referensi Tujuan Pemasukan',
  'code': '262',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pemasukan',
  'reference_name': 'Referensi Tujuan Pemasukan',
  'code': '262',
  'name': '5',
  'description': '5',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pemasukan',
  'reference_name': 'Referensi Tujuan Pemasukan',
  'code': '262',
  'name': '6',
  'description': '6',
  'is_active': True}]
