"""Seeder master data CEISA untuk referensi jenis kemasan.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_JENIS_KEMASAN_CODES = [{'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '1A',
  'name': 'Drum, steel',
  'description': 'Drum, steel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '1B',
  'name': 'Drum, aluminium',
  'description': 'Drum, aluminium',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '1D',
  'name': 'Drum, plywood',
  'description': 'Drum, plywood',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '1F',
  'name': 'Container, flexible',
  'description': 'Container, flexible',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '1G',
  'name': 'Drum, fibre',
  'description': 'Drum, fibre',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '1W',
  'name': 'Drum, wooden',
  'description': 'Drum, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '2C',
  'name': 'Barrel, wooden',
  'description': 'Barrel, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '3A',
  'name': 'Jerrican, steel',
  'description': 'Jerrican, steel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '3H',
  'name': 'Jerrican, plastic',
  'description': 'Jerrican, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '43',
  'name': 'Bag, super bulk',
  'description': 'Bag, super bulk',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '44',
  'name': 'Bag, polybag',
  'description': 'Bag, polybag',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '4A',
  'name': 'Box, steel',
  'description': 'Box, steel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '4B',
  'name': 'Box, aluminium',
  'description': 'Box, aluminium',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '4C',
  'name': 'Box, natural wood',
  'description': 'Box, natural wood',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '4D',
  'name': 'Box, plywood',
  'description': 'Box, plywood',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '4F',
  'name': 'Box, reconstituted wood',
  'description': 'Box, reconstituted wood',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '4G',
  'name': 'Box, fibreboard',
  'description': 'Box, fibreboard',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '4H',
  'name': 'Box, plastic',
  'description': 'Box, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '5H',
  'name': 'Bag, woven plastic',
  'description': 'Bag, woven plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '5L',
  'name': 'Bag, textile',
  'description': 'Bag, textile',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '5M',
  'name': 'Bag, paper',
  'description': 'Bag, paper',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '6H',
  'name': 'Composite packaging, plastic receptacle',
  'description': 'Composite packaging, plastic receptacle',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '6P',
  'name': 'Composite packaging, glass receptacle',
  'description': 'Composite packaging, glass receptacle',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '7A',
  'name': 'Case, car',
  'description': 'Case, car',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '7B',
  'name': 'Case, wooden',
  'description': 'Case, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '8A',
  'name': 'Pallet, wooden',
  'description': 'Pallet, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '8B',
  'name': 'Crate, wooden',
  'description': 'Crate, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': '8C',
  'name': 'Bundle, wooden',
  'description': 'Bundle, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AA',
  'name': 'Intermediate bulk container, rigid plastic',
  'description': 'Intermediate bulk container, rigid plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AB',
  'name': 'Receptacle, fibre',
  'description': 'Receptacle, fibre',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AC',
  'name': 'Receptacle, paper',
  'description': 'Receptacle, paper',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AD',
  'name': 'Receptacle, wooden',
  'description': 'Receptacle, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AE',
  'name': 'Aerosol',
  'description': 'Aerosol',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AF',
  'name': 'Pallet, modular, collars 80cms \\* 60cms',
  'description': 'Pallet, modular, collars 80cms \\* 60cms',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AG',
  'name': 'Pallet, shrinkwrapped',
  'description': 'Pallet, shrinkwrapped',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AH',
  'name': 'Pallet, 100cms \\* 110cms',
  'description': 'Pallet, 100cms \\* 110cms',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AI',
  'name': 'Clamshell',
  'description': 'Clamshell',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AJ',
  'name': 'Cone',
  'description': 'Cone',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AL',
  'name': 'Ball',
  'description': 'Ball',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AM',
  'name': 'Ampoule, non protected',
  'description': 'Ampoule, non protected',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AP',
  'name': 'Ampoule, protected',
  'description': 'Ampoule, protected',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AT',
  'name': 'Atomizer',
  'description': 'Atomizer',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'AV',
  'name': 'Capsule',
  'description': 'Capsule',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'B4',
  'name': 'Belt',
  'description': 'Belt',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BA',
  'name': 'Barrel',
  'description': 'Barrel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BB',
  'name': 'Bobbin',
  'description': 'Bobbin',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BC',
  'name': 'Bottlecrate, bottlerack',
  'description': 'Bottlecrate, bottlerack',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BD',
  'name': 'Board',
  'description': 'Board',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BE',
  'name': 'Bundle',
  'description': 'Bundle',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BF',
  'name': 'Balloon, non-protected',
  'description': 'Balloon, non-protected',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BG',
  'name': 'Bag',
  'description': 'Bag',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BH',
  'name': 'Bunch',
  'description': 'Bunch',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BI',
  'name': 'Bin',
  'description': 'Bin',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BJ',
  'name': 'Bucket',
  'description': 'Bucket',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BK',
  'name': 'Basket',
  'description': 'Basket',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BL',
  'name': 'Bale, compressed',
  'description': 'Bale, compressed',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BM',
  'name': 'Basin',
  'description': 'Basin',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BN',
  'name': 'Bale, non -compressed',
  'description': 'Bale, non -compressed',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BO',
  'name': 'Bottle, non-protected, cylindrical',
  'description': 'Bottle, non-protected, cylindrical',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BP',
  'name': 'Balloon, protected',
  'description': 'Balloon, protected',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BQ',
  'name': 'Bottle, protected cylindrical',
  'description': 'Bottle, protected cylindrical',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BR',
  'name': 'Bar',
  'description': 'Bar',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BS',
  'name': 'Bottle, non-protected, bulbous',
  'description': 'Bottle, non-protected, bulbous',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BT',
  'name': 'Bolt',
  'description': 'Bolt',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BU',
  'name': 'Butt',
  'description': 'Butt',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BV',
  'name': 'Bottle, protected bulbous',
  'description': 'Bottle, protected bulbous',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BW',
  'name': 'Box, for liquids',
  'description': 'Box, for liquids',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BX',
  'name': 'Box',
  'description': 'Box',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BY',
  'name': 'Board, in bundle/bunch/truss',
  'description': 'Board, in bundle/bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'BZ',
  'name': 'Bars, in bundle/bunch/truss',
  'description': 'Bars, in bundle/bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CA',
  'name': 'Can, rectangular',
  'description': 'Can, rectangular',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CB',
  'name': 'Beer crate',
  'description': 'Beer crate',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CC',
  'name': 'Churn',
  'description': 'Churn',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CD',
  'name': 'Can, with handle and spout',
  'description': 'Can, with handle and spout',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CE',
  'name': 'Creel',
  'description': 'Creel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CF',
  'name': 'Coffer',
  'description': 'Coffer',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CG',
  'name': 'Cage',
  'description': 'Cage',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CH',
  'name': 'Chest',
  'description': 'Chest',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CI',
  'name': 'Canister',
  'description': 'Canister',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CJ',
  'name': 'Coffin',
  'description': 'Coffin',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CK',
  'name': 'Cask',
  'description': 'Cask',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CL',
  'name': 'Coil',
  'description': 'Coil',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CM',
  'name': 'Card',
  'description': 'Card',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CN',
  'name': 'Cont,not otherwise specfied as transport equipment',
  'description': 'Cont,not otherwise specfied as transport equipment',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CO',
  'name': 'Carboy, non-protected',
  'description': 'Carboy, non-protected',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CP',
  'name': 'Carboy, protected',
  'description': 'Carboy, protected',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CQ',
  'name': 'Cartridge',
  'description': 'Cartridge',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CR',
  'name': 'Crate',
  'description': 'Crate',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CS',
  'name': 'Case',
  'description': 'Case',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CT',
  'name': 'Carton',
  'description': 'Carton',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CU',
  'name': 'Cup',
  'description': 'Cup',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CV',
  'name': 'Cover',
  'description': 'Cover',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CW',
  'name': 'Cage, roll',
  'description': 'Cage, roll',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CX',
  'name': 'Can, cylindical',
  'description': 'Can, cylindical',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CY',
  'name': 'Cylinder',
  'description': 'Cylinder',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'CZ',
  'name': 'Canvas',
  'description': 'Canvas',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DA',
  'name': 'Crate, multiple layer, plastic',
  'description': 'Crate, multiple layer, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DB',
  'name': 'Crate, multiple layer, wooden',
  'description': 'Crate, multiple layer, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DC',
  'name': 'Crate, multiple layer, cardboard',
  'description': 'Crate, multiple layer, cardboard',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DG',
  'name': 'Cage, Commonwealth Handling Equipment Pool (CHEP)',
  'description': 'Cage, Commonwealth Handling Equipment Pool (CHEP)',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DH',
  'name': 'Box,Commnwealth Hndling Equipmnt Pool/CHEP,Eurobox',
  'description': 'Box,Commnwealth Hndling Equipmnt Pool/CHEP,Eurobox',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DI',
  'name': 'Drum, iron',
  'description': 'Drum, iron',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DJ',
  'name': 'Demijohn, non-protected',
  'description': 'Demijohn, non-protected',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DK',
  'name': 'Crate, bulk, cardboard',
  'description': 'Crate, bulk, cardboard',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DL',
  'name': 'Crate, bulk, plastic',
  'description': 'Crate, bulk, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DM',
  'name': 'Crate, bulk, wooden',
  'description': 'Crate, bulk, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DN',
  'name': 'Dispenser',
  'description': 'Dispenser',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DP',
  'name': 'Demijohn, protected',
  'description': 'Demijohn, protected',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DR',
  'name': 'Drum',
  'description': 'Drum',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DS',
  'name': 'Tray, one layer no cover, plastic',
  'description': 'Tray, one layer no cover, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DT',
  'name': 'Tray, one layer no cover, wooden',
  'description': 'Tray, one layer no cover, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DU',
  'name': 'Tray, one layer no cover, polystyrene',
  'description': 'Tray, one layer no cover, polystyrene',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DV',
  'name': 'Tray, one layer no cover, cardboard',
  'description': 'Tray, one layer no cover, cardboard',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DW',
  'name': 'Tray, two layers no cover, plastic tray',
  'description': 'Tray, two layers no cover, plastic tray',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DX',
  'name': 'Tray, two layers no cover, wooden',
  'description': 'Tray, two layers no cover, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'DY',
  'name': 'Tray, two layers no cover, cardboard',
  'description': 'Tray, two layers no cover, cardboard',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'EC',
  'name': 'Bag, plastic',
  'description': 'Bag, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ED',
  'name': 'Case, with pallet base',
  'description': 'Case, with pallet base',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'EE',
  'name': 'Case, with pallet base, wooden',
  'description': 'Case, with pallet base, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'EF',
  'name': 'Case, with pallet base, cardboard',
  'description': 'Case, with pallet base, cardboard',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'EG',
  'name': 'Case, with pallet base, plastic',
  'description': 'Case, with pallet base, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'EH',
  'name': 'Case, with pallet base, metal',
  'description': 'Case, with pallet base, metal',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'EI',
  'name': 'Case, isothermic',
  'description': 'Case, isothermic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'EN',
  'name': 'Envelope',
  'description': 'Envelope',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FB',
  'name': 'Flexibag',
  'description': 'Flexibag',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FC',
  'name': 'Fruit crate',
  'description': 'Fruit crate',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FD',
  'name': 'Framed crate',
  'description': 'Framed crate',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FE',
  'name': 'Flexitank',
  'description': 'Flexitank',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FI',
  'name': 'Firkin',
  'description': 'Firkin',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FL',
  'name': 'Flask',
  'description': 'Flask',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FO',
  'name': 'Footlocker',
  'description': 'Footlocker',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FP',
  'name': 'Filmpack',
  'description': 'Filmpack',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FR',
  'name': 'Frame',
  'description': 'Frame',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FT',
  'name': 'Foodtainer',
  'description': 'Foodtainer',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FW',
  'name': 'Cart, flatbed',
  'description': 'Cart, flatbed',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'FX',
  'name': 'Bag, flexible container',
  'description': 'Bag, flexible container',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'GB',
  'name': 'Gas bottle',
  'description': 'Gas bottle',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'GI',
  'name': 'Girder',
  'description': 'Girder',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'GL',
  'name': 'Container, gallon',
  'description': 'Container, gallon',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'GR',
  'name': 'Receptacle, glass',
  'description': 'Receptacle, glass',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'GU',
  'name': 'Tray, containing horizontally stacked flat items',
  'description': 'Tray, containing horizontally stacked flat items',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'GY',
  'name': 'Bag, gunny',
  'description': 'Bag, gunny',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'GZ',
  'name': 'Girders, in bundle/bunch/truss',
  'description': 'Girders, in bundle/bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'HA',
  'name': 'Basket, with handle, plastic',
  'description': 'Basket, with handle, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'HB',
  'name': 'Basket, with handle, wooden',
  'description': 'Basket, with handle, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'HC',
  'name': 'Basket, with handle, cardboard',
  'description': 'Basket, with handle, cardboard',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'HG',
  'name': 'Hogshead',
  'description': 'Hogshead',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'HN',
  'name': 'Hanger',
  'description': 'Hanger',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'HR',
  'name': 'Hamper',
  'description': 'Hamper',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'HZ',
  'name': 'bukan kaleng kaleng',
  'description': 'bukan kaleng kaleng',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IA',
  'name': 'Package, display, wooden',
  'description': 'Package, display, wooden',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IB',
  'name': 'Package, display, cardboard',
  'description': 'Package, display, cardboard',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IC',
  'name': 'Package, display, plastic',
  'description': 'Package, display, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ID',
  'name': 'Package, display, metal',
  'description': 'Package, display, metal',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IE',
  'name': 'Package, show',
  'description': 'Package, show',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IF',
  'name': 'Package, flow',
  'description': 'Package, flow',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IG',
  'name': 'Package, paper wrapped',
  'description': 'Package, paper wrapped',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IH',
  'name': 'Drum, plastic',
  'description': 'Drum, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IK',
  'name': 'Package, cardboard, with bottle grip-holes',
  'description': 'Package, cardboard, with bottle grip-holes',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IL',
  'name': 'Tray, rigid, lidded stackable (CEN TS 14482:2002)',
  'description': 'Tray, rigid, lidded stackable (CEN TS 14482:2002)',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IN',
  'name': 'Ingot',
  'description': 'Ingot',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'IZ',
  'name': 'ingots, in bundle/bunch/truss',
  'description': 'ingots, in bundle/bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'JB',
  'name': 'Bag, jumbo',
  'description': 'Bag, jumbo',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'JC',
  'name': 'Jerrican, rectangular',
  'description': 'Jerrican, rectangular',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'JG',
  'name': 'Jug',
  'description': 'Jug',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'JR',
  'name': 'Jar',
  'description': 'Jar',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'JT',
  'name': 'Jutebag',
  'description': 'Jutebag',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'JY',
  'name': 'Jerrican, cylindrical',
  'description': 'Jerrican, cylindrical',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'KG',
  'name': 'Keg',
  'description': 'Keg',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'KI',
  'name': 'Kit',
  'description': 'Kit',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'KR',
  'name': 'karung',
  'description': 'karung',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'LE',
  'name': 'Luggage',
  'description': 'Luggage',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'LG',
  'name': 'Log',
  'description': 'Log',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'LT',
  'name': 'Lot',
  'description': 'Lot',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'LU',
  'name': 'Lug',
  'description': 'Lug',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'LV',
  'name': 'Liftvan',
  'description': 'Liftvan',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'LZ',
  'name': 'Logs, in bundle/bunch/truss',
  'description': 'Logs, in bundle/bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'MA',
  'name': 'Crate, metal',
  'description': 'Crate, metal',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'MB',
  'name': 'Multiply bag',
  'description': 'Multiply bag',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'MC',
  'name': 'milk crate',
  'description': 'milk crate',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ME',
  'name': 'Container, metal',
  'description': 'Container, metal',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'MR',
  'name': 'Receptacle, metal',
  'description': 'Receptacle, metal',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'MS',
  'name': 'Multiwall sack',
  'description': 'Multiwall sack',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'MT',
  'name': 'Mat',
  'description': 'Mat',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'MW',
  'name': 'Receptacle, plastic wrapped',
  'description': 'Receptacle, plastic wrapped',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'MX',
  'name': 'Macth box',
  'description': 'Macth box',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'NA',
  'name': 'Not available',
  'description': 'Not available',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'NE',
  'name': 'Unpacked or unpackaged',
  'description': 'Unpacked or unpackaged',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'NF',
  'name': 'Unpacked or unpackaged, single unit',
  'description': 'Unpacked or unpackaged, single unit',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'NG',
  'name': 'Unpacked or unpackaged, multiple units',
  'description': 'Unpacked or unpackaged, multiple units',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'NS',
  'name': 'Nest',
  'description': 'Nest',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'NT',
  'name': 'Net',
  'description': 'Net',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'NU',
  'name': 'Net, tube, plastic',
  'description': 'Net, tube, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'NV',
  'name': 'Net, tube, textile',
  'description': 'Net, tube, textile',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'OA',
  'name': 'Pallet, CHEP 40 cm x 60 cm',
  'description': 'Pallet, CHEP 40 cm x 60 cm',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'OB',
  'name': 'Pallet, CHEP 80 cm x 120 cm',
  'description': 'Pallet, CHEP 80 cm x 120 cm',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'OC',
  'name': 'Pallet, CHEP 100 cm x 120 cm',
  'description': 'Pallet, CHEP 100 cm x 120 cm',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'OD',
  'name': 'Pallet, AS 4068-1993',
  'description': 'Pallet, AS 4068-1993',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'OE',
  'name': 'Pallet, ISO T11',
  'description': 'Pallet, ISO T11',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'OF',
  'name': 'Platform, unspecified weight or dimension',
  'description': 'Platform, unspecified weight or dimension',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'OK',
  'name': 'Block',
  'description': 'Block',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'OT',
  'name': 'Octabin',
  'description': 'Octabin',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'OU',
  'name': 'Container, outer',
  'description': 'Container, outer',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'P2',
  'name': 'Pan',
  'description': 'Pan',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PA',
  'name': 'Packet',
  'description': 'Packet',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PB',
  'name': 'Pallet, box Combined open-ended box and pallet',
  'description': 'Pallet, box Combined open-ended box and pallet',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PC',
  'name': 'Parcel',
  'description': 'Parcel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PD',
  'name': 'Pallet, modular, collars 80cms \\* 100cms',
  'description': 'Pallet, modular, collars 80cms \\* 100cms',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PE',
  'name': 'Pallet, modular, collars 80cms \\* 120cms',
  'description': 'Pallet, modular, collars 80cms \\* 120cms',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PF',
  'name': 'Pen',
  'description': 'Pen',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PG',
  'name': 'Plate',
  'description': 'Plate',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PH',
  'name': 'Pitcher',
  'description': 'Pitcher',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PI',
  'name': 'Pipe',
  'description': 'Pipe',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PJ',
  'name': 'Punnet',
  'description': 'Punnet',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PK',
  'name': 'Package',
  'description': 'Package',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PL',
  'name': 'Pail',
  'description': 'Pail',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PN',
  'name': 'Plank',
  'description': 'Plank',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PO',
  'name': 'Pouch',
  'description': 'Pouch',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PP',
  'name': 'Piece',
  'description': 'Piece',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PR',
  'name': 'Receptacle, plastic',
  'description': 'Receptacle, plastic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PT',
  'name': 'Pot',
  'description': 'Pot',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PU',
  'name': 'Tray',
  'description': 'Tray',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PV',
  'name': 'Pipes, in bundle/bunch/truss',
  'description': 'Pipes, in bundle/bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PX',
  'name': 'Pallet',
  'description': 'Pallet',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PY',
  'name': 'Plates, in bundle/bunch/truss',
  'description': 'Plates, in bundle/bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'PZ',
  'name': 'Pipes, in bundle/bunch/truss',
  'description': 'Pipes, in bundle/bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QA',
  'name': 'Drum, steel, non-removable head',
  'description': 'Drum, steel, non-removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QB',
  'name': 'Drum, steel, removable head',
  'description': 'Drum, steel, removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QC',
  'name': 'Drum, aluminium, non-removable head',
  'description': 'Drum, aluminium, non-removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QD',
  'name': 'Drum, aluminium, removable head',
  'description': 'Drum, aluminium, removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QF',
  'name': 'Drum, plastic, non-removable head',
  'description': 'Drum, plastic, non-removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QG',
  'name': 'Drum, plastic, removable head',
  'description': 'Drum, plastic, removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QH',
  'name': 'Barrel, wooden, bung type',
  'description': 'Barrel, wooden, bung type',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QJ',
  'name': 'Barrel, wooden, removable head',
  'description': 'Barrel, wooden, removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QK',
  'name': 'Jerrican, steel, non-removable head',
  'description': 'Jerrican, steel, non-removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QL',
  'name': 'Jerrican, steel, removable head',
  'description': 'Jerrican, steel, removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QM',
  'name': 'Jerrican, plastic, non-removable head',
  'description': 'Jerrican, plastic, non-removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QN',
  'name': 'Jerrican, plastic, removable head',
  'description': 'Jerrican, plastic, removable head',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QP',
  'name': 'Box, wooden, natural wood, ordinary',
  'description': 'Box, wooden, natural wood, ordinary',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QQ',
  'name': 'Box, wooden, natural wood, with sift proof walls',
  'description': 'Box, wooden, natural wood, with sift proof walls',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QR',
  'name': 'Box, plastic, expanded',
  'description': 'Box, plastic, expanded',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'QS',
  'name': 'Box, plastic, solid',
  'description': 'Box, plastic, solid',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'RD',
  'name': 'Rod',
  'description': 'Rod',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'RG',
  'name': 'Ring',
  'description': 'Ring',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'RJ',
  'name': 'Rack, clothing hanger',
  'description': 'Rack, clothing hanger',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'RK',
  'name': 'Rack',
  'description': 'Rack',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'RL',
  'name': 'Reel',
  'description': 'Reel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'RO',
  'name': 'Roll',
  'description': 'Roll',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'RT',
  'name': 'Rednet',
  'description': 'Rednet',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'RZ',
  'name': 'Rods, in bundle/ bunch/truss',
  'description': 'Rods, in bundle/ bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SA',
  'name': 'Sack',
  'description': 'Sack',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SB',
  'name': 'Slab',
  'description': 'Slab',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SC',
  'name': 'Shallow crate',
  'description': 'Shallow crate',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SD',
  'name': 'Spindle',
  'description': 'Spindle',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SE',
  'name': 'Sea-chest',
  'description': 'Sea-chest',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SH',
  'name': 'Sachet',
  'description': 'Sachet',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SI',
  'name': 'Skid',
  'description': 'Skid',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SK',
  'name': 'Skeleton case',
  'description': 'Skeleton case',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SL',
  'name': 'Slipsheet',
  'description': 'Slipsheet',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SM',
  'name': 'Sheetmetal',
  'description': 'Sheetmetal',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SO',
  'name': 'Spool',
  'description': 'Spool',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SP',
  'name': 'Sheet, plastic wrapping',
  'description': 'Sheet, plastic wrapping',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SS',
  'name': 'Case, steel',
  'description': 'Case, steel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ST',
  'name': 'Sheet',
  'description': 'Sheet',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SU',
  'name': 'Suitcase',
  'description': 'Suitcase',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SV',
  'name': 'Envelope, steel',
  'description': 'Envelope, steel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SW',
  'name': 'Shrinkwrapped',
  'description': 'Shrinkwrapped',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SX',
  'name': 'Set',
  'description': 'Set',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SY',
  'name': 'Sleeve',
  'description': 'Sleeve',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'SZ',
  'name': 'Sheets, in bundle/bunch/truss',
  'description': 'Sheets, in bundle/bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'T1',
  'name': 'Tablet',
  'description': 'Tablet',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TB',
  'name': 'Tub',
  'description': 'Tub',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TC',
  'name': 'Tea-chest',
  'description': 'Tea-chest',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TD',
  'name': 'Collapsible tube',
  'description': 'Collapsible tube',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TE',
  'name': 'Tyre',
  'description': 'Tyre',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TG',
  'name': 'Tank container, generic',
  'description': 'Tank container, generic',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TI',
  'name': 'Tierce',
  'description': 'Tierce',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TK',
  'name': 'Tank, rectangular',
  'description': 'Tank, rectangular',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TL',
  'name': 'Tub, with lid',
  'description': 'Tub, with lid',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TN',
  'name': 'Tin',
  'description': 'Tin',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TO',
  'name': 'Tun',
  'description': 'Tun',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TP',
  'name': 'Tray',
  'description': 'Tray',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TR',
  'name': 'Trunk',
  'description': 'Trunk',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TS',
  'name': 'Truss',
  'description': 'Truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TT',
  'name': 'Bag, tote',
  'description': 'Bag, tote',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TU',
  'name': 'Tube',
  'description': 'Tube',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TV',
  'name': 'Tube, with nozzle',
  'description': 'Tube, with nozzle',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TW',
  'name': 'Pallet, triwall',
  'description': 'Pallet, triwall',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TY',
  'name': 'Tank, cylindrical',
  'description': 'Tank, cylindrical',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'TZ',
  'name': 'Tubes, in bundle/bunch/truss',
  'description': 'Tubes, in bundle/bunch/truss',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'UC',
  'name': 'Uncaged',
  'description': 'Uncaged',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'UN',
  'name': 'Unpackage',
  'description': 'Unpackage',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VA',
  'name': 'Vat',
  'description': 'Vat',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VG',
  'name': 'Bulk, gas ( at 1031 mbar and 15C )',
  'description': 'Bulk, gas ( at 1031 mbar and 15C )',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VI',
  'name': 'Vial',
  'description': 'Vial',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VK',
  'name': 'Vanpack',
  'description': 'Vanpack',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VL',
  'name': 'Bulk, liquid',
  'description': 'Bulk, liquid',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VN',
  'name': 'Vehicle',
  'description': 'Vehicle',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VO',
  'name': 'Bulk, solid, large particles ("nodules")',
  'description': 'Bulk, solid, large particles ("nodules")',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VP',
  'name': 'Vacuumpacked',
  'description': 'Vacuumpacked',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VQ',
  'name': 'Bulk,liquefied gas (at abnorml temprture/pressure)',
  'description': 'Bulk,liquefied gas (at abnorml temprture/pressure)',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VR',
  'name': 'Bulk, solid, granular particles ("grains")',
  'description': 'Bulk, solid, granular particles ("grains")',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VS',
  'name': 'Bulk, scrap metal',
  'description': 'Bulk, scrap metal',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'VY',
  'name': 'Bulk, solid, fine particles ("powders")',
  'description': 'Bulk, solid, fine particles ("powders")',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WA',
  'name': 'Intermediate bulk container',
  'description': 'Intermediate bulk container',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WB',
  'name': 'Wickerbottle',
  'description': 'Wickerbottle',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WC',
  'name': 'Intermediate bulk container, steel',
  'description': 'Intermediate bulk container, steel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WD',
  'name': 'Intermediate bulk container, aluminium',
  'description': 'Intermediate bulk container, aluminium',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WF',
  'name': 'Intermediate bulk container, metal',
  'description': 'Intermediate bulk container, metal',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WG',
  'name': 'Intermediate bulk cont,steel,pressurised >10 kpa',
  'description': 'Intermediate bulk cont,steel,pressurised >10 kpa',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WH',
  'name': 'Intermedt bulk cont,aluminium,pressurised >10 kpa',
  'description': 'Intermedt bulk cont,aluminium,pressurised >10 kpa',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WJ',
  'name': 'Intermediate bulk container,metal, pressure 10 kpa',
  'description': 'Intermediate bulk container,metal, pressure 10 kpa',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WK',
  'name': 'Intermediate bulk container, steel, liquid',
  'description': 'Intermediate bulk container, steel, liquid',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WL',
  'name': 'Intermediate bulk container, aluminium, liquid',
  'description': 'Intermediate bulk container, aluminium, liquid',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WM',
  'name': 'Intermediate bulk container, metal, liquid',
  'description': 'Intermediate bulk container, metal, liquid',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WN',
  'name': 'Intermd bulk cont,woven plastic,without coat/liner',
  'description': 'Intermd bulk cont,woven plastic,without coat/liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WP',
  'name': 'Intermediate bulk container, woven plastic, coated',
  'description': 'Intermediate bulk container, woven plastic, coated',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WQ',
  'name': 'Intermediate bulk cont,woven plastic,with liner',
  'description': 'Intermediate bulk cont,woven plastic,with liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WR',
  'name': 'Intermedt bulk cont,woven plastic,coated and liner',
  'description': 'Intermedt bulk cont,woven plastic,coated and liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WS',
  'name': 'Intermediate bulk container, plastic film',
  'description': 'Intermediate bulk container, plastic film',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WT',
  'name': 'Intermediate bulk cont,textile with out coat/liner',
  'description': 'Intermediate bulk cont,textile with out coat/liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WU',
  'name': 'Intermdte bulk cont,natural wood,with inner liner',
  'description': 'Intermdte bulk cont,natural wood,with inner liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WV',
  'name': 'Intermediate bulk container, textile, coated',
  'description': 'Intermediate bulk container, textile, coated',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WW',
  'name': 'Intermediate bulk container, textile, with liner',
  'description': 'Intermediate bulk container, textile, with liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WX',
  'name': 'Intermediate bulk cont,textile,coated and liner',
  'description': 'Intermediate bulk cont,textile,coated and liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WY',
  'name': 'Intermediate bulk cont,plywood,with inner liner',
  'description': 'Intermediate bulk cont,plywood,with inner liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'WZ',
  'name': 'Intermd bulk cont,reconstttd wood,with inner liner',
  'description': 'Intermd bulk cont,reconstttd wood,with inner liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'XA',
  'name': 'Bag, woven plastic, without inner coat/liner',
  'description': 'Bag, woven plastic, without inner coat/liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'XB',
  'name': 'Bag, woven plastic, sift proof',
  'description': 'Bag, woven plastic, sift proof',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'XC',
  'name': 'Bag, woven plastic, water resistant',
  'description': 'Bag, woven plastic, water resistant',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'XD',
  'name': 'Bag, plastics film',
  'description': 'Bag, plastics film',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'XF',
  'name': 'Bag, textile, without inner coat/liner',
  'description': 'Bag, textile, without inner coat/liner',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'XG',
  'name': 'Bag, textile, sift proof',
  'description': 'Bag, textile, sift proof',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'XH',
  'name': 'Bag, textile, water resistant',
  'description': 'Bag, textile, water resistant',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'XJ',
  'name': 'Bag, paper, multi-wall',
  'description': 'Bag, paper, multi-wall',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'XK',
  'name': 'Bag, paper, multi-wall, water resistant',
  'description': 'Bag, paper, multi-wall, water resistant',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'XN',
  'name': 'test',
  'description': 'test',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YA',
  'name': 'Compsite packging,plastic receptacle in steel drum',
  'description': 'Compsite packging,plastic receptacle in steel drum',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YB',
  'name': 'Compste packgng,plastc recptcle in steel crate box',
  'description': 'Compste packgng,plastc recptcle in steel crate box',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YC',
  'name': 'Compste packgng,plastic recptcle in aluminium drum',
  'description': 'Compste packgng,plastic recptcle in aluminium drum',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YD',
  'name': 'Compste packgng,plastic recptcle in alumnium crate',
  'description': 'Compste packgng,plastic recptcle in alumnium crate',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YF',
  'name': 'Compsite packging,plastic receptacle in wooden box',
  'description': 'Compsite packging,plastic receptacle in wooden box',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YG',
  'name': 'Compste packgng,plastic receptacle in plywood drum',
  'description': 'Compste packgng,plastic receptacle in plywood drum',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YH',
  'name': 'Compste packging,plastic receptacle in plywood box',
  'description': 'Compste packging,plastic receptacle in plywood box',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YJ',
  'name': 'Compsite packging,plastic receptacle in fibre drum',
  'description': 'Compsite packging,plastic receptacle in fibre drum',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YK',
  'name': 'Compste packgng,plastic recptcle in fibreboard box',
  'description': 'Compste packgng,plastic recptcle in fibreboard box',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YL',
  'name': 'Compste packgng,plastic receptacle in plastic drum',
  'description': 'Compste packgng,plastic receptacle in plastic drum',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YM',
  'name': 'Compsite packgng,plstc recptcle in solid plstc box',
  'description': 'Compsite packgng,plstc recptcle in solid plstc box',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YN',
  'name': 'Composite packaging,glass receptacle in steel drum',
  'description': 'Composite packaging,glass receptacle in steel drum',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YP',
  'name': 'Compste packgng,glass recptacle in steel crate box',
  'description': 'Compste packgng,glass recptacle in steel crate box',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YQ',
  'name': 'Compste packgng,glass receptacle in aluminium drum',
  'description': 'Compste packgng,glass receptacle in aluminium drum',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YR',
  'name': 'Compste packgng,glass recptacle in aluminium crate',
  'description': 'Compste packgng,glass recptacle in aluminium crate',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YS',
  'name': 'Composite packaging,glass receptacle in wooden box',
  'description': 'Composite packaging,glass receptacle in wooden box',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YT',
  'name': 'Compsite packging,glass receptacle in plywood drum',
  'description': 'Compsite packging,glass receptacle in plywood drum',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YV',
  'name': 'Compste packgng,glass recptcle in wickrwork hamper',
  'description': 'Compste packgng,glass recptcle in wickrwork hamper',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YW',
  'name': 'Composite packaging,glass receptacle in fibre drum',
  'description': 'Composite packaging,glass receptacle in fibre drum',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YX',
  'name': 'Compste packgng,glass receptacle in fibreboard box',
  'description': 'Compste packgng,glass receptacle in fibreboard box',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YY',
  'name': 'Compste pckgng,glss recptcl in expndbl plastc pack',
  'description': 'Compste pckgng,glss recptcl in expndbl plastc pack',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'YZ',
  'name': 'Compsite packgng,glass recptcle in solid plstc pck',
  'description': 'Compsite packgng,glass recptcle in solid plstc pck',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZA',
  'name': 'Intermediate bulk container, paper, multi-wall',
  'description': 'Intermediate bulk container, paper, multi-wall',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZB',
  'name': 'Bag, large',
  'description': 'Bag, large',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZC',
  'name': 'Intermd bulk cont,paper,multi-wall,water resistant',
  'description': 'Intermd bulk cont,paper,multi-wall,water resistant',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZD',
  'name': 'Intermd bulk cont,rgd plstc,w/strctrl equipm,solid',
  'description': 'Intermd bulk cont,rgd plstc,w/strctrl equipm,solid',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZF',
  'name': 'Intermd bulk cont,rgid plstc,freestandng,solds',
  'description': 'Intermd bulk cont,rgid plstc,freestandng,solds',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZG',
  'name': 'Intermdbulk cnt,rgd plstc,w/strctrl equipm,pressrd',
  'description': 'Intermdbulk cnt,rgd plstc,w/strctrl equipm,pressrd',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZH',
  'name': 'Intermd bulk cont,rgd plstc,freestnd,pressurised',
  'description': 'Intermd bulk cont,rgd plstc,freestnd,pressurised',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZJ',
  'name': 'Intermd bulk cont,rgd plstc,w/strctrl equipm,lquid',
  'description': 'Intermd bulk cont,rgd plstc,w/strctrl equipm,lquid',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZK',
  'name': 'Intermd bulk cont,rgid plstc,freestanding,liquids',
  'description': 'Intermd bulk cont,rgid plstc,freestanding,liquids',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZL',
  'name': 'Intermd bulk cont,composite,rigid plastic,solids',
  'description': 'Intermd bulk cont,composite,rigid plastic,solids',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZM',
  'name': 'Intermd bulk cont,compste,flexbl plastic, solids',
  'description': 'Intermd bulk cont,compste,flexbl plastic, solids',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZN',
  'name': 'Intermd bulk cont,compsit,rgid plstc,pressurised',
  'description': 'Intermd bulk cont,compsit,rgid plstc,pressurised',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZP',
  'name': 'Intermd bulk cont,compsit,flexbl plstc,pressurised',
  'description': 'Intermd bulk cont,compsit,flexbl plstc,pressurised',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZQ',
  'name': 'Intermd bulk cont,composite,rigid plastic,liquids',
  'description': 'Intermd bulk cont,composite,rigid plastic,liquids',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZR',
  'name': 'Intermd bulk cont,compsite,flexible plastc,liquids',
  'description': 'Intermd bulk cont,compsite,flexible plastc,liquids',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZS',
  'name': 'Intermediate bulk container, composite',
  'description': 'Intermediate bulk container, composite',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZT',
  'name': 'Intermediate bulk container, fibreboard',
  'description': 'Intermediate bulk container, fibreboard',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZU',
  'name': 'Intermediate bulk container, flexible',
  'description': 'Intermediate bulk container, flexible',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZV',
  'name': 'Intermediate bulk container,metal,other than steel',
  'description': 'Intermediate bulk container,metal,other than steel',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZW',
  'name': 'Intermediate bulk container, natural wood',
  'description': 'Intermediate bulk container, natural wood',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZX',
  'name': 'Intermediate bulk container, plywood',
  'description': 'Intermediate bulk container, plywood',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZY',
  'name': 'Intermediate bulk container, reconstituted wood',
  'description': 'Intermediate bulk container, reconstituted wood',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-kemasan',
  'reference_name': 'Referensi Jenis Kemasan',
  'code': 'ZZ',
  'name': 'Mutually defined',
  'description': 'Mutually defined',
  'is_active': True}]
