"""Seeder master data CEISA untuk referensi jenis ekspor.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_JENIS_EKSPOR_CODES = [{'reference_slug': 'referensi-jenis-ekspor',
  'reference_name': 'Referensi Jenis Ekspor',
  'code': '1',
  'name': 'BIASA',
  'description': 'BIASA',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-ekspor',
  'reference_name': 'Referensi Jenis Ekspor',
  'code': '2',
  'name': 'BERKALA',
  'description': 'BERKALA',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-ekspor',
  'reference_name': 'Referensi Jenis Ekspor',
  'code': '3',
  'name': 'FASILITAS',
  'description': 'FASILITAS',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-ekspor',
  'reference_name': 'Referensi Jenis Ekspor',
  'code': '4',
  'name': 'RE-IMPOR',
  'description': 'RE-IMPOR',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-ekspor',
  'reference_name': 'Referensi Jenis Ekspor',
  'code': '5',
  'name': 'RE-EKSPOR',
  'description': 'RE-EKSPOR',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-ekspor',
  'reference_name': 'Referensi Jenis Ekspor',
  'code': '6',
  'name': 'EX IMPOR SEMENTARA',
  'description': 'EX IMPOR SEMENTARA',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-ekspor',
  'reference_name': 'Referensi Jenis Ekspor',
  'code': '7',
  'name': 'EKSPOR GABUNGAN',
  'description': 'EKSPOR GABUNGAN',
  'is_active': True}]
