"""Seeder master data CEISA untuk referensi jenis pengangkutan.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_JENIS_PENGANGKUTAN_CODES = [{'reference_slug': 'referensi-jenis-pengangkutan',
  'reference_name': 'Referensi Jenis Pengangkutan',
  'code': '1',
  'name': 'SATU SARANA ANGKUT',
  'description': 'SATU SARANA ANGKUT',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pengangkutan',
  'reference_name': 'Referensi Jenis Pengangkutan',
  'code': '2',
  'name': 'INSTALASI/PIPA/TRANSMISI',
  'description': 'INSTALASI/PIPA/TRANSMISI',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pengangkutan',
  'reference_name': 'Referensi Jenis Pengangkutan',
  'code': '3',
  'name': 'ANGKUT LANJUT',
  'description': 'ANGKUT LANJUT',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pengangkutan',
  'reference_name': 'Referensi Jenis Pengangkutan',
  'code': '4',
  'name': 'ANGKUT LANJUT MULTIMODA',
  'description': 'ANGKUT LANJUT MULTIMODA',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pengangkutan',
  'reference_name': 'Referensi Jenis Pengangkutan',
  'code': '5',
  'name': 'BARANG BAWAAN PENUMPANG / AWAK SARKUT',
  'description': 'BARANG BAWAAN PENUMPANG / AWAK SARKUT',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pengangkutan',
  'reference_name': 'Referensi Jenis Pengangkutan',
  'code': '6',
  'name': 'SARANA ANGKUT LAINNYA',
  'description': 'SARANA ANGKUT LAINNYA',
  'is_active': True}]
