"""Seeder master data CEISA untuk referensi jenis vd.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_JENIS_NILAI_CODES = [{'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'BTR',
  'name': 'BUKAN TRANSAKSI JUAL BELI LAINNYA',
  'description': 'BUKAN TRANSAKSI JUAL BELI LAINNYA',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'CAM',
  'name': 'Barang terdiri dari barang-barang yang merupakan obyek transaksi gabungan dari dua atau lebih jenis '
          'transaksi 1 sampai dengan 10',
  'description': 'Barang terdiri dari barang-barang yang merupakan obyek transaksi gabungan dari dua atau lebih jenis '
                 'transaksi 1 sampai dengan 10',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'CMA',
  'name': 'BUKAN TRANSAKSI JUAL BELI BERUPA BARANG HADIAH/PROMOSI/CONTOH',
  'description': 'BUKAN TRANSAKSI JUAL BELI BERUPA BARANG HADIAH/PROMOSI/CONTOH',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'FTR',
  'name': 'TRANSAKSI JUAL BELI BERDASARKAN HARGA FUTURES (FUTURE PRICE), YAITU HARGA YANG BARU DAPAT DITENTUKAN '
          'SETELAH PIB DISAMPAIKAN',
  'description': 'TRANSAKSI JUAL BELI BERDASARKAN HARGA FUTURES (FUTURE PRICE), YAITU HARGA YANG BARU DAPAT DITENTUKAN '
                 'SETELAH PIB DISAMPAIKAN',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'HBH',
  'name': 'BUKAN TRANSAKSI JUAL BELI BERUPA BARANG BANTUAN/HIBAH',
  'description': 'BUKAN TRANSAKSI JUAL BELI BERUPA BARANG BANTUAN/HIBAH',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'ITM',
  'name': 'BUKAN TRANSAKSI JUAL BELI BERUPA BARANG YANG DIIMPOR OLEH INTERMEDIARY YANG TIDAK MEMBELI BARANG',
  'description': 'BUKAN TRANSAKSI JUAL BELI BERUPA BARANG YANG DIIMPOR OLEH INTERMEDIARY YANG TIDAK MEMBELI BARANG',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'KON',
  'name': 'BUKAN TRANSAKSI JUAL BELI BERUPA BARANG KONSINYASI',
  'description': 'BUKAN TRANSAKSI JUAL BELI BERUPA BARANG KONSINYASI',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'LES',
  'name': 'BUKAN TRANSAKSI JUAL BELI BERUPA BARANG SEWA (LEASING)',
  'description': 'BUKAN TRANSAKSI JUAL BELI BERUPA BARANG SEWA (LEASING)',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'NTR',
  'name': 'TRANSAKSI JUAL BELI',
  'description': 'TRANSAKSI JUAL BELI',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'PRO',
  'name': 'TRANSAKSI JUAL BELI MENGANDUNG PROCEEDS YANG NILAINYA BELUM DAPAT DITENTUKAN',
  'description': 'TRANSAKSI JUAL BELI MENGANDUNG PROCEEDS YANG NILAINYA BELUM DAPAT DITENTUKAN',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'ROY',
  'name': 'TRANSAKSI JUAL BELI MENGANDUNG ROYALTI YANG NILAINYA BELUM DAPAT DITENTUKAN',
  'description': 'TRANSAKSI JUAL BELI MENGANDUNG ROYALTI YANG NILAINYA BELUM DAPAT DITENTUKAN',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-nilai',
  'reference_name': 'Referensi Jenis VD',
  'code': 'TIP',
  'name': 'TITIPAN',
  'description': 'TITIPAN',
  'is_active': True}]
