"""Seeder master data CEISA untuk referensi fasilitas.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_FASILITAS_CODES = [{'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '00',
  'name': 'Tanpa Fasilitas',
  'description': 'Tanpa Fasilitas',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '01',
  'name': 'PMA',
  'description': 'PMA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '02',
  'name': 'PMDN',
  'description': 'PMDN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '03',
  'name': 'KITE/Kemudahan Impor Tujuan Ekspor - KITE PEMBEBASAN',
  'description': 'KITE/Kemudahan Impor Tujuan Ekspor - KITE PEMBEBASAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '04',
  'name': 'Insentif Otomotif',
  'description': 'Insentif Otomotif',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '05',
  'name': 'PTNI',
  'description': 'PTNI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '06',
  'name': 'ATIGA',
  'description': 'ATIGA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '07',
  'name': 'Keperluan Pertahanan dan Keamanan',
  'description': 'Keperluan Pertahanan dan Keamanan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '08',
  'name': 'Industri Strategis',
  'description': 'Industri Strategis',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '09',
  'name': 'Proyek pemerintah yang dibiayai dengan hibah atau dana pinjaman luar negeri',
  'description': 'Proyek pemerintah yang dibiayai dengan hibah atau dana pinjaman luar negeri',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '10',
  'name': 'Perwakilan Negara Asing dan Pejabatnya',
  'description': 'Perwakilan Negara Asing dan Pejabatnya',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '11',
  'name': 'Badan Internasional dan Pejabatnya',
  'description': 'Badan Internasional dan Pejabatnya',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '12',
  'name': '--',
  'description': '--',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '13',
  'name': 'Hadiah untuk ibadah umum, amal,sosial, atau kebudayaan',
  'description': 'Hadiah untuk ibadah umum, amal,sosial, atau kebudayaan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '14',
  'name': 'Keperluan museum, kebun binatang dan tempat lain yang semacamnya untuk umum',
  'description': 'Keperluan museum, kebun binatang dan tempat lain yang semacamnya untuk umum',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '15',
  'name': 'Keperluan khusus tuna netra dan penyandang cacat',
  'description': 'Keperluan khusus tuna netra dan penyandang cacat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '16',
  'name': 'Penelitian dan Pengembangan Ilmu Pengetahuan',
  'description': 'Penelitian dan Pengembangan Ilmu Pengetahuan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '17',
  'name': 'Barang contoh tidak untuk diperdagangkan',
  'description': 'Barang contoh tidak untuk diperdagangkan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '18',
  'name': 'Barang re-impor yang mendapat fasilitas Bapeksta',
  'description': 'Barang re-impor yang mendapat fasilitas Bapeksta',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '19',
  'name': 'Pencegahan Pencemaran Lingkungan',
  'description': 'Pencegahan Pencemaran Lingkungan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '20',
  'name': 'Bibit dan benih untuk pengembangan pertanian, peternakan dan perikanan',
  'description': 'Bibit dan benih untuk pengembangan pertanian, peternakan dan perikanan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '21',
  'name': 'Hasil laut',
  'description': 'Hasil laut',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '22',
  'name': 'Barang yang semula diekspor untuk perbaikan, pengerjaan dan pengujian',
  'description': 'Barang yang semula diekspor untuk perbaikan, pengerjaan dan pengujian',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '23',
  'name': 'Bahan terapi manusia, pengelompokan darah, dan bahan penjenisan jaringan',
  'description': 'Bahan terapi manusia, pengelompokan darah, dan bahan penjenisan jaringan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '24',
  'name': 'Diimpor pleh pemerintah pusat/ daerah untuk kepentingan umum',
  'description': 'Diimpor pleh pemerintah pusat/ daerah untuk kepentingan umum',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '25',
  'name': 'Berasal dari Kawasan Berikat',
  'description': 'Berasal dari Kawasan Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '26',
  'name': 'Berasal dari Gudang Berikat',
  'description': 'Berasal dari Gudang Berikat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '27',
  'name': '--',
  'description': '--',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '28',
  'name': 'Keputusan lainnya (selain 01 s/d 24 dan 29 s/d 36)',
  'description': 'Keputusan lainnya (selain 01 s/d 24 dan 29 s/d 36)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '29',
  'name': 'Pertamina',
  'description': 'Pertamina',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '30',
  'name': 'Pembangunan atau pengembangan Industri (non PMA/PMDN)',
  'description': 'Pembangunan atau pengembangan Industri (non PMA/PMDN)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '31',
  'name': 'Barang reimpor yang tidak mendapatkan fasilitas Bapeksta',
  'description': 'Barang reimpor yang tidak mendapatkan fasilitas Bapeksta',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '32',
  'name': 'Barang yang semula diekspor untuk pengerjaan proyek, pameran dan pengemasan',
  'description': 'Barang yang semula diekspor untuk pengerjaan proyek, pameran dan pengemasan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '33',
  'name': 'Berasal dari Toko Bebas Bea (TBB)',
  'description': 'Berasal dari Toko Bebas Bea (TBB)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '34',
  'name': 'Berasal dari Entreport Tujuan Pameran (ETP)',
  'description': 'Berasal dari Entreport Tujuan Pameran (ETP)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '35',
  'name': 'Impor Sementara',
  'description': 'Impor Sementara',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '36',
  'name': 'AIDA',
  'description': 'AIDA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '37',
  'name': 'BKPM',
  'description': 'BKPM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '38',
  'name': 'Pertambangan',
  'description': 'Pertambangan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '39',
  'name': 'Penundaan Bea Masuk, Cukai dan/atau Pajak',
  'description': 'Penundaan Bea Masuk, Cukai dan/atau Pajak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '40',
  'name': 'KITE Pengembalian',
  'description': 'KITE Pengembalian',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '41',
  'name': 'KITE IKM',
  'description': 'KITE IKM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '42',
  'name': 'KITE IKM (Mesin)',
  'description': 'KITE IKM (Mesin)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '43',
  'name': 'KITE (Barang Contoh)',
  'description': 'KITE (Barang Contoh)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '50',
  'name': 'Keterangan Karantina',
  'description': 'Keterangan Karantina',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '51',
  'name': 'Keterangan Kesehatan / POM',
  'description': 'Keterangan Kesehatan / POM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '52',
  'name': 'Keterangan Pajak',
  'description': 'Keterangan Pajak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '53',
  'name': 'Keterangan lainnya (selain 50 s/d 52)',
  'description': 'Keterangan lainnya (selain 50 s/d 52)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '54',
  'name': 'Preferensi Tarif Importasi Asean-China (ACFTA)',
  'description': 'Preferensi Tarif Importasi Asean-China (ACFTA)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '55',
  'name': 'Preferensi Tarif Importasi Asean-Korea (AKFTA)',
  'description': 'Preferensi Tarif Importasi Asean-Korea (AKFTA)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '56',
  'name': 'Preferensi Tarif Indonesia-Japan (IJ-EPA)',
  'description': 'Preferensi Tarif Indonesia-Japan (IJ-EPA)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '57',
  'name': 'Preferensi Tarif Importasi Asean-India (AIFTA)',
  'description': 'Preferensi Tarif Importasi Asean-India (AIFTA)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '58',
  'name': 'Preferensi Tarif Asean-Australia-New Zealand (AANZFTA)',
  'description': 'Preferensi Tarif Asean-Australia-New Zealand (AANZFTA)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '59',
  'name': 'Preferensi Tarif Indonesia Pakistan FTA',
  'description': 'Preferensi Tarif Indonesia Pakistan FTA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '60',
  'name': 'USDFS',
  'description': 'USDFS',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '61',
  'name': 'AJCEP',
  'description': 'AJCEP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '62',
  'name': 'Preferensi Tarif Indonesia - Palestina',
  'description': 'Preferensi Tarif Indonesia - Palestina',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '63',
  'name': 'Preferensi Tarif Indonesia - Chili (ICCEPA)',
  'description': 'Preferensi Tarif Indonesia - Chili (ICCEPA)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '64',
  'name': 'Preferensi Tarif ASEAN - Hongkong, China FTA',
  'description': 'Preferensi Tarif ASEAN - Hongkong, China FTA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '65',
  'name': 'Preferensi Tarif Indonesia Australia (IACEPA)',
  'description': 'Preferensi Tarif Indonesia Australia (IACEPA)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '67',
  'name': 'IECEPA',
  'description': 'IECEPA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '68',
  'name': 'PTA-D8',
  'description': 'PTA-D8',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '69',
  'name': 'RCEP',
  'description': 'RCEP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '70',
  'name': 'Pembebasan Bea Masuk barang dan bahan untuk pembangunan dan pengembangan industri dalam rangka penanaman '
          'modal',
  'description': 'Pembebasan Bea Masuk barang dan bahan untuk pembangunan dan pengembangan industri dalam rangka '
                 'penanaman modal',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '71',
  'name': 'Pembebasan Bea Masuk barang dan bahan dalam rangka pembangunan dan pengembangan industri untuk jangka waktu '
          'tertentu',
  'description': 'Pembebasan Bea Masuk barang dan bahan dalam rangka pembangunan dan pengembangan industri untuk '
                 'jangka waktu tertentu',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '72',
  'name': 'IKCEPA',
  'description': 'IKCEPA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '73',
  'name': 'USDFS-IKCEPA',
  'description': 'USDFS-IKCEPA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '74',
  'name': 'IUAECEPA',
  'description': 'IUAECEPA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '79',
  'name': 'Tariff Rate Quota (TRQ)',
  'description': 'Tariff Rate Quota (TRQ)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '80',
  'name': 'Penanggulangan Bencana',
  'description': 'Penanggulangan Bencana',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '81',
  'name': 'BM DTP KHUSUS',
  'description': 'BM DTP KHUSUS',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '83',
  'name': 'Vaksin Covid 19',
  'description': 'Vaksin Covid 19',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '84',
  'name': 'KEK',
  'description': 'KEK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '88',
  'name': 'Preferensi Nilai Kandungan Lokal',
  'description': 'Preferensi Nilai Kandungan Lokal',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '89',
  'name': 'Insentif KBLBB Skema PPnBM DTP',
  'description': 'Insentif KBLBB Skema PPnBM DTP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'},
 {'reference_slug': 'referensi-fasilitas',
  'reference_name': 'Referensi Fasilitas',
  'code': '99',
  'name': 'Terdapat beberapa fasilitas/ pemenuhan peryaratan impor untuk 1 dokumen',
  'description': 'Terdapat beberapa fasilitas/ pemenuhan peryaratan impor untuk 1 dokumen',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-fasilitas.md'}]
