"""Seeder master data CEISA untuk referensi tujuan pengiriman.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_TUJUAN_PENGIRIMAN_CODES = [{'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '25',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '25',
  'name': '2',
  'description': '2',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '25',
  'name': '3',
  'description': '3',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '25',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '25',
  'name': '5',
  'description': '5',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '261',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '261',
  'name': '2',
  'description': '2',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '261',
  'name': '3',
  'description': '3',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '261',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '261',
  'name': '5',
  'description': '5',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '27',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '27',
  'name': '2',
  'description': '2',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '27',
  'name': '3',
  'description': '3',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '27',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '27',
  'name': '5',
  'description': '5',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '40',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '40',
  'name': '2',
  'description': '2',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '40',
  'name': '3',
  'description': '3',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '40',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '40',
  'name': '5',
  'description': '5',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '41',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '41',
  'name': '2',
  'description': '2',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '41',
  'name': '3',
  'description': '3',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '41',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '41',
  'name': '5',
  'description': '5',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '512',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '512',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '513',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '513',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '522',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengiriman',
  'reference_name': 'Referensi Tujuan Pengiriman',
  'code': '522',
  'name': '4',
  'description': '4',
  'is_active': True}]
