"""Seeder master data CEISA untuk referensi ijin.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_IJIN_CODES = [{'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '00000',
  'name': 'Dilarang',
  'description': 'Dilarang',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01000',
  'name': 'Dilarang',
  'description': 'Dilarang',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01001',
  'name': 'NPIK Beras',
  'description': 'NPIK Beras',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01002',
  'name': 'NPIK Gula',
  'description': 'NPIK Gula',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01003',
  'name': 'NPIK Kedelai',
  'description': 'NPIK Kedelai',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01004',
  'name': 'NPIK Jagung',
  'description': 'NPIK Jagung',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01005',
  'name': 'NPIK TPT',
  'description': 'NPIK TPT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01006',
  'name': 'NPIK Elektronik',
  'description': 'NPIK Elektronik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01007',
  'name': 'NPIK Sepatu',
  'description': 'NPIK Sepatu',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01008',
  'name': 'NPIK Mainan Anak-anak',
  'description': 'NPIK Mainan Anak-anak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01009',
  'name': 'IT Cakram Optik',
  'description': 'IT Cakram Optik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01010',
  'name': 'SPI Cakram Optik Isi/Kosong/Bahan Baku/Mesin dan Peralatan Mesin',
  'description': 'SPI Cakram Optik Isi/Kosong/Bahan Baku/Mesin dan Peralatan Mesin',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01011',
  'name': 'IP Limbah Non B3',
  'description': 'IP Limbah Non B3',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01012',
  'name': 'IP Bahan Berbahaya',
  'description': 'IP Bahan Berbahaya',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01013',
  'name': 'IP Plastik',
  'description': 'IP Plastik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01015',
  'name': 'PI Cakram Optik Isi',
  'description': 'PI Cakram Optik Isi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01016',
  'name': 'PI Cakram Optik Kosong',
  'description': 'PI Cakram Optik Kosong',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01017',
  'name': 'PI Cakram Optik Mesin dan Peralatan Mesin',
  'description': 'PI Cakram Optik Mesin dan Peralatan Mesin',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01021',
  'name': 'IP Bahan Baku Plastik',
  'description': 'IP Bahan Baku Plastik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01061',
  'name': 'Surat Pendaftaran Barang',
  'description': 'Surat Pendaftaran Barang',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01062',
  'name': 'Nomor Pendaftaran Barang',
  'description': 'Nomor Pendaftaran Barang',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01099',
  'name': 'Laporan Surveyor',
  'description': 'Laporan Surveyor',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01203',
  'name': 'IP Beras',
  'description': 'IP Beras',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01204',
  'name': 'IP BPO Non Metil Bromida',
  'description': 'IP BPO Non Metil Bromida',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01208',
  'name': 'IP Nitrocellulose',
  'description': 'IP Nitrocellulose',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01209',
  'name': 'IP Prekursor Non Farmasi',
  'description': 'IP Prekursor Non Farmasi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01210',
  'name': 'IP Tekstil',
  'description': 'IP Tekstil',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01211',
  'name': 'IP PCMX',
  'description': 'IP PCMX',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01212',
  'name': 'IP Pelumas',
  'description': 'IP Pelumas',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01213',
  'name': 'IP Etilena',
  'description': 'IP Etilena',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01214',
  'name': 'IP Garam Konsumsi',
  'description': 'IP Garam Konsumsi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01215',
  'name': 'IP Garam Industri',
  'description': 'IP Garam Industri',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01216',
  'name': 'IP Gula Kristal Rafinasi',
  'description': 'IP Gula Kristal Rafinasi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01217',
  'name': 'IP BPO Metil Bromida',
  'description': 'IP BPO Metil Bromida',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01218',
  'name': 'IP Gula Kristal Mentah',
  'description': 'IP Gula Kristal Mentah',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01219',
  'name': 'IP Besi atau Baja',
  'description': 'IP Besi atau Baja',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01291',
  'name': 'IP / IT / SPI Garam Iodisasi / Non Iodisasi',
  'description': 'IP / IT / SPI Garam Iodisasi / Non Iodisasi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01292',
  'name': 'PI Garam Industri/PI Garam Konsumsi',
  'description': 'PI Garam Industri/PI Garam Konsumsi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01294',
  'name': 'IP / IT / SPI BPO Metil atau Non Metil Bromida',
  'description': 'IP / IT / SPI BPO Metil atau Non Metil Bromida',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01295',
  'name': 'IP/PI/IT Bahan Baku Plastik',
  'description': 'IP/PI/IT Bahan Baku Plastik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01296',
  'name': 'IP / IT / SPI Prekursor Non Farmasi',
  'description': 'IP / IT / SPI Prekursor Non Farmasi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01297',
  'name': 'IP / IT Besi Baja',
  'description': 'IP / IT Besi Baja',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01302',
  'name': 'IT Bahan Peledak Industri (Komersial)',
  'description': 'IT Bahan Peledak Industri (Komersial)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01304',
  'name': 'IT BPO Non Metil Bromida',
  'description': 'IT BPO Non Metil Bromida',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01306',
  'name': 'IT Garam',
  'description': 'IT Garam',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01307',
  'name': 'IT Intan Kasar',
  'description': 'IT Intan Kasar',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01308',
  'name': 'IT Mesin Multifungsi dan Printer Berwarna',
  'description': 'IT Mesin Multifungsi dan Printer Berwarna',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01309',
  'name': 'IT Minuman Beralkohol',
  'description': 'IT Minuman Beralkohol',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01310',
  'name': 'IT Nitro Cellulose',
  'description': 'IT Nitro Cellulose',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01311',
  'name': 'IT Prekursor Non Farmasi',
  'description': 'IT Prekursor Non Farmasi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01312',
  'name': 'IT Perkakas Tangan',
  'description': 'IT Perkakas Tangan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01313',
  'name': 'IT Preparat Bau-bauan',
  'description': 'IT Preparat Bau-bauan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01314',
  'name': 'IT Sakarin dan Garamnya',
  'description': 'IT Sakarin dan Garamnya',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01316',
  'name': 'IT Besi atau Baja',
  'description': 'IT Besi atau Baja',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01321',
  'name': 'PI Bahan Baku Plastik',
  'description': 'PI Bahan Baku Plastik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01399',
  'name': 'IT Produk Tertentu',
  'description': 'IT Produk Tertentu',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01403',
  'name': 'PI Bahan Berbahaya',
  'description': 'PI Bahan Berbahaya',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01405',
  'name': 'PI Nitrocellulose',
  'description': 'PI Nitrocellulose',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01406',
  'name': 'PI Prekursor Non Farmasi',
  'description': 'PI Prekursor Non Farmasi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01407',
  'name': 'PI Bahan Peledak Industri',
  'description': 'PI Bahan Peledak Industri',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01408',
  'name': 'PI Cengkeh',
  'description': 'PI Cengkeh',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01410',
  'name': 'IP / SPI / IT Gula Kristal',
  'description': 'IP / SPI / IT Gula Kristal',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01411',
  'name': 'PI Intan Kasar',
  'description': 'PI Intan Kasar',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01412',
  'name': 'SPI MMEA',
  'description': 'SPI MMEA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01413',
  'name': 'PI Mesin Multi Fungsi dan Printer Berwarna',
  'description': 'PI Mesin Multi Fungsi dan Printer Berwarna',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01414',
  'name': 'SPI Perkakas Tangan',
  'description': 'SPI Perkakas Tangan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01415',
  'name': 'SPI Preparat Bau-bauan',
  'description': 'SPI Preparat Bau-bauan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01416',
  'name': 'PI Sakarin',
  'description': 'PI Sakarin',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01417',
  'name': 'PI Preparat Campuran Mengandung Alkohol',
  'description': 'PI Preparat Campuran Mengandung Alkohol',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01418',
  'name': 'PI Tabung gas 3 Kg',
  'description': 'PI Tabung gas 3 Kg',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01421',
  'name': 'PI Siklamat',
  'description': 'PI Siklamat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01422',
  'name': 'PI Beras',
  'description': 'PI Beras',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01425',
  'name': 'PI BPO Metil Bromida',
  'description': 'PI BPO Metil Bromida',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01426',
  'name': 'PI BPO Non Metil Bromida',
  'description': 'PI BPO Non Metil Bromida',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01427',
  'name': 'SPI Produk Kehutanan',
  'description': 'SPI Produk Kehutanan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01501',
  'name': 'Surat Pendaftaran Barang/Perkecualian SNI/NPB',
  'description': 'Surat Pendaftaran Barang/Perkecualian SNI/NPB',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01502',
  'name': 'PI Gula Kristal Putih',
  'description': 'PI Gula Kristal Putih',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01503',
  'name': 'PI Barang Hibah',
  'description': 'PI Barang Hibah',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01504',
  'name': 'PI Barang Modal Bukan Baru Pemakai Langsung',
  'description': 'PI Barang Modal Bukan Baru Pemakai Langsung',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01505',
  'name': 'PI Barang Impor Sementara',
  'description': 'PI Barang Impor Sementara',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01506',
  'name': 'PI Barang Modal Bukan Baru Rekondisi',
  'description': 'PI Barang Modal Bukan Baru Rekondisi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01507',
  'name': 'PI Pemasukan Barang Kembali',
  'description': 'PI Pemasukan Barang Kembali',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01508',
  'name': 'PI Tanpa API & NPIK',
  'description': 'PI Tanpa API & NPIK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01509',
  'name': 'PI Tanpa NPIK',
  'description': 'PI Tanpa NPIK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01510',
  'name': 'PI Cakram Otik Polycarbonat',
  'description': 'PI Cakram Otik Polycarbonat',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01511',
  'name': 'PI Minyak dan Gas Bumi',
  'description': 'PI Minyak dan Gas Bumi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01512',
  'name': 'PI Minuman Beralkohol',
  'description': 'PI Minuman Beralkohol',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01513',
  'name': 'PI Pupuk Bersubsidi',
  'description': 'PI Pupuk Bersubsidi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01514',
  'name': 'PI Garam Industri',
  'description': 'PI Garam Industri',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01515',
  'name': 'PI Barang Pindahan Duta Besar',
  'description': 'PI Barang Pindahan Duta Besar',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01516',
  'name': 'PI Tidak Reekspor barang ex Impor Sementara',
  'description': 'PI Tidak Reekspor barang ex Impor Sementara',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01517',
  'name': 'PI Tanpa API',
  'description': 'PI Tanpa API',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01518',
  'name': 'IP Besi atau Baja K3S',
  'description': 'IP Besi atau Baja K3S',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01519',
  'name': 'IT Produk Tertentu - Alas Kaki',
  'description': 'IT Produk Tertentu - Alas Kaki',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01520',
  'name': 'IT Produk Tertentu - Elektronika',
  'description': 'IT Produk Tertentu - Elektronika',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01521',
  'name': 'IT Produk Tertentu - Mainan Anak-anak',
  'description': 'IT Produk Tertentu - Mainan Anak-anak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01522',
  'name': 'IT Produk Tertentu - Pakaian Jadi',
  'description': 'IT Produk Tertentu - Pakaian Jadi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01523',
  'name': 'IT Produk Tertentu - Produk Makanan dan Minuman',
  'description': 'IT Produk Tertentu - Produk Makanan dan Minuman',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01524',
  'name': 'IT Gula Kristal Putih',
  'description': 'IT Gula Kristal Putih',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01525',
  'name': 'IT Non Cakram Optik',
  'description': 'IT Non Cakram Optik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01526',
  'name': 'IT BPO Metil Bromida',
  'description': 'IT BPO Metil Bromida',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01527',
  'name': 'PI Barang Modal Tidak Baru',
  'description': 'PI Barang Modal Tidak Baru',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01530',
  'name': 'PI Barang Modal Bukan Baru Pemakai Langsung / Rekondisi',
  'description': 'PI Barang Modal Bukan Baru Pemakai Langsung / Rekondisi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01531',
  'name': 'Laporan Surveyor / Certificate Of Inspection',
  'description': 'Laporan Surveyor / Certificate Of Inspection',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01532',
  'name': 'IT Cakram Optik / IT Non Cakram Optik',
  'description': 'IT Cakram Optik / IT Non Cakram Optik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01534',
  'name': 'IP B2 /SPI B2',
  'description': 'IP B2 /SPI B2',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01535',
  'name': 'IP / IT / SPI Nitrocelulose',
  'description': 'IP / IT / SPI Nitrocelulose',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01536',
  'name': 'IP Beras / SPI Beras',
  'description': 'IP Beras / SPI Beras',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01537',
  'name': 'Certificate Of Inspection',
  'description': 'Certificate Of Inspection',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01555',
  'name': 'Surat Keterangan Label berbahasa Indonesia',
  'description': 'Surat Keterangan Label berbahasa Indonesia',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01557',
  'name': 'SPI TPT',
  'description': 'SPI TPT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01558',
  'name': 'SPI Batik dan Motif Batik',
  'description': 'SPI Batik dan Motif Batik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01560',
  'name': 'PI Besi atau Baja, Baja Paduan, dan Produk Turunannya',
  'description': 'PI Besi atau Baja, Baja Paduan, dan Produk Turunannya',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01601',
  'name': 'PI Holtikultura',
  'description': 'PI Holtikultura',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01602',
  'name': 'IP Holtikultura',
  'description': 'IP Holtikultura',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01603',
  'name': 'IT Holtikultura',
  'description': 'IT Holtikultura',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01604',
  'name': 'IP / IT / SPI Holtikultura',
  'description': 'IP / IT / SPI Holtikultura',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01605',
  'name': 'IT Telepon Seluler, Komputer Genggam (Handheld) dan Komputer Tablet',
  'description': 'IT Telepon Seluler, Komputer Genggam (Handheld) dan Komputer Tablet',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01606',
  'name': 'PI Telepon Seluler, Komputer Genggam (Handheld) dan Komputer Tablet',
  'description': 'PI Telepon Seluler, Komputer Genggam (Handheld) dan Komputer Tablet',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01607',
  'name': 'IT Hewan dan Produk Hewan',
  'description': 'IT Hewan dan Produk Hewan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01608',
  'name': 'PI Hewan dan Produk Hewan',
  'description': 'PI Hewan dan Produk Hewan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01609',
  'name': 'IT Kedelai',
  'description': 'IT Kedelai',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01610',
  'name': 'PI Kedelai',
  'description': 'PI Kedelai',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01611',
  'name': 'IP Semen',
  'description': 'IP Semen',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01612',
  'name': 'IT Semen',
  'description': 'IT Semen',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01613',
  'name': 'PI Semen',
  'description': 'PI Semen',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01614',
  'name': 'PPI Semen',
  'description': 'PPI Semen',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01615',
  'name': 'IT Baja Paduan',
  'description': 'IT Baja Paduan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01616',
  'name': 'PI Baja Paduan',
  'description': 'PI Baja Paduan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01619',
  'name': 'IP Baja Paduan',
  'description': 'IP Baja Paduan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01621',
  'name': 'IT Bahan Baku Plastik',
  'description': 'IT Bahan Baku Plastik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01623',
  'name': 'Izin Tipe UTTP',
  'description': 'Izin Tipe UTTP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01627',
  'name': 'IP/PI/SPI Ban',
  'description': 'IP/PI/SPI Ban',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01690',
  'name': 'IP / IT / PI / PPI Semen',
  'description': 'IP / IT / PI / PPI Semen',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01800',
  'name': 'API-U / API-P',
  'description': 'API-U / API-P',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '01803',
  'name': 'Laporan Surveyor / Certificate Of Inspection / API-P',
  'description': 'Laporan Surveyor / Certificate Of Inspection / API-P',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '02001',
  'name': 'Karantina Ikan KID 7',
  'description': 'Karantina Ikan KID 7',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '02003',
  'name': 'Karantina Ikan KID 3',
  'description': 'Karantina Ikan KID 3',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '02015',
  'name': 'Karantina Ikan KID 15',
  'description': 'Karantina Ikan KID 15',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '02946',
  'name': 'Karantina Ikan KID 3',
  'description': 'Karantina Ikan KID 3',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '02947',
  'name': 'Karantina Ikan KID 5',
  'description': 'Karantina Ikan KID 5',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '02999',
  'name': 'KI-D3, KI-D12, atau KI-D15',
  'description': 'KI-D3, KI-D12, atau KI-D15',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '03004',
  'name': 'Karantina Hewan KH 4',
  'description': 'Karantina Hewan KH 4',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '03005',
  'name': 'Karantina Hewan KH 5',
  'description': 'Karantina Hewan KH 5',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '03007',
  'name': 'Karantina Hewan KH 7',
  'description': 'Karantina Hewan KH 7',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '03012',
  'name': 'Karantina Hewan KH 12',
  'description': 'Karantina Hewan KH 12',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '03999',
  'name': 'KH.4, KH.5, KH.7,KH.8a, KH.8b, KH.8c, KH.9, KH.10,KH.11 atau KH.12',
  'description': 'KH.4, KH.5, KH.7,KH.8a, KH.8b, KH.8c, KH.9, KH.10,KH.11 atau KH.12',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '04001',
  'name': 'KT 9 - Sertifikat Pelepasan',
  'description': 'KT 9 - Sertifikat Pelepasan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '04007',
  'name': 'SP 7 - Surat Pemberitahuan Tidak Perlu Tindakan Karantina Tumbuhan',
  'description': 'SP 7 - Surat Pemberitahuan Tidak Perlu Tindakan Karantina Tumbuhan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '04016',
  'name': 'KT 2 - Surat Persetujuan Pelaksanaan Tindakan',
  'description': 'KT 2 - Surat Persetujuan Pelaksanaan Tindakan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '04019',
  'name': 'KT 2 - Surat Persetujuan Pelaksanaan Tindakan',
  'description': 'KT 2 - Surat Persetujuan Pelaksanaan Tindakan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '04942',
  'name': 'KT.2 atau KT.9',
  'description': 'KT.2 atau KT.9',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '05854',
  'name': 'Surat Keterangan Impor',
  'description': 'Surat Keterangan Impor',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '05855',
  'name': 'Surat Keterangan Komoditas Non Obat dan Makanan',
  'description': 'Surat Keterangan Komoditas Non Obat dan Makanan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '05856',
  'name': 'Surat Keterangan Impor/Surat Keterangan Komoditas Non Obat dan Makanan',
  'description': 'Surat Keterangan Impor/Surat Keterangan Komoditas Non Obat dan Makanan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '05857',
  'name': 'Surat Keterangan Impor / Special Access Scheme (SAS)',
  'description': 'Surat Keterangan Impor / Special Access Scheme (SAS)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '06001',
  'name': 'Nomor Pendaftaran Alat Kesehatan',
  'description': 'Nomor Pendaftaran Alat Kesehatan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '06002',
  'name': 'Laporan Surveyor',
  'description': 'Laporan Surveyor',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '06006',
  'name': 'SPI Narkotika',
  'description': 'SPI Narkotika',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '06007',
  'name': 'SPI Psikotropika',
  'description': 'SPI Psikotropika',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '06008',
  'name': 'Nomor Pendaftaran PKRT',
  'description': 'Nomor Pendaftaran PKRT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '06091',
  'name': 'SPI-Prekursor Farmasi',
  'description': 'SPI-Prekursor Farmasi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '06999',
  'name': 'Izin Edar Alat Kesehatan, Alat Kesehatan Diagnostik In Vitro, dan PKRT',
  'description': 'Izin Edar Alat Kesehatan, Alat Kesehatan Diagnostik In Vitro, dan PKRT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '07001',
  'name': 'Fasilitas Pertambangan',
  'description': 'Fasilitas Pertambangan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '08001',
  'name': 'Persetujuan Impor bahan nuklir dari BAPETEN',
  'description': 'Persetujuan Impor bahan nuklir dari BAPETEN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '08002',
  'name': 'Persetujuan Impor Sumber radiasi pengion dari BAPETEN',
  'description': 'Persetujuan Impor Sumber radiasi pengion dari BAPETEN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '09001',
  'name': 'Formulir Pemberitahuan kepada BI/PPATK',
  'description': 'Formulir Pemberitahuan kepada BI/PPATK',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '09003',
  'name': 'Persetujuan Pembawaan UKA',
  'description': 'Persetujuan Pembawaan UKA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '10001',
  'name': 'Ijin Impor dari Dep. Kebudayaan dan Pariwisata',
  'description': 'Ijin Impor dari Dep. Kebudayaan dan Pariwisata',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '11001',
  'name': 'SATS LN dari DepHut dan Izin CITES dari negara pengekspor.',
  'description': 'SATS LN dari DepHut dan Izin CITES dari negara pengekspor.',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '12001',
  'name': 'Sertifikasi',
  'description': 'Sertifikasi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '13001',
  'name': 'SNI Gula Kristal Mentah',
  'description': 'SNI Gula Kristal Mentah',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '13002',
  'name': 'Wajib izin impor dari Departemen Pertanian',
  'description': 'Wajib izin impor dari Departemen Pertanian',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '13003',
  'name': 'Wajib Izin dan/atau Pendaftaran Pestisida dari Menteri Pertanian',
  'description': 'Wajib Izin dan/atau Pendaftaran Pestisida dari Menteri Pertanian',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '13604',
  'name': 'Rekomendasi Impor Produk Holtikultura',
  'description': 'Rekomendasi Impor Produk Holtikultura',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '14001',
  'name': 'Sertifikat Produk Penggunaan Tanda SNI',
  'description': 'Sertifikat Produk Penggunaan Tanda SNI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '14003',
  'name': 'Pengecualian SNI',
  'description': 'Pengecualian SNI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '14210',
  'name': 'Rekomendasi IP Tekstil',
  'description': 'Rekomendasi IP Tekstil',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '15001',
  'name': 'Wajib Izin Impor dari POLRI',
  'description': 'Wajib Izin Impor dari POLRI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '16000',
  'name': 'Dilarang',
  'description': 'Dilarang',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '16001',
  'name': 'Surat Keterangan Registrasi Bahan Berbahaya dan Beracun (B3)',
  'description': 'Surat Keterangan Registrasi Bahan Berbahaya dan Beracun (B3)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '17001',
  'name': 'SNI',
  'description': 'SNI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '17002',
  'name': 'Nomor Pelumas Terdaftar',
  'description': 'Nomor Pelumas Terdaftar',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '17003',
  'name': 'Ijin Usaha Niaga Umum/Ijin Usaha Niaga Terbatas',
  'description': 'Ijin Usaha Niaga Umum/Ijin Usaha Niaga Terbatas',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '17004',
  'name': 'Izin pencantuman tanda SKEM dan Label Tanda Hemat Energi/Rekomendasi pengiriman sampel uji Piranti '
          'Pengkondisi Udara',
  'description': 'Izin pencantuman tanda SKEM dan Label Tanda Hemat Energi/Rekomendasi pengiriman sampel uji Piranti '
                 'Pengkondisi Udara',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '21001',
  'name': 'Nomor Pendaftaran Obat Ikan',
  'description': 'Nomor Pendaftaran Obat Ikan',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22002',
  'name': 'BP Kawasan Batam',
  'description': 'BP Kawasan Batam',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22009',
  'name': 'IT Cakram Optik',
  'description': 'IT Cakram Optik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22013',
  'name': 'IP Plastik',
  'description': 'IP Plastik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22016',
  'name': 'IP Cakram Optik',
  'description': 'IP Cakram Optik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22049',
  'name': 'IT Kendaraan Bermotor',
  'description': 'IT Kendaraan Bermotor',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22215',
  'name': 'IP Garam Industri',
  'description': 'IP Garam Industri',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22306',
  'name': 'IT Garam Yodium',
  'description': 'IT Garam Yodium',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22308',
  'name': 'IT Mesin Multi Fungsi Berwarna',
  'description': 'IT Mesin Multi Fungsi Berwarna',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22309',
  'name': 'IT Minuman Beralkohol',
  'description': 'IT Minuman Beralkohol',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22519',
  'name': 'Alas Kaki',
  'description': 'Alas Kaki',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22520',
  'name': 'Elektronik',
  'description': 'Elektronik',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22521',
  'name': 'Mainan Anak-anak',
  'description': 'Mainan Anak-anak',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22522',
  'name': 'Garment/Pakaian jadi',
  'description': 'Garment/Pakaian jadi',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22523',
  'name': 'Makanan dan Minuman',
  'description': 'Makanan dan Minuman',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22603',
  'name': 'IT Hortikultura',
  'description': 'IT Hortikultura',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22701',
  'name': 'IT Alat Mesin dan Pertanian',
  'description': 'IT Alat Mesin dan Pertanian',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22850',
  'name': 'Kosmetik (Kecantikan)',
  'description': 'Kosmetik (Kecantikan)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '22851',
  'name': 'Obat Tradisionil',
  'description': 'Obat Tradisionil',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'},
 {'reference_slug': 'referensi-ijin',
  'reference_name': 'Referensi Ijin',
  'code': '23001',
  'name': 'Ijin BKPM',
  'description': 'Ijin BKPM',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-ijin.md'}]
