"""Seeder master data CEISA untuk referensi cara bayar.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_CARA_BAYAR_CODES = [{'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '1',
  'name': 'BIASA/TUNAI',
  'description': 'BIASA/TUNAI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '2',
  'name': 'BERKALA',
  'description': 'BERKALA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '3',
  'name': 'DENGAN JAMINAN',
  'description': 'DENGAN JAMINAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '4',
  'name': 'PERHITUNGAN KEMUDIAN',
  'description': 'PERHITUNGAN KEMUDIAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '5',
  'name': 'KONSINYASI (CONSIGNMENT)',
  'description': 'KONSINYASI (CONSIGNMENT)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '6',
  'name': 'USANCE LETTER OF CREDIT',
  'description': 'USANCE LETTER OF CREDIT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '7',
  'name': 'RED CLAUSE LETTER OF CREDIT',
  'description': 'RED CLAUSE LETTER OF CREDIT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '8',
  'name': 'INTER-COMPANY ACCOUNT',
  'description': 'INTER-COMPANY ACCOUNT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '9',
  'name': 'GABUNGAN/LAINNYA',
  'description': 'GABUNGAN/LAINNYA',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '10',
  'name': 'PEMBAYARAN KEMUDIAN (OPEN ACCOUNT) SECARA BERTAHAP',
  'description': 'PEMBAYARAN KEMUDIAN (OPEN ACCOUNT) SECARA BERTAHAP',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '11',
  'name': 'PEMBAYARAN KEMUDIAN (OPEN ACCOUNT) SECARA TUNAI',
  'description': 'PEMBAYARAN KEMUDIAN (OPEN ACCOUNT) SECARA TUNAI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '12',
  'name': 'DILAKUKAN DI DN DENGAN PEMBAYARAN UANG TUNAI',
  'description': 'DILAKUKAN DI DN DENGAN PEMBAYARAN UANG TUNAI',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '13',
  'name': 'DILAKUKAN DI DN DENGAN PEMBAYARAN MELALUI TELEGRAPH',
  'description': 'DILAKUKAN DI DN DENGAN PEMBAYARAN MELALUI TELEGRAPH',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '14',
  'name': 'DILAKUKAN TANPA PEMBAYARAN',
  'description': 'DILAKUKAN TANPA PEMBAYARAN',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '15',
  'name': 'PEMBAYARAN DIMUKA (ADVANCE PAYMENT)',
  'description': 'PEMBAYARAN DIMUKA (ADVANCE PAYMENT)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '16',
  'name': 'SIGHT LETTER OF CREDIT',
  'description': 'SIGHT LETTER OF CREDIT',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'},
 {'reference_slug': 'referensi-cara-bayar',
  'reference_name': 'Referensi Cara Bayar',
  'code': '17',
  'name': 'INKASO (COLLECTION DRAFT)',
  'description': 'INKASO (COLLECTION DRAFT)',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-bayar.md'}]
