"""Seeder master data CEISA untuk referensi spesifikasi khusus.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_SPESIFIKASI_KHUSUS_CODES = [{'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '2',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '3',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '4',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '5',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '6',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '7',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '8',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '9',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '10',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '11',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '12',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '13',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '14',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '15',
  'name': 'CHEMICAL ABSTRACT SERVICE (CAS)',
  'description': 'CHEMICAL ABSTRACT SERVICE (CAS)',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '16',
  'name': 'CHEMICAL ABSTRACT SERVICE (CAS)',
  'description': 'CHEMICAL ABSTRACT SERVICE (CAS)',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '17',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '18',
  'name': 'ICUMSA',
  'description': 'ICUMSA',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '19',
  'name': 'KENDARAAN BERMOTOR',
  'description': 'KENDARAAN BERMOTOR',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1001',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1002',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1003',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1004',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1005',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1006',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1007',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1008',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1009',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1010',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1011',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1012',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1013',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1014',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1015',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1016',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1017',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1018',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1019',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True},
 {'reference_slug': 'referensi-spesifikasi-khusus',
  'reference_name': 'Referensi Spesifikasi Khusus',
  'code': '1020',
  'name': 'LARTAS',
  'description': 'LARTAS',
  'is_active': True}]
