"""Seeder master data CEISA untuk referensi jenis pungutan.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_JENIS_PUNGUTAN_CODES = [{'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'BK',
  'name': 'Bea Keluar',
  'description': 'Bea Keluar',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'BM',
  'name': 'Bea Masuk',
  'description': 'Bea Masuk',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'BMAD',
  'name': 'Bea Masuk Anti Dumping',
  'description': 'Bea Masuk Anti Dumping',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'BMI',
  'name': 'Bea Masuk Imbalan',
  'description': 'Bea Masuk Imbalan',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'BMKITE',
  'name': 'Bea Masuk KITE',
  'description': 'Bea Masuk KITE',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'BMP',
  'name': 'Bea Masuk Pembalasan',
  'description': 'Bea Masuk Pembalasan',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'BMTP',
  'name': 'Bea Masuk Tindakan Pengamanan',
  'description': 'Bea Masuk Tindakan Pengamanan',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'CEA',
  'name': 'Cukai Etil Alkohol',
  'description': 'Cukai Etil Alkohol',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'CMEA',
  'name': 'Cukai Minuman Mengandung Etil Alkohol',
  'description': 'Cukai Minuman Mengandung Etil Alkohol',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'CTEM',
  'name': 'Cukai Tembakau',
  'description': 'Cukai Tembakau',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'DENDA',
  'name': 'Denda Administrasi Pabean',
  'description': 'Denda Administrasi Pabean',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'DS',
  'name': 'Dana Sawit',
  'description': 'Dana Sawit',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'PNBP',
  'name': 'Penerimaan Negara Bukan Pajak',
  'description': 'Penerimaan Negara Bukan Pajak',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'PPH',
  'name': 'PPh Impor',
  'description': 'PPh Impor',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'PPHEKSPOR',
  'name': 'PPh Ekspor',
  'description': 'PPh Ekspor',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'PPN',
  'name': 'PPN Impor',
  'description': 'PPN Impor',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'PPNBM',
  'name': 'PPnBM Impor',
  'description': 'PPnBM Impor',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-pungutan',
  'reference_name': 'Referensi Jenis Pungutan',
  'code': 'PPNLOKAL',
  'name': 'PPN Dalam Negeri / Hasil Tembakau',
  'description': 'PPN Dalam Negeri / Hasil Tembakau',
  'is_active': True}]
