"""Seeder master data CEISA untuk referensi kode jenis impor.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_JENIS_IMPOR_CODES = [{'reference_slug': 'referensi-jenis-impor',
  'reference_name': 'Referensi Kode Jenis Impor',
  'code': '1',
  'name': 'UNTUK DIPAKAI',
  'description': 'UNTUK DIPAKAI',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-impor',
  'reference_name': 'Referensi Kode Jenis Impor',
  'code': '2',
  'name': 'SEMENTARA',
  'description': 'SEMENTARA',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-impor',
  'reference_name': 'Referensi Kode Jenis Impor',
  'code': '3',
  'name': 'REIMPOR',
  'description': 'REIMPOR',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-impor',
  'reference_name': 'Referensi Kode Jenis Impor',
  'code': '4',
  'name': 'TPB',
  'description': 'TPB',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-impor',
  'reference_name': 'Referensi Kode Jenis Impor',
  'code': '5',
  'name': 'PELAYANAN SEGERA',
  'description': 'PELAYANAN SEGERA',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-impor',
  'reference_name': 'Referensi Kode Jenis Impor',
  'code': '6',
  'name': 'VOORUITSLAG',
  'description': 'VOORUITSLAG',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-impor',
  'reference_name': 'Referensi Kode Jenis Impor',
  'code': '7',
  'name': 'GABUNGAN',
  'description': 'GABUNGAN',
  'is_active': True}]
