"""Seeder master data CEISA untuk referensi tujuan pengeluaran.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_TUJUAN_PENGELUARAN_CODES = [{'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '512',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '512',
  'name': '2',
  'description': '2',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '512',
  'name': '3',
  'description': '3',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '512',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '512',
  'name': '5',
  'description': '5',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '512',
  'name': '6',
  'description': '6',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '512',
  'name': '7',
  'description': '7',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '512',
  'name': '8',
  'description': '8',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '512',
  'name': '9',
  'description': '9',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '2',
  'description': '2',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '3',
  'description': '3',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '5',
  'description': '5',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '6',
  'description': '6',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '7',
  'description': '7',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '8',
  'description': '8',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '9',
  'description': '9',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '10',
  'description': '10',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '513',
  'name': '11',
  'description': '11',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '1',
  'description': '1',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '2',
  'description': '2',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '3',
  'description': '3',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '4',
  'description': '4',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '5',
  'description': '5',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '6',
  'description': '6',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '7',
  'description': '7',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '8',
  'description': '8',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '9',
  'description': '9',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '10',
  'description': '10',
  'is_active': True},
 {'reference_slug': 'referensi-tujuan-pengeluaran',
  'reference_name': 'Referensi Tujuan Pengeluaran',
  'code': '522',
  'name': '11',
  'description': '11',
  'is_active': True}]
