"""Seeder master data CEISA untuk referensi jenis jaminan.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_JENIS_JAMINAN_CODES = [{'reference_slug': 'referensi-jenis-jaminan',
  'reference_name': 'Referensi Jenis Jaminan',
  'code': '1',
  'name': 'Tunai',
  'description': 'Tunai',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-jaminan',
  'reference_name': 'Referensi Jenis Jaminan',
  'code': '2',
  'name': 'Bank Garansi',
  'description': 'Bank Garansi',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-jaminan',
  'reference_name': 'Referensi Jenis Jaminan',
  'code': '3',
  'name': 'Customs Bond',
  'description': 'Customs Bond',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-jaminan',
  'reference_name': 'Referensi Jenis Jaminan',
  'code': '4',
  'name': 'Tertulis/CG',
  'description': 'Tertulis/CG',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-jaminan',
  'reference_name': 'Referensi Jenis Jaminan',
  'code': '5',
  'name': 'STTJ',
  'description': 'STTJ',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-jaminan',
  'reference_name': 'Referensi Jenis Jaminan',
  'code': '6',
  'name': 'Pusat',
  'description': 'Pusat',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-jaminan',
  'reference_name': 'Referensi Jenis Jaminan',
  'code': '7',
  'name': 'Indonesia EximBank',
  'description': 'Indonesia EximBank',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-jaminan',
  'reference_name': 'Referensi Jenis Jaminan',
  'code': '8',
  'name': 'Perusahaan Penjaminan',
  'description': 'Perusahaan Penjaminan',
  'is_active': True}]
