"""Seeder master data CEISA untuk referensi cara dagang.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_CARA_DAGANG_CODES = [{'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '1',
  'name': 'Biasa',
  'description': 'Biasa',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '2',
  'name': 'IMB - Imbal Dagang',
  'description': 'IMB - Imbal Dagang',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '3',
  'name': 'PMK - Pembayaran dimuka / Advance Payment',
  'description': 'PMK - Pembayaran dimuka / Advance Payment',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '4',
  'name': 'KMD Bertahap - Pembayaran Kemudian / Open Account Tunai',
  'description': 'KMD Bertahap - Pembayaran Kemudian / Open Account Tunai',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '5',
  'name': 'KMD Tunai - Pembayaran Kemudian / Open Account Tunai',
  'description': 'KMD Tunai - Pembayaran Kemudian / Open Account Tunai',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '6',
  'name': 'SLC - Sight Letter of Credit',
  'description': 'SLC - Sight Letter of Credit',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '7',
  'name': 'ULC - Usance Letter of Credit',
  'description': 'ULC - Usance Letter of Credit',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '8',
  'name': 'RLC - Red Clause Letter of Credit',
  'description': 'RLC - Red Clause Letter of Credit',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '9',
  'name': 'WSI - Wessel Inkaso / Collection Draft',
  'description': 'WSI - Wessel Inkaso / Collection Draft',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '10',
  'name': 'KON - Konsinyasi / Consignment',
  'description': 'KON - Konsinyasi / Consignment',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '11',
  'name': 'ICA - Inter Company Account',
  'description': 'ICA - Inter Company Account',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '12',
  'name': 'PDN Tunai - Pembayaran di Dalam Negeri Tunai',
  'description': 'PDN Tunai - Pembayaran di Dalam Negeri Tunai',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '13',
  'name': 'TT - Pembayaran di Dalam Negeri melalui Telegraph Transfer',
  'description': 'TT - Pembayaran di Dalam Negeri melalui Telegraph Transfer',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '14',
  'name': 'NCV - Dilakukan tanpa pembayaran',
  'description': 'NCV - Dilakukan tanpa pembayaran',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'},
 {'reference_slug': 'referensi-cara-dagang',
  'reference_name': 'Referensi Cara Dagang',
  'code': '15',
  'name': 'Lainnya',
  'description': 'Lainnya',
  'source': 'CEISA_GITBOOK',
  'is_active': True,
  'doc_url': 'https://ceisa40.gitbook.io/pia-ceisa40/referensi/referensi-cara-dagang.md'}]
