"""Seeder master data CEISA untuk referensi negara.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_NEGARA_CODES = [{'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AD',
  'name': 'ANDORRA',
  'description': 'ANDORRA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AE',
  'name': 'UNITED ARAB EMIRATES',
  'description': 'UNITED ARAB EMIRATES',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AF',
  'name': 'AFGHANISTAN',
  'description': 'AFGHANISTAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AG',
  'name': 'ANTIGUA AND BARBUDA',
  'description': 'ANTIGUA AND BARBUDA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AI',
  'name': 'ANGUILLA',
  'description': 'ANGUILLA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AL',
  'name': 'ALBANIA',
  'description': 'ALBANIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AM',
  'name': 'ARMENIA',
  'description': 'ARMENIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AN',
  'name': 'NETHERLANDS ANTILLES',
  'description': 'NETHERLANDS ANTILLES',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AO',
  'name': 'ANGOLA',
  'description': 'ANGOLA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AQ',
  'name': 'ANTARCTICA',
  'description': 'ANTARCTICA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AR',
  'name': 'ARGENTINA',
  'description': 'ARGENTINA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AS',
  'name': 'AMERICAN SAMOA',
  'description': 'AMERICAN SAMOA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AT',
  'name': 'AUSTRIA',
  'description': 'AUSTRIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AU',
  'name': 'AUSTRALIA',
  'description': 'AUSTRALIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AW',
  'name': 'ARUBA',
  'description': 'ARUBA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AX',
  'name': 'Aland Islands',
  'description': 'Aland Islands',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'AZ',
  'name': 'AZERBAIJAN',
  'description': 'AZERBAIJAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BA',
  'name': 'BOSNIA AND HERZEGOVINA',
  'description': 'BOSNIA AND HERZEGOVINA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BB',
  'name': 'BARBADOS',
  'description': 'BARBADOS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BD',
  'name': 'BANGLADESH',
  'description': 'BANGLADESH',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BE',
  'name': 'BELGIUM',
  'description': 'BELGIUM',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BF',
  'name': 'BURKINA FASO',
  'description': 'BURKINA FASO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BG',
  'name': 'BULGARIA',
  'description': 'BULGARIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BH',
  'name': 'BAHRAIN',
  'description': 'BAHRAIN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BI',
  'name': 'BURUNDI',
  'description': 'BURUNDI',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BJ',
  'name': 'BENIN',
  'description': 'BENIN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BL',
  'name': 'Saint Barthelemy',
  'description': 'Saint Barthelemy',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BM',
  'name': 'BERMUDA',
  'description': 'BERMUDA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BN',
  'name': 'BRUNEI DARUSSALAM',
  'description': 'BRUNEI DARUSSALAM',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BO',
  'name': 'BOLIVIA',
  'description': 'BOLIVIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BQ',
  'name': 'Bonaire, Sint Eustatius and Saba',
  'description': 'Bonaire, Sint Eustatius and Saba',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BR',
  'name': 'BRAZIL',
  'description': 'BRAZIL',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BS',
  'name': 'BAHAMAS',
  'description': 'BAHAMAS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BT',
  'name': 'BHUTAN',
  'description': 'BHUTAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BV',
  'name': 'BOUVET ISLAND',
  'description': 'BOUVET ISLAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BW',
  'name': 'BOTSWANA',
  'description': 'BOTSWANA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BY',
  'name': 'BELARUS',
  'description': 'BELARUS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'BZ',
  'name': 'BELIZE',
  'description': 'BELIZE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CA',
  'name': 'CANADA',
  'description': 'CANADA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CC',
  'name': 'COCOS (KEELING) ISLANDS',
  'description': 'COCOS (KEELING) ISLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CD',
  'name': 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
  'description': 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CF',
  'name': 'CENTRAL AFRICAN REPUBLIC',
  'description': 'CENTRAL AFRICAN REPUBLIC',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CG',
  'name': 'CONGO',
  'description': 'CONGO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CH',
  'name': 'SWITZERLAND',
  'description': 'SWITZERLAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CI',
  'name': "COTE D'IVOIRE",
  'description': "COTE D'IVOIRE",
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CK',
  'name': 'COOK ISLANDS',
  'description': 'COOK ISLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CL',
  'name': 'CHILE',
  'description': 'CHILE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CM',
  'name': 'CAMEROON',
  'description': 'CAMEROON',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CN',
  'name': 'CHINA',
  'description': 'CHINA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CO',
  'name': 'COLOMBIA',
  'description': 'COLOMBIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CR',
  'name': 'COSTA RICA',
  'description': 'COSTA RICA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CS',
  'name': 'FORMER CZECHOSLOVAKIA',
  'description': 'FORMER CZECHOSLOVAKIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CU',
  'name': 'CUBA',
  'description': 'CUBA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CV',
  'name': 'CAPE VERDE',
  'description': 'CAPE VERDE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CW',
  'name': 'Curacao',
  'description': 'Curacao',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CX',
  'name': 'CHRISTMAS ISLAND',
  'description': 'CHRISTMAS ISLAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CY',
  'name': 'CYPRUS',
  'description': 'CYPRUS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'CZ',
  'name': 'CZECH REPUBLIC',
  'description': 'CZECH REPUBLIC',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'DE',
  'name': 'GERMANY',
  'description': 'GERMANY',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'DJ',
  'name': 'DJIBOUTI',
  'description': 'DJIBOUTI',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'DK',
  'name': 'DENMARK',
  'description': 'DENMARK',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'DM',
  'name': 'DOMINICA',
  'description': 'DOMINICA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'DO',
  'name': 'DOMINICAN REPUBLIC',
  'description': 'DOMINICAN REPUBLIC',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'DZ',
  'name': 'ALGERIA',
  'description': 'ALGERIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'EC',
  'name': 'ECUADOR',
  'description': 'ECUADOR',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'EE',
  'name': 'ESTONIA',
  'description': 'ESTONIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'EG',
  'name': 'EGYPT',
  'description': 'EGYPT',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'EH',
  'name': 'WESTERN SAHARA',
  'description': 'WESTERN SAHARA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'ER',
  'name': 'ERITREA',
  'description': 'ERITREA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'ES',
  'name': 'SPAIN',
  'description': 'SPAIN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'ET',
  'name': 'ETHIOPIA',
  'description': 'ETHIOPIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'FI',
  'name': 'FINLAND',
  'description': 'FINLAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'FJ',
  'name': 'FIJI',
  'description': 'FIJI',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'FK',
  'name': 'FALKLAND ISLANDS (MALVINAS)',
  'description': 'FALKLAND ISLANDS (MALVINAS)',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'FM',
  'name': 'MICRONESIA, FEDERATED STATES OF',
  'description': 'MICRONESIA, FEDERATED STATES OF',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'FO',
  'name': 'FAROE ISLANDS',
  'description': 'FAROE ISLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'FR',
  'name': 'FRANCE',
  'description': 'FRANCE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GA',
  'name': 'GABON',
  'description': 'GABON',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GB',
  'name': 'UNITED KINGDOM',
  'description': 'UNITED KINGDOM',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GD',
  'name': 'GRENADA',
  'description': 'GRENADA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GE',
  'name': 'GEORGIA',
  'description': 'GEORGIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GF',
  'name': 'FRENCH GUIANA',
  'description': 'FRENCH GUIANA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GG',
  'name': 'Guernsey',
  'description': 'Guernsey',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GH',
  'name': 'GHANA',
  'description': 'GHANA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GI',
  'name': 'GIBRALTAR',
  'description': 'GIBRALTAR',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GL',
  'name': 'GREENLAND',
  'description': 'GREENLAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GM',
  'name': 'GAMBIA',
  'description': 'GAMBIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GN',
  'name': 'GUINEA',
  'description': 'GUINEA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GP',
  'name': 'GUADELOUPE',
  'description': 'GUADELOUPE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GQ',
  'name': 'EQUATORIAL GUINEA',
  'description': 'EQUATORIAL GUINEA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GR',
  'name': 'GREECE',
  'description': 'GREECE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GS',
  'name': 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISL',
  'description': 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISL',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GT',
  'name': 'GUATEMALA',
  'description': 'GUATEMALA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GU',
  'name': 'GUAM',
  'description': 'GUAM',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GW',
  'name': 'GUINEA-BISSAU',
  'description': 'GUINEA-BISSAU',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'GY',
  'name': 'GUYANA',
  'description': 'GUYANA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'HK',
  'name': 'HONG KONG',
  'description': 'HONG KONG',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'HM',
  'name': 'HEARD ISLAND AND MCDONALD ISLANDS',
  'description': 'HEARD ISLAND AND MCDONALD ISLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'HN',
  'name': 'HONDURAS',
  'description': 'HONDURAS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'HR',
  'name': 'CROATIA',
  'description': 'CROATIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'HT',
  'name': 'HAITI',
  'description': 'HAITI',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'HU',
  'name': 'HUNGARY',
  'description': 'HUNGARY',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'ID',
  'name': 'INDONESIA',
  'description': 'INDONESIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'IE',
  'name': 'IRELAND',
  'description': 'IRELAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'IL',
  'name': 'ISRAEL',
  'description': 'ISRAEL',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'IM',
  'name': 'Isle of Man',
  'description': 'Isle of Man',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'IN',
  'name': 'INDIA',
  'description': 'INDIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'IO',
  'name': 'BRITISH INDIAN OCEAN TERRITORY',
  'description': 'BRITISH INDIAN OCEAN TERRITORY',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'IQ',
  'name': 'IRAQ',
  'description': 'IRAQ',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'IR',
  'name': 'IRAN, ISLAMIC REPUBLIC OF',
  'description': 'IRAN, ISLAMIC REPUBLIC OF',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'IS',
  'name': 'ICELAND',
  'description': 'ICELAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'IT',
  'name': 'ITALY',
  'description': 'ITALY',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'JE',
  'name': 'Jersey',
  'description': 'Jersey',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'JM',
  'name': 'JAMAICA',
  'description': 'JAMAICA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'JO',
  'name': 'JORDAN',
  'description': 'JORDAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'JP',
  'name': 'JAPAN',
  'description': 'JAPAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KE',
  'name': 'KENYA',
  'description': 'KENYA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KG',
  'name': 'KYRGYZSTAN',
  'description': 'KYRGYZSTAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KH',
  'name': 'CAMBODIA',
  'description': 'CAMBODIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KI',
  'name': 'KIRIBATI',
  'description': 'KIRIBATI',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KM',
  'name': 'COMOROS',
  'description': 'COMOROS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KN',
  'name': 'SAINT KITTS AND NEVIS',
  'description': 'SAINT KITTS AND NEVIS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KP',
  'name': "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
  'description': "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KR',
  'name': 'KOREA, REPUBLIC OF',
  'description': 'KOREA, REPUBLIC OF',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KW',
  'name': 'KUWAIT',
  'description': 'KUWAIT',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KY',
  'name': 'CAYMAN ISLANDS',
  'description': 'CAYMAN ISLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'KZ',
  'name': 'KAZAKSTAN',
  'description': 'KAZAKSTAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LA',
  'name': "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
  'description': "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LB',
  'name': 'LEBANON',
  'description': 'LEBANON',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LC',
  'name': 'SAINT LUCIA',
  'description': 'SAINT LUCIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LI',
  'name': 'LIECHTENSTEIN',
  'description': 'LIECHTENSTEIN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LK',
  'name': 'SRI LANKA',
  'description': 'SRI LANKA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LR',
  'name': 'LIBERIA',
  'description': 'LIBERIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LS',
  'name': 'LESOTHO',
  'description': 'LESOTHO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LT',
  'name': 'LITHUANIA',
  'description': 'LITHUANIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LU',
  'name': 'LUXEMBOURG',
  'description': 'LUXEMBOURG',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LV',
  'name': 'LATVIA',
  'description': 'LATVIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'LY',
  'name': 'LIBYAN ARAB JAMAHIRIYA',
  'description': 'LIBYAN ARAB JAMAHIRIYA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MA',
  'name': 'MOROCCO',
  'description': 'MOROCCO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MC',
  'name': 'MONACO',
  'description': 'MONACO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MD',
  'name': 'MOLDOVA, REPUBLIC OF',
  'description': 'MOLDOVA, REPUBLIC OF',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'ME',
  'name': 'Montenegro',
  'description': 'Montenegro',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MF',
  'name': 'Saint Martin (French Part)',
  'description': 'Saint Martin (French Part)',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MG',
  'name': 'MADAGASCAR',
  'description': 'MADAGASCAR',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MH',
  'name': 'MARSHALL ISLANDS',
  'description': 'MARSHALL ISLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MK',
  'name': 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC',
  'description': 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'ML',
  'name': 'MALI',
  'description': 'MALI',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MM',
  'name': 'MYANMAR',
  'description': 'MYANMAR',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MN',
  'name': 'MONGOLIA',
  'description': 'MONGOLIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MO',
  'name': 'MACAU',
  'description': 'MACAU',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MP',
  'name': 'NORTHERN MARIANA ISLANDS',
  'description': 'NORTHERN MARIANA ISLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MQ',
  'name': 'MARTINIQUE',
  'description': 'MARTINIQUE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MR',
  'name': 'MAURITANIA',
  'description': 'MAURITANIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MS',
  'name': 'MONTSERRAT',
  'description': 'MONTSERRAT',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MT',
  'name': 'MALTA',
  'description': 'MALTA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MU',
  'name': 'MAURITIUS',
  'description': 'MAURITIUS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MV',
  'name': 'MALDIVES',
  'description': 'MALDIVES',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MW',
  'name': 'MALAWI',
  'description': 'MALAWI',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MX',
  'name': 'MEXICO',
  'description': 'MEXICO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MY',
  'name': 'MALAYSIA',
  'description': 'MALAYSIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'MZ',
  'name': 'MOZAMBIQUE',
  'description': 'MOZAMBIQUE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NA',
  'name': 'NAMIBIA',
  'description': 'NAMIBIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NC',
  'name': 'NEW CALEDONIA',
  'description': 'NEW CALEDONIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NE',
  'name': 'NIGER',
  'description': 'NIGER',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NF',
  'name': 'NORFOLK ISLAND',
  'description': 'NORFOLK ISLAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NG',
  'name': 'NIGERIA',
  'description': 'NIGERIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NI',
  'name': 'NICARAGUA',
  'description': 'NICARAGUA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NL',
  'name': 'NETHERLANDS',
  'description': 'NETHERLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NO',
  'name': 'NORWAY',
  'description': 'NORWAY',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NP',
  'name': 'NEPAL',
  'description': 'NEPAL',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NR',
  'name': 'NAURU',
  'description': 'NAURU',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NU',
  'name': 'NIUE',
  'description': 'NIUE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'NZ',
  'name': 'NEW ZEALAND',
  'description': 'NEW ZEALAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'OM',
  'name': 'OMAN',
  'description': 'OMAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PA',
  'name': 'PANAMA',
  'description': 'PANAMA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PE',
  'name': 'PERU',
  'description': 'PERU',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PF',
  'name': 'FRENCH POLYNESIA',
  'description': 'FRENCH POLYNESIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PG',
  'name': 'PAPUA NEW GUINEA',
  'description': 'PAPUA NEW GUINEA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PH',
  'name': 'PHILIPPINES',
  'description': 'PHILIPPINES',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PK',
  'name': 'PAKISTAN',
  'description': 'PAKISTAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PL',
  'name': 'POLAND',
  'description': 'POLAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PM',
  'name': 'SAINT PIERRE AND MIQUELON',
  'description': 'SAINT PIERRE AND MIQUELON',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PN',
  'name': 'PITCAIRN',
  'description': 'PITCAIRN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PR',
  'name': 'PUERTO RICO',
  'description': 'PUERTO RICO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PS',
  'name': 'PALESTINIAN TERRITORY, OCCUPIED',
  'description': 'PALESTINIAN TERRITORY, OCCUPIED',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PT',
  'name': 'PORTUGAL',
  'description': 'PORTUGAL',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PW',
  'name': 'PALAU',
  'description': 'PALAU',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'PY',
  'name': 'PARAGUAY',
  'description': 'PARAGUAY',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'QA',
  'name': 'QATAR',
  'description': 'QATAR',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'RE',
  'name': 'REUNION',
  'description': 'REUNION',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'RO',
  'name': 'ROMANIA',
  'description': 'ROMANIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'RS',
  'name': 'SERBIA',
  'description': 'SERBIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'RU',
  'name': 'RUSSIAN FEDERATION',
  'description': 'RUSSIAN FEDERATION',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'RW',
  'name': 'RWANDA',
  'description': 'RWANDA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SA',
  'name': 'SAUDI ARABIA',
  'description': 'SAUDI ARABIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SB',
  'name': 'SOLOMON ISLANDS',
  'description': 'SOLOMON ISLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SC',
  'name': 'SEYCHELLES',
  'description': 'SEYCHELLES',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SD',
  'name': 'SUDAN',
  'description': 'SUDAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SE',
  'name': 'SWEDEN',
  'description': 'SWEDEN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SG',
  'name': 'SINGAPORE',
  'description': 'SINGAPORE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SH',
  'name': 'SAINT HELENA',
  'description': 'SAINT HELENA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SI',
  'name': 'SLOVENIA',
  'description': 'SLOVENIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SJ',
  'name': 'SVALBARD AND JAN MAYEN',
  'description': 'SVALBARD AND JAN MAYEN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SK',
  'name': 'SLOVAKIA',
  'description': 'SLOVAKIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SL',
  'name': 'SIERRA LEONE',
  'description': 'SIERRA LEONE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SM',
  'name': 'SAN MARINO',
  'description': 'SAN MARINO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SN',
  'name': 'SENEGAL',
  'description': 'SENEGAL',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SO',
  'name': 'SOMALIA',
  'description': 'SOMALIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SR',
  'name': 'SURINAME',
  'description': 'SURINAME',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SS',
  'name': 'South Sudan',
  'description': 'South Sudan',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'ST',
  'name': 'SAO TOME AND PRINCIPE',
  'description': 'SAO TOME AND PRINCIPE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SV',
  'name': 'EL SALVADOR',
  'description': 'EL SALVADOR',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SX',
  'name': 'Sint Maarten (Dutch Part)',
  'description': 'Sint Maarten (Dutch Part)',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SY',
  'name': 'SYRIAN ARAB REPUBLIC',
  'description': 'SYRIAN ARAB REPUBLIC',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'SZ',
  'name': 'SWAZILAND',
  'description': 'SWAZILAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TC',
  'name': 'TURKS AND CAICOS ISLANDS',
  'description': 'TURKS AND CAICOS ISLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TD',
  'name': 'CHAD',
  'description': 'CHAD',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TF',
  'name': 'FRENCH SOUTHERN TERRITORIES',
  'description': 'FRENCH SOUTHERN TERRITORIES',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TG',
  'name': 'TOGO',
  'description': 'TOGO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TH',
  'name': 'THAILAND',
  'description': 'THAILAND',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TJ',
  'name': 'TAJIKISTAN',
  'description': 'TAJIKISTAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TK',
  'name': 'TOKELAU',
  'description': 'TOKELAU',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TL',
  'name': 'Timor-Leste',
  'description': 'Timor-Leste',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TM',
  'name': 'TURKMENISTAN',
  'description': 'TURKMENISTAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TN',
  'name': 'TUNISIA',
  'description': 'TUNISIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TO',
  'name': 'TONGA',
  'description': 'TONGA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TP',
  'name': 'EAST TIMOR',
  'description': 'EAST TIMOR',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TR',
  'name': 'TURKEY',
  'description': 'TURKEY',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TT',
  'name': 'TRINIDAD AND TOBAGO',
  'description': 'TRINIDAD AND TOBAGO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TV',
  'name': 'TUVALU',
  'description': 'TUVALU',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TW',
  'name': 'TAIWAN, PROVINCE OF CHINA',
  'description': 'TAIWAN, PROVINCE OF CHINA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'TZ',
  'name': 'TANZANIA, UNITED REPUBLIC OF',
  'description': 'TANZANIA, UNITED REPUBLIC OF',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'UA',
  'name': 'UKRAINE',
  'description': 'UKRAINE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'UG',
  'name': 'UGANDA',
  'description': 'UGANDA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'UM',
  'name': 'UNITED STATES MINOR OUTLYING ISLANDS',
  'description': 'UNITED STATES MINOR OUTLYING ISLANDS',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'US',
  'name': 'UNITED STATES',
  'description': 'UNITED STATES',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'UY',
  'name': 'URUGUAY',
  'description': 'URUGUAY',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'UZ',
  'name': 'UZBEKISTAN',
  'description': 'UZBEKISTAN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'VA',
  'name': 'HOLY SEE (VATICAN CITY STATE)',
  'description': 'HOLY SEE (VATICAN CITY STATE)',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'VC',
  'name': 'SAINT VINCENT AND THE GRENADINES',
  'description': 'SAINT VINCENT AND THE GRENADINES',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'VE',
  'name': 'VENEZUELA',
  'description': 'VENEZUELA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'VG',
  'name': 'VIRGIN ISLANDS, BRITISH',
  'description': 'VIRGIN ISLANDS, BRITISH',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'VI',
  'name': 'VIRGIN ISLANDS, U.S.',
  'description': 'VIRGIN ISLANDS, U.S.',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'VN',
  'name': 'VIET NAM',
  'description': 'VIET NAM',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'VU',
  'name': 'VANUATU',
  'description': 'VANUATU',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'WF',
  'name': 'WALLIS AND FUTUNA',
  'description': 'WALLIS AND FUTUNA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'WS',
  'name': 'SAMOA',
  'description': 'SAMOA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'XZ',
  'name': 'KOSOVO',
  'description': 'KOSOVO',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'YE',
  'name': 'YEMEN',
  'description': 'YEMEN',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'YT',
  'name': 'MAYOTTE',
  'description': 'MAYOTTE',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'YU',
  'name': 'YUGOSLAVIA',
  'description': 'YUGOSLAVIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'ZA',
  'name': 'SOUTH AFRICA',
  'description': 'SOUTH AFRICA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'ZM',
  'name': 'ZAMBIA',
  'description': 'ZAMBIA',
  'is_active': True},
 {'reference_slug': 'referensi-negara',
  'reference_name': 'Referensi Negara',
  'code': 'ZW',
  'name': 'ZIMBABWE',
  'description': 'ZIMBABWE',
  'is_active': True}]
