"""Seeder master data CEISA untuk referensi kategori keluar ftz.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_KATEGORI_KELUAR_FTZ_CODES = [{'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '001',
  'name': 'Pengeluaran Biasa',
  'description': 'Pengeluaran Biasa',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '002',
  'name': 'Pengeluaran Khusus Barang Kiriman (Pos atau Jasa Titipan)',
  'description': 'Pengeluaran Khusus Barang Kiriman (Pos atau Jasa Titipan)',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '003',
  'name': 'Pengeluaran Khusus Barang Pindahan',
  'description': 'Pengeluaran Khusus Barang Pindahan',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '004',
  'name': 'Pengeluaran Khusus Barang Perwakilan Negara Asing atau Badan Internasional',
  'description': 'Pengeluaran Khusus Barang Perwakilan Negara Asing atau Badan Internasional',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '005',
  'name': 'Pengeluaran Khusus Barang untuk Keperluan Ibadah untuk Umum, Sosial, Pendidikan, Kebudayaan, Olah Raga, '
          'atau Bencana Alam',
  'description': 'Pengeluaran Khusus Barang untuk Keperluan Ibadah untuk Umum, Sosial, Pendidikan, Kebudayaan, Olah '
                 'Raga, atau Bencana Alam',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '006',
  'name': 'Pengeluaran Khusus Barang Cinderamata',
  'description': 'Pengeluaran Khusus Barang Cinderamata',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '007',
  'name': 'Pengeluaran Khusus Barang Contoh',
  'description': 'Pengeluaran Khusus Barang Contoh',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '008',
  'name': 'Pengeluaran Khusus Barang untuk Keperluan Penelitian',
  'description': 'Pengeluaran Khusus Barang untuk Keperluan Penelitian',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '009',
  'name': 'Pengeluaran Sementara dari Kawasan Bebas',
  'description': 'Pengeluaran Sementara dari Kawasan Bebas',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '010',
  'name': 'Pengeluaran Kembali dari Kawasan Bebas ke Luar Daerah Pabean atas Barang yang Nyata-nyata Berasal dari Luar '
          'Daerah Pabean',
  'description': 'Pengeluaran Kembali dari Kawasan Bebas ke Luar Daerah Pabean atas Barang yang Nyata-nyata Berasal '
                 'dari Luar Daerah Pabean',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '011',
  'name': 'Pengeluaran Kembali dari Kawasan Bebas ke Kawasan Bebas Lainnya/TPB/KEK atas Barang yang Nyata-nyata '
          'Berasal dari Kawasan Bebas Lainnya/TPB/KEK',
  'description': 'Pengeluaran Kembali dari Kawasan Bebas ke Kawasan Bebas Lainnya/TPB/KEK atas Barang yang Nyata-nyata '
                 'Berasal dari Kawasan Bebas Lainnya/TPB/KEK',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '012',
  'name': 'Pengeluaran Kembali dari Kawasan Bebas ke Tempat Lain Dalam Daerah Pabean atas Barang yang Nyata-nyata '
          'Berasal dari Tempat Lain Dalam Daerah Pabean',
  'description': 'Pengeluaran Kembali dari Kawasan Bebas ke Tempat Lain Dalam Daerah Pabean atas Barang yang '
                 'Nyata-nyata Berasal dari Tempat Lain Dalam Daerah Pabean',
  'is_active': True},
 {'reference_slug': 'referensi-kategori-keluar-ftz',
  'reference_name': 'Referensi Kategori Keluar FTZ',
  'code': '013',
  'name': 'Pengeluaran Khusus ke Kawasan Bebas oleh penumpang, awak sarana pengangkut, pelintas batas, atau barang '
          'kiriman',
  'description': 'Pengeluaran Khusus ke Kawasan Bebas oleh penumpang, awak sarana pengangkut, pelintas batas, atau '
                 'barang kiriman',
  'is_active': True}]
