"""Seeder master data CEISA untuk referensi jenis tpb.

Snapshot tanggal: 2026-04-27
"""

CEISA_REFERENCE_JENIS_TPB_CODES = [{'reference_slug': 'referensi-jenis-tpb',
  'reference_name': 'Referensi Jenis TPB',
  'code': '1',
  'name': 'KAWASAN BERIKAT',
  'description': 'KAWASAN BERIKAT',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-tpb',
  'reference_name': 'Referensi Jenis TPB',
  'code': '2',
  'name': 'GUDANG BERIKAT',
  'description': 'GUDANG BERIKAT',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-tpb',
  'reference_name': 'Referensi Jenis TPB',
  'code': '3',
  'name': 'TPPB',
  'description': 'TPPB',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-tpb',
  'reference_name': 'Referensi Jenis TPB',
  'code': '4',
  'name': 'TBB',
  'description': 'TBB',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-tpb',
  'reference_name': 'Referensi Jenis TPB',
  'code': '5',
  'name': 'TLB',
  'description': 'TLB',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-tpb',
  'reference_name': 'Referensi Jenis TPB',
  'code': '6',
  'name': 'KDUB',
  'description': 'KDUB',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-tpb',
  'reference_name': 'Referensi Jenis TPB',
  'code': '7',
  'name': 'LAINNYA',
  'description': 'LAINNYA',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-tpb',
  'reference_name': 'Referensi Jenis TPB',
  'code': '8',
  'name': 'KAWASAN BEBAS',
  'description': 'KAWASAN BEBAS',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-tpb',
  'reference_name': 'Referensi Jenis TPB',
  'code': '9',
  'name': 'KAWASAN EKONOMI KHUSUS',
  'description': 'KAWASAN EKONOMI KHUSUS',
  'is_active': True},
 {'reference_slug': 'referensi-jenis-tpb',
  'reference_name': 'Referensi Jenis TPB',
  'code': '10',
  'name': 'KAWASAN EKONOMI LAINNYA',
  'description': 'KAWASAN EKONOMI LAINNYA',
  'is_active': True}]
