DISCREPANCY_CODES = [
    # --- Quantity ---
    {
        "code": "SHP",
        "category": "Quantity",
        "name": "Short Pieces",
        "description": "Jumlah pieces diterima kurang dari data manifest/awb.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "OVR",
        "category": "Quantity",
        "name": "Over Pieces",
        "description": "Jumlah pieces diterima lebih dari data manifest/awb.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "MIS",
        "category": "Quantity",
        "name": "Missing Cargo",
        "description": "AWB ada di manifest tetapi fisik tidak ditemukan.",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "PAR",
        "category": "Quantity",
        "name": "Partial Received",
        "description": "Cargo diterima sebagian (partial).",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "ULD-S",
        "category": "Quantity",
        "name": "Short from ULD",
        "description": "Kekurangan pieces terdeteksi saat buka ULD.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    # --- Weight ---
    {
        "code": "SWT",
        "category": "Weight",
        "name": "Short Weight",
        "description": "Berat aktual kurang dari data dokumen/EDI.",
        "severity": "MINOR",
        "hold_delivery": False,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "OWT",
        "category": "Weight",
        "name": "Over Weight",
        "description": "Berat aktual lebih dari data dokumen/EDI.",
        "severity": "MINOR",
        "hold_delivery": False,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "WDM",
        "category": "Weight",
        "name": "Weight Difference Major",
        "description": "Selisih berat di atas toleransi (major).",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "WDI",
        "category": "Weight",
        "name": "Weight Difference Minor",
        "description": "Selisih berat kecil (minor/informational).",
        "severity": "INFO",
        "hold_delivery": False,
        "require_photo": False,
        "require_remark": False,
        "is_active": True,
    },
    # --- Condition / Damage ---
    {
        "code": "DMG",
        "category": "Condition",
        "name": "Damaged Cargo",
        "description": "Cargo rusak/penyok/robek.",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "WET",
        "category": "Condition",
        "name": "Wet Cargo",
        "description": "Cargo basah/terkena cairan.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "BRK",
        "category": "Condition",
        "name": "Broken Package",
        "description": "Kemasan pecah atau terbuka.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "TAM",
        "category": "Condition",
        "name": "Tampered",
        "description": "Indikasi kemasan dibuka/dirusak.",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "LEK",
        "category": "Condition",
        "name": "Leakage",
        "description": "Bocor (liquid/chemical).",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    # --- ULD / Packaging ---
    {
        "code": "ULD-DMG",
        "category": "ULD",
        "name": "ULD Damaged",
        "description": "ULD rusak.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "ULD-MIS",
        "category": "ULD",
        "name": "ULD Missing",
        "description": "ULD di manifest tidak ditemukan.",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "ULD-OVR",
        "category": "ULD",
        "name": "ULD Over",
        "description": "ULD ekstra tidak tercantum di manifest.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "PKG-BAD",
        "category": "ULD",
        "name": "Improper Packing",
        "description": "Packing tidak sesuai/unsafe.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "PLT-ISS",
        "category": "ULD",
        "name": "Pallet Issue",
        "description": "Masalah pallet (rusak/kurang/over).",
        "severity": "MINOR",
        "hold_delivery": False,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    # --- Documentation ---
    {
        "code": "DOC-MIS",
        "category": "Documentation",
        "name": "Missing Document",
        "description": "Dokumen tidak lengkap.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "DOC-INV",
        "category": "Documentation",
        "name": "Invalid Document",
        "description": "Dokumen salah/tidak valid.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "FWB-MIS",
        "category": "Documentation",
        "name": "No FWB",
        "description": "FWB tidak tersedia pada saat dibutuhkan.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "FHL-MIS",
        "category": "Documentation",
        "name": "No FHL",
        "description": "FHL tidak tersedia untuk consol.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "DATA-MIS",
        "category": "Documentation",
        "name": "Data Mismatch",
        "description": "Data EDI tidak konsisten antar message (FWB/FHL/FFM).",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    # --- Routing / Flight ---
    {
        "code": "MIS-ROU",
        "category": "Routing",
        "name": "Misrouted",
        "description": "Cargo salah rute.",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "OFF-LD",
        "category": "Routing",
        "name": "Offloaded",
        "description": "Cargo tidak ikut flight (offloaded).",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "OVC",
        "category": "Routing",
        "name": "Overcarried",
        "description": "Cargo terbawa melewati tujuan.",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "UND",
        "category": "Routing",
        "name": "Undercarried",
        "description": "Sebagian cargo tertinggal (undercarried).",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "FLT-ERR",
        "category": "Routing",
        "name": "Flight Error",
        "description": "Kesalahan flight/date pada data.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    # --- Security / Customs ---
    {
        "code": "SEC-HLD",
        "category": "Security",
        "name": "Security Hold",
        "description": "Ditahan security.",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "CUS-HLD",
        "category": "Security",
        "name": "Customs Hold",
        "description": "Ditahan Bea Cukai / Customs hold.",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "DG-ISS",
        "category": "Security",
        "name": "DG Issue",
        "description": "Masalah Dangerous Goods (label/doc/packing).",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "SCR-FAIL",
        "category": "Security",
        "name": "Screening Failed",
        "description": "Screening gagal/invalid.",
        "severity": "CRITICAL",
        "hold_delivery": True,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "SEAL-BRK",
        "category": "Security",
        "name": "Seal Broken",
        "description": "Seal rusak/tidak sesuai.",
        "severity": "MAJOR",
        "hold_delivery": True,
        "require_photo": True,
        "require_remark": True,
        "is_active": True,
    },
    # --- Operational / System ---
    {
        "code": "SYS-ERR",
        "category": "Operational",
        "name": "System Error",
        "description": "Kesalahan sistem/EDI/processing.",
        "severity": "MAJOR",
        "hold_delivery": False,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "SCAN-MIS",
        "category": "Operational",
        "name": "Scan Missing",
        "description": "Event scan tidak ada/terlewat.",
        "severity": "MINOR",
        "hold_delivery": False,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "TIME-ERR",
        "category": "Operational",
        "name": "Time Mismatch",
        "description": "Timestamp tidak sesuai/invalid.",
        "severity": "MINOR",
        "hold_delivery": False,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
    {
        "code": "OPR-ERR",
        "category": "Operational",
        "name": "Operational Error",
        "description": "Human error operasional (mis-handle, salah input).",
        "severity": "MINOR",
        "hold_delivery": False,
        "require_photo": False,
        "require_remark": True,
        "is_active": True,
    },
]
