filebeat.inputs:
  - type: filestream
    id: fastapi-json
    enabled: true
    paths:
      - "C:/Users/wisnu/Documents/Belajar/materialize-project/materialize-fastapi/logs/app.log"
    parsers:
      - ndjson:
          keys_under_root: true
          add_error_key: true
          overwrite_keys: true
          expand_keys: true
          # penting: pastikan ini cocok dengan log JSON kamu
          target: ""
    fields:
      service: fastapi
      environment: dev
    fields_under_root: true

output.logstash:
  hosts: ["11.10.10.21:5000"]
  ssl.enabled: false

logging:
  level: info
  to_files: true
  files:
    path: C:/Elastic/Filebeat/logs
    name: filebeat
    keepfiles: 7
