[tool.poetry]
name = "fastapi-project"
version = "0.1.0"
description = "FastAPI starter project with JWT authentication and MySQL"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false  # ✅ Non-package mode

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = { extras = ["standard"], version = "^0.30.1" }
sqlalchemy = "^2.0.30"
pymysql = "^1.1.0"
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
python-jose = { extras = ["cryptography"], version = "^3.3.0" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
